modules/module_user_general.php
The menuitem.Sequence was missing in the Select statement, while being used in the Order By statement.
See problem and solution log here:
https://community.xibo.org.uk/t/admin-panel-does-not-show-navigation-bar/4601/9
=> Fix SQL query

lib/Xmds/Soap4.php
Please ignore the [previous](https://github.com/xibosignage/xibo-cms/pull/131) PR.
Detect image format, convert to preferred format if necessary and possible.
Check the image format from data submitted by a Player and do conversion if
the incoming format is different with preferred format, provided that the php
extension, imagick in this case, is available and enabled, and supports conversion
from the detected format to preferred one.
On successful conversion, the `$screenShot` variable will contain the converted
binary data.
On failure conversion and when the incoming format != preferred format,
the method returns `false`.
On detection failure and conversion failure, the method flow doesn't change.
xibosignage/xibo#689
=> Detect image format, convert to preferred format if necessary and possible.

lib/app/session.class.php, lib/data/display.data.class.php
- Session locking during upgrade. 
- Fail to notify displays running campaigns with layouts assigned when one of those layouts is updated.
=> 1.7.7 pre release testing

views/layout-designer-page.twig
I don't know why this button had a hidden-md class added, but it makes it impossible (even as a superuser) to add more regions to a layout.
=> Fix hidden region add button

web/theme/default/js/xibo-forms.js
If we use this function on a page that does not have a global variable named table a bug happens. We cannot test simply to see if the table variable exists because table exists as a built-in function in modern browsers (console.table is aliased to table).
I've tested the "if (backgroundChanges && table)" construction which due to it existing causes weirdness. This is the only way to test if table actually exists.
=> Fix this function on a page without table

lib/Helper/Session.php
Session information was displaying the proxy server's IP address instead of client address. I found this issue - https://github.com/xibosignage/xibo/issues/606 - and it seems like it was fixed when referencing display IP addresses but not session, so I added the same function found in https://github.com/xibosignage/xibo-cms/blob/500f3e16fa525c7428a3bc1f98383a0bde6697d0/lib/Xmds/Soap.php#L1735-L1748
=> Session.php fix remoteaddr from Proxy

lib/Controller/Layout.php
Hello,
One of our needs was to be able to find, through the API, the "draft" Layout given the original "published" Layout's id.
This change allows a user to pass a `parentId` parameter to the `api/layout` endpoint to filter Layouts whose parent Layout has the given id.
=> Feature: Can search layouts filtered by ParentId

Dockerfile, docker/entrypoint.sh
This commit replaces the recursive chown in the entrypoint.sh for the cms folder to a non-recursive chown on some files and set the correct permissions when copying the files to the docker container.
See issue's https://github.com/xibosignage/xibo/issues/2010 and https://github.com/docker/for-linux/issues/388
=> Removed recursive chown

ui/src/core/xibo-cms.js, views/campaign-page.twig, views/dataset-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/layout-page.twig, views/library-page.twig, views/playlist-page.twig
fixes xibosignage/xibo#2347
- Table inline style with at 100%
- Row select fix
- Display grid "remote" field warning fix
=> Grid Folder feature: Fix double click and table horizontal resizing

ui/src/core/xibo-forms.js
Basically the stored data in table was only addressing the first set of results, changing to a different page or searching for an element not contained in that set would break that data.
By merging the permissions objects we get all needed data, and it seems to be fixed
=> Share: With Selected Share requires repeated attempts to apply desired settings

lib/XTR/CampaignSchedulerTask.php, lib/Xmds/Soap.php
- stops scheduling when we reach 100% of target
- stops scheduling when progress to target is 5% over
- splits plays needed by the number of logged in/valid displays in the schedule
- adjusts budget/impression targets based on logged in displays 
- only aggregates against the campaign for `layout` stats
=> Ad Campaigns: adjust scheduler for xibosignage/xibo#2971

lib/Xmds/Soap.php
This turned out to be a two-fold issue - the first being the campaign lookup, but before that the schedule look up. The final commit being where I had put the arrays to track deleted IDs inside the loop :facepalm: 
xibosignage/xibo#2989
=> XMDS: submit stats shouldn't error if the ad campaign isn't found

lib/Factory/TagTrait.php, lib/Xmds/Soap5.php
- On RegisterDisplay function, add `<tags>` xml element, populated with `<tag>` elements containing `<tagName>` element and if no not null also `<tagValue>` element per each Tag assigned to the Display.
Fixes xibosignage/xibo#2773
=> Widgets : Send Display tags and values in the xml on Register.

lib/Factory/LayoutFactory.php, lib/Xmds/Soap.php
=> Interactive : navigate to Layout action, fix potential infinite loop.

lib/Connector/XiboAudienceReportingConnector.php
- When a block of 5000 stats, all are skipped, (never called the `receiveStats()`, watermark has not updated) we move to the next block of 5000 stats. This would mean we are progressing.
- When `receiveStats()` is successful (a watermark has been saved) we no longer process the next block
https://github.com/xibosignage/xibo/issues/2990
=> Audience Connector Bug Fix: If a block of stats has nothing to send, progress next stat block

lib/Controller/Widget.php, lib/Entity/DataSet.php, lib/Entity/Module.php, lib/Entity/ModulePropertyTrait.php, lib/Event/DataSetDataRequestEvent.php, lib/Listener/DataSetDataProviderListener.php, lib/Middleware/ListenersMiddleware.php, lib/Widget/DataSetProvider.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Provider/DataProviderInterface.php, lib/Widget/Provider/WidgetProviderInterface.php, lib/Widget/Provider/WidgetProviderTrait.php, lib/Widget/Render/WidgetDataProviderCache.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php
This is still a work in progress which needs testing.
xibosignageltd/xibo-private#95
A listener has been implemented to serve DataSet data from the core software instead of a Connector, which is called from a Widget Provider. This should allow reuse of that data across multiple widgets. A connector didn't seem appropriate as the dataset is internal to Xibo - so we aren't connecting to a third party to retrieve it.
The Widget Provider uses an event to request this data so that it is not polluted with factories the developer shouldn't have access to.
A breaking change to the data output structure has been implemented. Previously calls to getData and the `json` file served to players contained an array of data points.
```json
[]
```
Now it will be enveloped:
```json
{
"data": [],
"meta": {} …
```
=> Widgets: DataSet data provider for DataSet Ticker/View widgets.

lib/Connector/XiboAudienceReportingConnector.php, views/xibo-audience-connector-form-settings.twig
- Connector should only send a block with a size of 5000 or batch size defined in connector provider settings
- Connector sets the watermark, sends a request to audience reporting service to update the watermark
- Watermark is the last statId of the block, that has been returned by the getStats()
https://github.com/xibosignageltd/xibo-private/issues/107
=> Audience connector: Running indefinitely for multiple blocks of stat

lib/Connector/XiboAudienceReportingConnector.php, lib/Controller/Stats.php, views/statistics-form-export.twig
Audience Connector/Send Stat:
- Start/End dates are saved in UTC format in MongoDB
- Convert those dates to the display time zone if a timezone is set on the display, otherwise use the CMS time zone
Proof of play CSV export:
- allow users to select a date format (UTC/CMS local time) when exporting stats
https://github.com/xibosignageltd/xibo-private/issues/114
=> Connector Report/Receive Stat: Send the start/end date in the local time zone

lib/Entity/Campaign.php
This is a fix for missing hours in the `campaign proof of play` report
- Audience Connector API should have a stat with the campaign start/end date in CMS timezone
- The "createFromFormat" function does not automatically use the CMS timezone, while the "createFromTimestamp" function does.
https://github.com/xibosignage/xibo/issues/3003
https://github.com/xibosignageltd/xibo-private/issues/114
=> Campaign start/end date should be in CMS timezone

lib/Widget/AlphaVantageBase.php, lib/Widget/Stocks.php, modules/stocks-form-settings.twig
- Stocks add isPaidPlan flag to Module settings
- Use different function in data query based on isPaidPlan flag
Data format is the same for both endpoints.
Fixes xibosignage/xibo#2995
=> Widgets : Stocks use different endpoint for free and paid plan

lib/Widget/AlphaVantageBase.php
Protect against attempts at parsing data not matching expected format, which leads to bunch of php warnings/notices
This is mostly for the case where a free Alpha Vantage API key was marked as paid key in the module, as we will not get the data from their API in such case.
https://github.com/xibosignage/xibo/issues/2995
=> Stocks Widget : Protect against unexpected data results

lib/Controller/Playlist.php, lib/Entity/Playlist.php, lib/Listener/OnUserDelete/PlaylistListener.php, lib/Middleware/ListenersMiddleware.php
- Use moduleFactory on Playlist Entity on delete
- Use SubPlaylist `getAssignedPlaylists()` (this will cover old Widget options)
- If Widget was not removed and requires save, go through SubPlaylistItems, adjust rowNo and make sure empty spots/spotLength are saved as string (same as on SubPlaylist edit)
https://github.com/xibosignage/xibo/issues/2997
=> Playlist : Fix delete issue with old SubPlaylist Widget options

lib/Factory/DisplayProfileFactory.php, views/task-page.twig
- Task : disable sorting on next run column
- Display Profile : make the default profile types always available, do not rely solely on database query on displayprofile table
=> BugFixes for 3.3.3 : Display Profile available types and Task next run sorting

lib/Entity/Schedule.php, lib/Factory/ScheduleFactory.php, lib/XTR/MaintenanceRegularTask.php
- Regular Maintenance : new function that looks for 90 days + old interrupt events with set parentCampaignId and deletes them making sure to not notify Displays (notify => false).
- Schedule Entity delete : add array of options with default notify true, do not even attempt to check inScheduleLookAhead if notify is set to false
Fixes xibosignage/xibo#2977
=> Ad Campaigns : tidy up interrupt schedules after 90 days.

ui/src/templates/forms/inputs/checkbox.hbs, ui/src/templates/forms/inputs/code.hbs, ui/src/templates/forms/inputs/color.hbs, ui/src/templates/forms/inputs/custom.hbs, ui/src/templates/forms/inputs/date.hbs, ui/src/templates/forms/inputs/dropdown.hbs, ui/src/templates/forms/inputs/hidden.hbs, ui/src/templates/forms/inputs/number.hbs, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/text.hbs
relates to xibosignageltd/xibo-private#100
Name field was being populated for the new XML form fields but not for the existing HBS forms like region and layout, and it was preventing those forms to save correctly.
We now check for `name`, and if it doesn't exist, we re-use `id` for it
=> Layout Editor: Fix "name" in dynamic fields

lib/Connector/XiboAudienceReportingConnector.php, lib/Storage/MongoDbTimeSeriesStore.php, lib/Storage/MySqlTimeSeriesStore.php, lib/Storage/TimeSeriesStoreInterface.php
To ensure that the results of the "getStats" query are stored in memory, set the MYSQL_ATTR_USE_BUFFERED_QUERY attribute to true when sending stats.
Fixes: https://github.com/xibosignage/xibo/issues/3009
=> Bug Fix 3.3.3: Fix for MySQL Audience Connector send stats

lib/Widget/DataSetTicker.php, lib/Widget/DataSetView.php
This is tricky as there is no elegant way to determine which images assigned to *any* module are the primary ones or not. This whole process has been improved in v4 because we do not assign non primary media directly to the widget anymore.
However until then we need to clear out library assignments specifically each time a dataset based widget is regenerated.
I think it is safe to do as noted in this PR, because the dataset widgets do not ever have a primary media assigned to them.
fixes xibosignage/xibo#3017
=> DataSet Widgets: workaround for library image links not being cleared on cache regenerate

lib/Entity/Schedule.php, lib/Xmds/Soap.php
XMDS: it looks like we're checking strings using `>` instead of waiting until they are actually dates.
Schedule: we are only including recurring events where the start date is greater than the month start - using an inclusive date check means we grab events which started in the prior month.
=> Fix recurring schedules which cross the month boundary. Optimise submit stats (date checking in wrong place)

lib/Controller/Module.php, lib/Widget/Definition/Property.php
Fixes: https://github.com/xibosignageltd/xibo-private/issues/145
Update the setting value even if the new setting value matches with the default value. Previously, we were ignoring update if the new value matched the default.
=> Module Settings: Form save isn't working

lib/Widget/RssProvider.php, lib/Widget/Ticker.php, modules/rss-ticker.xml
In Layout Editor, RSS Ticker widget will now have the option to set userAgent
Relates to: https://github.com/xibosignage/xibo/issues/2999
=> Ticker widget: add option to set the user agent (4.0.0)

lib/Widget/Ticker.php
- Fix for accidental placement for the Guzzle 'User-Agent'  in headers
=> Fix: userAgent should be in headers

views/display-page.twig
- Handling of webOS/Tizen data differently based on version for consistent formatting for older players.
Fixes https://github.com/xibosignage/xibo/issues/3004
=> Preserve old webos and tizen players status window data presentation

lib/Report/ProofOfPlay.php
I am not sure when this bug was introduced, apparently no one noticed this. We will have to fix that in 3.3.4 as well.
- Fixes https://github.com/xibosignage/xibo/issues/3032
=> Report: Proof of play schedule report cannot filter by media/layout

lib/Controller/UserGroup.php, lib/Entity/User.php, ui/src/core/xibo-cms.js
- User Group : Group admin permissions fix, specific handling for User Group entity, as we can't rely on ownerId (it's not a thing for user groups ) - https://github.com/xibosignage/xibo/issues/3019
- If we do not have any buttons to show in the row menu dropdown, then do not show the dropdown at all - easiest example would be the system tags on Tags page - https://github.com/xibosignage/xibo/issues/3006
=> 3.3.4 - hide empty row menu and fix group admin userGroup permissions

.eslintrc.js, lib/Connector/XiboDashboardConnector.php, lib/Controller/Widget.php, lib/Event/WidgetEditOptionRequestEvent.php, ui/src/core/forms.js
I've made a change here so that the front end passes in a propertyId with the request and as the initialKey. The back end then passes that directly into the event so that it can be handled entirely by the connector (or whatever handles the event).
=> Modules: refactor WidgetEditOptionRequestEvent to make it generic 

lib/Controller/Schedule.php, lib/Entity/Schedule.php, ui/src/core/xibo-calendar.js, views/base.twig, views/schedule-form-add.twig, views/schedule-form-edit.twig, views/schedule-form-now.twig, views/schedule-grid-page.twig
- Various wording adjustments on schedule forms and grid
- Default some filters on Schedule grid to All/Both instead of an empty string
- Add Max plays per hour to the Schedule grid
- Fix `Invalid Date` in Recurrence End for Recurring event without end date
- Show only Image and Video in the Media selector on schedule grids for Full Screen schedule
- Fix PHP warning on schedule forms with no DisplayGroup selected
- Use SystemMessageInline instead of SystemMessage for errors during layout create/fetch for full screen schedule
=> Schedule full screen : wording adjustments and minor fixes

lib/Widget/Render/WidgetHtmlRenderer.php, lib/Xmds/Soap.php, modules/src/player.js
This tries to handle 3 cases:
- v4 player: widget where data is expected and can be requested via a separate URL
- v4 player: widget where we do not expect data
- v3 player: widget where data is expected and injected into the HTML (player does not support separate data)
@rubenpingol-xibo I made a workaround to player.js in this PR - please can you see if it will meet all of the above 3 requirements?
---------
@PeterMis I think this also finally fixes having duplicate assets in the RF table/xml 😅
=> Widget data: handle 3 difference cases for when there is data/not.

lib/Entity/Display.php, lib/Widget/Definition/Asset.php, lib/Xmds/Soap.php
Get legacyId works for assets as long as new modules/templates aren't added to the system - at that point the assetId changes and duplicates are added into the requiredfiles table. Duplicates are not added to rf.xml though, so the player still updates and marks itself as complete.
To improve this in v4 we can add the assetId to RF using the realId instead of the legacyId (legacyId isn't really used at that point). This means the asset only gets into the table once, even if its calculated legacyId changes.
I think this works!
----
I also fixed an issue with deleting displays that have display_media links, and tidied up the delete method.
=> Player test fixes

lib/Controller/Schedule.php, lib/Controller/SyncGroup.php, lib/Entity/Schedule.php, lib/Entity/SyncGroup.php, tests/Xmds/SyncTest.php, ui/src/core/xibo-calendar.js, views/schedule-form-sync-edit.twig, views/schedule-grid-page.twig, views/schedule-page.twig
Relates to https://github.com/xibosignageltd/xibo-private/issues/268
- Various wording adjustments
- Fixed switching syncGroup on sync event edit form
- Fixed syncGroup members table on sync event edit form when member was added to the group AFTER the event was created (previously there would be no row for such Display in this case)
- XMDS test for sync group register/schedule output
=> Content sync : fixes and xmds test

ui/src/editor-core/element.js, ui/src/editor-core/properties-panel.js, ui/src/templates/forms/inputs/number.hbs
relates to xibosignageltd/xibo-private#251
- Slot input will force a positive input
- Viewer data render will start from 0 if slot is higher than data results length
=> Elements with data: Prevent negative and empty results

modules/templates/global-elements.xml, ui/src/playlist-editor/playlist-timeline.js, ui/src/style/playlist-editor.scss, ui/src/templates/playlist-timeline.hbs
relates to xibosignageltd/xibo-private#2905
- Hide image and date from global elements
=> Playlists: media add to queue doesn't always put it in the right place

modules/src/xibo-webpage-render.js, modules/webpage.xml
In v3, although the form has `modeId`, the `setOption` is actually `modeId`, which means that all players have been looking for `modeid`.
fixes https://github.com/xibosignageltd/xibo-private/issues/382
=> Widget: webpage modeid should be non camel case

lib/Controller/Library.php, lib/Controller/Widget.php, lib/Entity/DataSet.php, lib/Entity/DataSetColumn.php, lib/Entity/Module.php, lib/Entity/Widget.php, lib/Event/MenuBoardModifiedDtRequest.php, lib/Factory/LayoutFactory.php, lib/Factory/ModuleFactory.php, lib/Listener/MenuBoardProviderListener.php, lib/Middleware/CustomMiddlewareTrait.php, lib/Middleware/ListenersMiddleware.php, lib/Middleware/SAMLAuthentication.php, lib/Widget/AudioProvider.php, lib/Widget/Compatibility/DatasetWidgetCompatibility.php, lib/Widget/DataSetProvider.php, lib/Widget/MastodonProvider.php, lib/Widget/MenuBoardProductProvider.php, lib/Widget/NotificationProvider.php, lib/Widget/Provider/DurationProvider.php, lib/Widget/Provider/DurationProviderInterface.php, lib/Widget/Provider/DurationProviderNumItemsTrait.php, lib/Widget/RssProvider.php, lib/Widget/VideoProvider.php, modules/menuboard-product.xml, modules/templates/dataset-static.xml, ui/src/layout-editor/main.js
- OKTA SAML from v3
- Improvements to Custom Middleware creation
- Widget duration fixes
=> Various issues

modules/canvas.xml, ui/src/editor-core/widget.js
relates to xibosignageltd/xibo-private#365
=> Fix for deleting all elements in a widget

lib/Controller/Command.php, lib/Controller/Display.php, lib/Controller/DisplayGroup.php, lib/Entity/Schedule.php, lib/Factory/CommandFactory.php, lib/Factory/DisplayFactory.php, lib/Service/PlayerActionService.php, views/authed.twig, views/display-page.twig
- Schedule name length validation
- Displays : filter by XMR registered status resolves https://github.com/xibosignage/xibo/issues/3079
- Commands : execute with selected Displays / Display Groups, resolves https://github.com/xibosignage/xibo/issues/2927
- Display Groups : Show Display name when XMR action fails, resolves https://github.com/xibosignage/xibo/issues/3080
- phpcs / formatting adjustments
=> Minor misc fixes

cypress/e2e/folder.cy.js, cypress/e2e/layout_dataset.cy.js, lib/Widget/MastodonProvider.php, modules/mastodon.xml
- Related to https://github.com/xibosignageltd/xibo-private/issues/351
=> Mastodon username search

views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#444
=> Layout: renaming from inside the editor doesn't refresh the name

lib/Controller/Action.php, lib/routes-web.php, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/layout-editor/main.js, ui/src/style/common.scss, views/common.twig
* Toolbar Icons: regression in [403](https://github.com/xibosignageltd/xibo-private/issues/403)
* Actions: tidy unused code
* Actions: fixes for field dependencies/visibility
=> Misc Fixes 12

lib/Connector/ConnectorTrait.php, lib/Connector/XiboDashboardConnector.php, lib/Controller/Widget.php, lib/Factory/ModuleFactory.php, lib/Widget/DashboardProvider.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Render/WidgetDataProviderCache.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php
fixes xibosignage/xibo#3128
- Wsdl:getRoot doesn't work in XTR
- Display specific cache keys must have %displayId% in them
- Get Resource must return data nodes for widget provider modules
- Preview mode on DataProvider doesn't work for any key that is not display specific
=> Dashboards: no data being returned/requested by the player

lib/Connector/XiboDashboardConnector.php, lib/Entity/Layout.php, lib/Widget/Compatibility/RssWidgetCompatibility.php, lib/Widget/RssProvider.php, modules/countdown-clock.xml, modules/countdown-custom.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/rss-ticker.xml, modules/templates/article-static.xml, views/welcome-page.twig, web/xmds.php
- Countdown widget warning on layout status (can't use duration in status rule)
- Dashboards should have a shorter token TTL
- RSS ticker should support custom image enclosures
- RSS ticker upgrade from v3 fixed
- Welcome page uses product_support_url for non Xibo themed, which isn't set.
=> Widget Fixes

ui/src/core/xibo-cms.js
relates to xibosignageltd/xibo-private#479
=> Date Picker: Set default time to 12am and not 12pm

docker/entrypoint.sh, lib/Controller/Module.php, lib/Controller/Widget.php, lib/Entity/Module.php, lib/Service/DisplayNotifyService.php, lib/Service/DisplayNotifyServiceInterface.php, lib/Widget/Render/WidgetDataProviderCache.php, lib/Widget/Render/WidgetHtmlRenderer.php, lib/XMR/DataUpdateAction.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php, modules/dashboard.xml, views/dataset-form-edit.twig, views/dataset-page.twig
DataSet takes too long to update on the player after editing
- add data last modified and active info to data set page for debugging
- XMDS required files needs to push the `updated` attribute on resource for older players
- DataSet notify should run the widget sync task immediately
- Widget Sync task should notify now for older displays and should have some way to notify newer players that data has changed 
- fixes xibosignage/xibo#3145
PDF widget is broken because it expects data, fixes xibosignage/xibo#3147
=> Widget issues with data cache

lib/Widget/Render/WidgetHtmlRenderer.php, modules/widget-html-render.twig
v3 initialised xiboIC with the targetId, this is missing in v4
related to: xibosignage/xibo#3147 and xibosignageltd/xibo-private#264
=> Widget: xiboIC not initialised with a widgetId

lib/Xmds/Soap.php
relates to xibosignage/xibo#3145
We're only recording a data file for the global widget in the canvas, which means data is never delivered for elements on widgets with data.
=> XMDS: ensure required files outputs the data node for elements

lib/Entity/ModulePropertyTrait.php, lib/Xmds/Soap.php
If the module default is used we don't set the widget option and always end up with 2 hours as our update interval.
relates to xibosignage/xibo#3145
=> XMDS: use update interval default value 

lib/Xmds/Soap.php
relates to xibosignage/xibo#3145
=> XMDS: get resource for older players using wrong module cache and data provider

lib/Controller/Layout.php, lib/Widget/IcsProvider.php, lib/Widget/RssProvider.php, ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/templates/viewer-element-content.hbs, views/common.twig, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#499
=> Show error message on Elements with bad configured widget

lib/Controller/Layout.php, lib/Controller/Schedule.php, lib/Entity/SyncGroup.php, lib/Factory/ResolutionFactory.php, lib/Helper/Install.php, modules/templates/forecast-elements.xml, ui/src/core/file-upload.js, views/include-file-upload.twig
- Schedule : Sync event, check and throw relevant error if not all Displays were assigned a Layout. Relates to https://github.com/xibosignage/xibo/issues/3150
- Maintenance : Remove no longer needed asset (weather-humidity-percent) from weather template. Relates to https://github.com/xibosignage/xibo/issues/3155
- Custom Install : Try to create fonts sub-folder under selected Library Directory on install. Relates to https://github.com/xibosignage/xibo/issues/3156
- Layout : Filter Resolutions available in Layout editor Resolution dropdown by enabled flag, but always include currently selected resolution regardless of enabled flag. Relates to https://github.com/xibosignage/xibo/issues/3173
- Library Upload : Protect against empty Default Resize Limit causing various errors on upload form. …
=> Bugifxes 4.0.4 issues part2

lib/Controller/Applications.php, lib/Controller/Module.php, lib/Factory/ApplicationFactory.php, lib/Factory/DataSetFactory.php, lib/Factory/ModuleFactory.php, views/applications-page.twig, views/daypart-page.twig, views/module-page.twig
This can go in 4.0.5 if needed.
Search Filters for
- Daypart
- Applications
- Modules
Bonus
- Remote DataSet : Fixed deprecated filter for string, use `strip_tags` instead.
=> Add missing search filters

lib/Storage/PdoStorageService.php, lib/XTR/StatsMigrationTask.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/517
=> 3.3.9 - Statistic migration 

lib/Factory/RequiredFileFactory.php, lib/Xmds/Soap.php
=> Store the assetType for older players, so we can rewrite the URL correctly

lib/Entity/Playlist.php, lib/Entity/Widget.php, lib/XTR/DynamicPlaylistSyncTask.php
- Widget : on delete of a drawer Widget, make sure we do not delete the whole action, just remove the widgetId from the record.
- Playlists : Fix various displayOrder issues after replacing, removing and the re-adding files that match Dynamic Playlist filters
=> Dynamic Playlist and Widget delete fixes

lib/Controller/DisplayProfile.php, lib/Controller/Library.php, lib/Factory/DisplayProfileFactory.php, ui/src/core/xibo-cms.js, views/applications-form-edit.twig, views/authed.twig, views/campaign-page.twig, views/dataset-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/folders-page.twig, views/layout-page.twig, views/library-page.twig, views/menuboard-page.twig, views/playlist-page.twig, views/syncgroup-page.twig, views/template-page.twig, web/theme/default/css/xibo.css
- Folders tree : style adjustments
- Display Profile : Fix NotFound exception being thrown on no results from the query in grid
- Library : show nothing instead of big red X if no thumbnail available for video
- Applications : Fix scope checkboxes state on edit form
=> 4.0.5 issues part2

cypress/e2e/Display/datasets.cy.js, cypress/e2e/Display/dayparts.cy.js, cypress/e2e/Display/displaygroups.cy.js, cypress/e2e/Display/syncgroups.cy.js, cypress/e2e/Layout/displaysettings.cy.js, cypress/e2e/Layout/tags.cy.js, cypress/e2e/Layout/transitions.cy.js, cypress/e2e/Layout/usergroups.cy.js, cypress/e2e/Layout/users.cy.js, cypress/e2e/campaigns.cy.js, cypress/e2e/displays.cy.js, cypress/e2e/layout_designer_empty.cy.js, cypress/support/commands.js, lib/XTR/SeedDatabaseTask.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/532
=> Cypress - add/edit part2

modules/src/player.js, modules/templates/forecast-elements.xml, ui/src/helpers/player-helper.js
relates to xibosignage/xibo#3195
=> Text flashes on-screen once and then disappears when a weather widget is also present

modules/templates/dataset-static.xml
relates to xibosignage/xibo#3178
=> Widget: DataSet Image Slideshow doesn't show DataSet Field when the dataset has no image columns

lib/Controller/Schedule.php, lib/Factory/ScheduleFactory.php, views/campaign-page.twig, views/dataset-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/layout-page.twig, views/library-page.twig, views/menuboard-page.twig, views/playlist-page.twig, views/schedule-page.twig, views/syncgroup-page.twig, views/template-page.twig, web/theme/default/css/xibo.css
- Folders : few css adjustments to the folder tree next to grids on relevant pages
- Schedule : Added two new filters directSchedule and sharedSchedule
-- Direct Schedule when enabled is pretty much they way it works now, when disabled we should also see for example: any events scheduled to the displayGroup selected Display is a member of
-- Shared Schedule should show only events that are scheduled to all selected Displays/Groups ie it requires for example at least two Displays to be selected to show any events that are scheduled to both of them.
=> Schedule grid filter improvements and Folder css adjustments

docker/entrypoint.sh, lib/Entity/Layout.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Property.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/hls.xml, views/displayprofile-form-edit-android.twig
- Database auto backup not running
- New option for default video engine on Android display settings profile
- HLS widget should output the URI in the XLF (for those players which render that natively instead of via HTML)
- Add variable parsing to the module/template style property
=> Misc 4.0.5 issues

ui/src/layout-editor/viewer.js
relates to xibosignage/xibo#3221
=> Layout editor viewer: Element Groups with layer 0 show out of order

modules/src/xibo-substitutes-parser.js
relates to xibosignage/xibo#3192
=> Substitutes parser doesn't handle custom date format for variables

lib/Entity/Application.php, lib/Entity/ApplicationRedirectUri.php, lib/Entity/ApplicationScope.php
The root cause for the "Authorisation parameters missing from session" is that the session isn't being updated in the database for the `GET /api/authorize` request. It seems to be either silently failing, or not updating at all (no log showing the SQL is recorded, but it is for other requests).
I think this might be due to us serialising the private member variables on the application/redirect/scope objects. This PR limits the data we serialise.
This is only a theory.
=> Auth: serialise logic for oAuth objects in session xibosignage/xibo#3184

lib/Helper/Translate.php, lib/Widget/Render/WidgetHtmlRenderer.php
relates to xibosignage/xibo#3130
=> Weather widget: changing the language doesn't affect the whole template

modules/templates/article-static.xml
relates to xibosignage/xibo#3135
=> RSS Ticker: not possible to easily add a separator between marquee items

lib/Widget/DataSetProvider.php, lib/Widget/MenuBoardProductProvider.php, modules/menuboard-product.xml
DataSet: fix table durations per page (rowsPerPage)
MenuBoard: fix duration is per item (reverts prior fix).
relates to xibosignageltd/xibo-private#555
=> Misc fixes for duration is per item

modules/templates/global-elements.xml, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, views/layout-designer-page.twig
relates to xibosignage/xibo#3224
=> Widgets: Show empty element and tooltip icon when no data

ui/src/editor-core/widget.js, ui/src/layout-editor/main.js, ui/src/layout-editor/region.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/templates/context-menu.hbs, ui/src/templates/viewer-element-group.hbs, ui/src/templates/viewer-element.hbs, views/common.twig, views/user-form-permissions.twig
relates to xibosignage/xibo#3289
=> Layout Editor: Sharing is broken

lib/Controller/Layout.php, lib/Controller/Library.php, lib/Controller/User.php, lib/Controller/Widget.php, lib/Widget/Provider/DataProvider.php, ui/src/layout-editor/viewer.js
This PR makes a change to the way we serve images/video thumbnails from the /library/download endpoint, so that if we say we're in preview mode (`preview=1`) we return a 1px placeholder when access is denied.
It also makes a change to the way module files have their permissions checked so that when data is returned users are granted permissions to any linked modules files. That means these files can be checked in the same way as any other file.
It also links together the sharing options applied to a Region and its Region Playlist, which means if we add a playlist (which adds a playlist region), we can set sharing on it.
=> Misc fixes related to sharing in 4.0

lib/Controller/Schedule.php, views/schedule-page.twig
- Fix js error (and PHP deprecated use of explode) when recurring event is set with recurrenceRepeatsOn null.
Relates to https://github.com/xibosignage/xibo/issues/3301
- Fix two issues with switching from Campaign to Interrupt event type - campaign should not be allowed, parentCampaignId should be cleared.
Relates to https://github.com/xibosignage/xibo/issues/3298
=> Schedule grid fixes

lib/Controller/DisplayProfileConfigFields.php, lib/Factory/DisplayProfileFactory.php, views/displayprofile-form-edit-android.twig
This PR adds a new setting to the Android display settings profile, defaulted to off to match the android app.
=> Android settings: add setting to toggle restart wifi on failure

lib/Entity/Layout.php, lib/Factory/ModuleXmlTrait.php, modules/video.xml, modules/videoin.xml
This PR fixes https://github.com/xibosignage/xibo/issues/3284.
It also tidies up the contents of the XLF where messages were being output for native widgets.
=> Fix for Video In duration getting set to 1 and XLF output tidying

lib/XTR/WidgetCompatibilityTask.php
This PR makes sure that when we upgrade a widget we only assert the module type if the widget compatibility class has not already changed it.
fixes xibosignage/xibo#3275
=> Widget: clock widget upgrade issue (type changing back to analogue)

lib/Entity/ModulePropertyTrait.php, lib/Widget/CurrenciesAndStocksProvider.php, lib/Widget/Provider/DataProviderInterface.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/currencies.xml, modules/stocks.xml
This PR fixes an issue with currencies and stocks not calculating their duration correctly as they did not know how many items were available.
It also adds a change which will ignore the `[0]` library reference in JavaScript, which seems to be the most common array accessor.
=> Currencies and Stocks duration issue

lib/Connector/XiboExchangeConnector.php
This PR makes a simple quick fix to the Xibo Exchange endpoint so that we can support v4 only layouts.
=> Connectors: Xibo Exchange simple switch to v4 layouts.json

modules/src/xibo-player.js
* Dashboard Widget doesn't work (the HBS is not getting added to the DOM)
=> PlayerJS: Fix for dashboard module so template can be added to the DOM

lib/Entity/Module.php, lib/Entity/ModuleTemplate.php, lib/Factory/ModuleFactory.php, lib/Factory/ModuleTemplateFactory.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/calendar.xml, modules/src/xibo-player.js, modules/widget-html-render.twig
PlayerJS: make sure we pass dataItems into both data load methods and hook those up on the back end. 
PlayerJS: Fix v3 players isDataReady.
PlayerJS: call expire now on static widgets where data is not ready
Modules: remove old onDataError.
relates to xibosignageltd/xibo-private#611
=> Resolve handling for onTemplateDataLoad and ensure data items are passed correctly

modules/src/xibo-player.js, ui/src/layout-editor/main.js
PlayerJS: delay the expiry by 1500ms to prevent race conditions 
relates to xibosignageltd/xibo-private#611
PlayerJS: xiboImageRender not called for elements
relates to xibosignageltd/xibo-private#614
Layout Editor: fixes some undefined variables which were preventing elements being grouped.
=> PlayerJS: expiry/image render fixes. LayoutEditor: undefined variables

lib/Controller/Widget.php
related to xibosignageltd/xibo-private#617
I elected to throw an error instead of deleting the widget as we shouldn't make a DELETE inside a POST API call. Hopefully the error will give us an example for where this happens in the FE which we can diagnose.
=> Elements: add an API check to ensure we aren't trying to save a widget with no elements

db/migrations/20240227102400_missing_indexes_migration.php
fixes xibosignageltd/xibo-private#575
It should not be possible to have orphaned regions, but just in case we take care of those here.
=> DB: fix missing indexes

lib/Widget/IcsProvider.php
=> Widget: calendar widget event filtering only ever return events 5 days in the past.

.github/workflows/test-suite.yaml
- Related to https://github.com/xibosignageltd/xibo-private/issues/641
=> Testmo command with cypress

ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js
relates to xibosignage/xibo#3352
=> Property Panel doesn't move target when changing between Elements

lib/Controller/User.php, lib/Entity/Layout.php, lib/Entity/Region.php, lib/Entity/User.php, lib/Event/LayoutSharingChangeEvent.php, lib/Factory/CampaignFactory.php, lib/Factory/PermissionFactory.php, lib/Listener/LayoutListener.php, lib/Middleware/ListenersMiddleware.php
Updating layout sharing should update any Canvas regions with the same. Adding a new canvas region should adopt the layout sharing that already exists. A double-lock.
In addition, trying to set canvas permissions separately will throw an error (@maurofmferrao I think you will remove that option once this is merged?)
=> Layout: sync together canvas and layout sharing.

ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/playlist-editor/main.js, ui/src/style/layout-editor.scss, ui/src/style/playlist-editor.scss, ui/src/templates/topbar-playlist-switch.hbs, ui/src/templates/viewer-playlist-controls.hbs, views/common.twig, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#639
=> Edit single sub-playlist from Layout Editor

lib/Factory/BaseFactory.php, lib/Service/LogService.php, lib/Service/LogServiceInterface.php, lib/Storage/PdoStorageService.php
Relates to https://github.com/xibosignageltd/xibo-private/issues/570
=> Log Service : When sql syntax error occurs, log sql in error level.

ui/src/helpers/form-helpers.js
relates to xibosignage/xibo#3377
=> Inline Playlist Editor: Rich text same colour as layout's

ui/src/layout-editor/main.js, ui/src/playlist-editor/main.js, views/common.twig
relates to xibosignageltd/xibo-private#661
=> Bring back Delete confirmation modals

lib/Connector/AlphaVantageConnector.php, lib/Widget/CurrenciesAndStocksProvider.php
Widget uses maxItemsPerPage instead of itemsPerPage. Also improve error responses from AlphaVantageConnector.
fixes xibosignage/xibo#3368
=> Widget: Stocks and Currencies invalid duration when items per page is used

lib/Widget/DataSetProvider.php, modules/dataset.xml, modules/src/xibo-dataset-render.js
This PR addresses two issues:
- The freshness timeout property in DataSet does not work for Elements
- The validation for ensuring we have a number of items makes more sense on numItems vs upperLimit
=> Widget: DataSet issues with duration is per item and freshness timeout

ui/src/editor-core/toolbar.js, ui/src/style/toolbar.scss, ui/src/templates/toolbar-content.hbs, ui/src/templates/toolbar-search-form.hbs, views/common.twig
relates to xibosignageltd/xibo-private#666
=> Editor Toolbar: Exchange tab

lib/Controller/Layout.php, lib/Factory/ResolutionFactory.php
=> Layout: cannot add a layout if you remove the 1920x1080 resolution

modules/src/editor-render.js, modules/src/xibo-player.js, modules/src/xibo-text-render.js
relates to xibosignage/xibo#3388
=> Widget: Fix marquee effect implementation from xiboTextRender

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Property.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/forecastio.xml, modules/src/xibo-player.js
Controls whether a module sends it properties into a widget. 
Handle it on HTML render. 
Remove workaround for playerJS
fixes xibosignage/xibo#3394
=> Elements: add a new property to control

ui/src/editor-core/properties-panel.js, views/common.twig
relates to xibosignageltd/xibo-private#670
=> Confusing Widget naming for elements

lib/Entity/Layout.php
Ensure we output the transInDirection and transOutDirection fields. Default to `E` to mimic player functionality.
fixes xibosignage/xibo#3419
=> Transitions: output trans(In/Out)Direction.

ui/src/core/xibo-cms.js, views/campaign-page.twig, views/dataset-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/layout-page.twig, views/library-page.twig, views/menuboard-page.twig, views/playlist-page.twig, views/syncgroup-page.twig, views/template-page.twig, web/theme/default/css/xibo.css
relates to xibosignage/xibo#3374
- Folder control container can now be resized horizontaly
- Folder names now have a limited size based on the container width
- Folder container visual changed to be more consistent with the table
=> Folders: Refactor

lib/Factory/ModuleFactory.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php
Fix an issue where the data provider `useDisplayLocation` variable in the cache key is not substituted correctly https://github.com/xibosignage/xibo/issues/3422
Also a potential solution for "cache not ready" on display specific caches, caused by not supplying the data provider with lat/long/displayId in all cases.
=> Module: cache issues with weather and others

lib/Controller/Display.php, lib/Controller/Preview.php, lib/Controller/Task.php, lib/Controller/Widget.php
relates to xibosignage/xibo#3427
- Removed the setting of the content-type header to application/json in some of the modified methods where it was previously set to json.
=> Library upload API returns plain/text instead of application/json (fixed)

lib/Connector/OpenWeatherMapConnector.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Provider/DataProviderInterface.php
xibosignage/xibo#3428
The prior fix of this issue cause this error:
```
Xibo\Widget\Provider\DataProvider::getDisplayLatitude(): Return value must be of type float, null returned
```
This is because some displays will have `null` in their lat/lng. It is possible we would have seen this error before, but we were not reliably using the lat/lng in all cases.
=> Module: data provider lat/lng might return null if it has not ever need set on a display

lib/Connector/OpenWeatherMapConnector.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php
The root cause of our issue is that we did not provide the CMS lat/lon when the display one was null/empty.
xibosignage/xibo#3428
=> Module: data provider: make sure there is always a lat/lon

modules/webpage.xml
These parameters represent region width/height and should be used rather than determining it client side.
fixes xibosignage/xibo#3424
=> Module: webpage widget should use original width/height

lib/Middleware/State.php
In this PR we add the url_decode filter to the XMDS entrypoint so that if we need to generate widget HTML (which uses a twig file) we have that filter available.
xibosignage/xibo#3433
=> Module: HTML cache can be generated via XMDS which fails for HLS.

ui/src/core/xibo-cms.js
relates to xibosignage/xibo#3442
- Flatpickr mobile version disabled to allow the CMS custom code to still work
=> Schedule page shows no events when mobile layout is used

lib/Report/Bandwidth.php
- Fixes error in displaying the table/chart in Bandwidth Report
- RCA: When the data returned is empty, infinite value is calculated in the $base, hence, causes the type error
Relates to: https://github.com/xibosignage/xibo/issues/3438
=> Bandwidth Report: Fixed Table/Chart is not showing any data

lib/Controller/StatusDashboard.php, lib/Factory/UserFactory.php
This PR adjusts two parts of the status dashboard logic.
1. we queried and looped over display groups for no apparent reason (likely this is legacy code left by mistake) - removed
2. we uses a count() method on an array of users, which has been switched to a direct query approach instead
fixes xibosignage/xibo#3440
=> Dashboard: remove unused code to improve page load performance.

lib/Controller/Widget.php, lib/Widget/DataSetProvider.php, ui/src/editor-core/widget.js, ui/src/layout-editor/main.js
This PR fixes two problems:
- the duration was not being calculated when the number of unique slots (pages) was changed
- the UI was not refreshing layout status after saving elements
=> Data Widget: increasing/decreasing the number of slots does not update the duration when durationPerItem is checked

lib/Controller/Schedule.php, views/schedule-page.twig
The from/to date are being shown with respect to CMS timezone, instead of timezone agnostic. In addition the recurrence detail uses the timezone specific date during formatting.
xibosignage/xibo#3429
=> Schedule: fix monthly repeat and from/to dates for time zone.

modules/src/xibo-text-render.js
The marquee sets the contents of scroller to float:left, which on android causes the containing div height to go from 100% to 0 (as the things inside it are all floated). Fixing a pixel height to the content div makes the container for the scroller have a height.
fixes xibosignage/xibo#3388
=> Widget: Marquee up/down scrolling on android

ui/src/style/toolbar.scss
relates to xibosignageltd/xibo-private#794
=> Editor: Viewer dimensions wrong when refreshing page with toolbar toggled off

lib/Controller/Preview.php, lib/routes-web.php, views/schedule-form-add.twig, views/schedule-form-edit.twig
relates to xibosignageltd/xibo-private#539
- Did not need to provide a dedicated preview button for `layout` Event Type, as the current preview button already accommodates both campaign and layout previews.
=> Schedule Edit: Preview button on Edit Event form requires Campaign features to be enabled

lib/Factory/ScheduleFactory.php
This PR updates the query for returning the schedule to XMDS so that layouts which have an associated draft are not returned twice in the schedule.
fixes to xibosignage/xibo#3437
=> XMDS: use a sub-query to filter out draft layouts before outer join

lib/Entity/Permission.php, lib/Factory/PermissionFactory.php
This PR tries to reduce the number of unnecessary SQL updates which would run when saving permissions if there are no changes to the existing records.
Inserting new records is unaffected. Inserting existing records only happens if a property has changed.
relates to xibosignageltd/xibo-private#797
=> Permissions: only update permission record in the DB if necessary 

lib/Controller/Layout.php, lib/Factory/LayoutFactory.php
This is because they are applied templates and the parent tags win.
xibosignageltd/xibo-private#811
This PR makes sure that the "imported" tag is not applied when applying a template from a provider (in this case the Xibo Exchange).
=> Exchange: layouts added from exchange should not have the imported tag

modules/templates/global-elements.xml, views/common.twig, views/layout-form-background.twig
relates to xibosignageltd/xibo-private#822
=> Image Element: replace drop area text update

lib/Dependencies/Factories.php, lib/Entity/ApplicationRequest.php, lib/Factory/ApplicationRequestsFactory.php, lib/Middleware/ApiAuthorization.php, lib/Report/ApiRequests.php, reports/apirequests-email-template.twig, reports/apirequests-report-form.twig, reports/apirequests-report-preview.twig, reports/apirequests-schedule-form-add.twig
relates to xibosignage/xibo#3362
- Requests : New API requests report type that does not join on log/audit tables
- Various adjustments to the report, forms etc to suit the new report type
- Change the url added to database to correctly include route parameters ( previously things like `{id}` would be saved)
- Separate sql connection and commit to ensure we get the error requests in the table
- Added small new Factory and Entity for API requests
=> Reports : API Requests new report type, various adjustments.

lib/Report/Bandwidth.php
- Fixed data calculation error for duplicate display names
Relates to: https://github.com/xibosignage/xibo/issues/3462
=> Bandwidth Report: Fixed data calculation error for duplicate display names

lib/Report/Bandwidth.php
- Fixed data calculation error for duplicate display names
Relates to: https://github.com/xibosignage/xibo/issues/3462
=> Bandwidth Report: Fixed data calculation error for displays with same name

views/dataset-dataentry-page.twig
- Fixed HTML sanitation in datasets table
Relates to: https://github.com/xibosignageltd/xibo-private/issues/801
=> Datasets: Fixed HTML sanitation in datasets table

lib/Controller/DisplayGroup.php, lib/XMR/ScheduleCriteriaUpdateAction.php, lib/routes.php
relates to xibosignageltd/xibo-private#807
=> Schedule Criteria: CMS API + XMR update to displays

lib/Controller/Library.php, lib/Controller/Widget.php
- Disable manual changes to media assignments on dynamic playlists
Relates to: https://github.com/xibosignage/xibo/issues/3480
=> Playlists: Fix for disable manual changes to media assignments on dynamic playlists

ui/src/core/xibo-forms.js
relates to xibosignage/xibo#3483
=> Display Assign Files: Prevent reassigning same items

lib/Entity/DisplayEvent.php, lib/Xmds/Soap.php
- Display: Update detail of an alert when submitting the end
Relates to: https://github.com/xibosignage/xibo/issues/3478
=> Display: Fix for updating detail of an alert when submitting the end

views/authed.twig
FE:
- Help Button: Hide in mobile view
Relates to: https://github.com/xibosignage/xibo/issues/3489
=> Help button: Fix for Help button gets in the way of paging and mobile forms

lib/Connector/PixabayConnector.php
BE:
- Get 1080p videos by default instead of 4k
Relates to: https://github.com/xibosignageltd/xibo-private/issues/840
=> Pixabay: Get 1080p videos by default instead of 4k

lib/Controller/Display.php
relates to xibosignage/xibo#3481
=> Display: assigning a display to a group from the Display page doesn't clear the cache

ui/src/editor-core/toolbar.js
relates to xibosignage/xibo#3492
=> Editor Toolbox: Size popup buttons disappear on drag

modules/clock-flip.xml, ui/src/core/forms.js
relates to xibosignage/xibo#3506
=> Flip Clock Widget: Shadow appears behind Clock Widget when using RGBA color

ui/src/core/file-upload.js
- Added `limitConcurrentUploads` option in file-upload.js
Relates to: https://github.com/xibosignage/xibo/issues/3503
=> Library: Fix for uploader should limit concurrent uploads

ui/src/core/xibo-cms.js, ui/src/templates/forms/inputs/connectorProperties.hbs
- Connectors: Fix for issue on using `pagedSelect` dropdown 
- Used `localSelect` instead to display all options at once 
Relates to: https://github.com/xibosignage/xibo/issues/3505
=> Connectors: Fix duplicate data on dropdown option

lib/Connector/OpenWeatherMapConnector.php, lib/Xmds/Soap.php
relates to xibosignage/xibo#3487
- Modified metric IDs to better align with JSON responses from the OWM API.
- Added a prefix to avoid conflicts with other potential weather schedule criteria.
- Removed metrics that are not present in OpenWeather API responses.
=> Schedule Criteria: weather "clear sky" condition does not match

lib/Report/ProofOfPlay.php, reports/proofofplay-report-form.twig
FE:
- Fixed column duration column calculation
BE:
- [MongoDB] Added data calculation for accumulating the values according to grouping option
Relates to: https://github.com/xibosignage/xibo/issues/3356
=> Reports: Add Proof of Play MongoDB grouping

lib/Xmds/Soap.php
relates to xibosignageltd/xibo-private#858
=> XMDS: join action layouts after processing.

lib/Entity/Display.php
- Fix not possible to get audit logging from the player (updated `debug` to `audit`)
Relates to: https://github.com/xibosignage/xibo/issues/3493
=> Player logging: Fix not possible to get audit logging from the player

ui/src/core/xibo-cms.js, views/forms.twig
relates to xibosignage/xibo#3517
- When closing the second modal without saving, the previous modal will also be closed
=> Image Scheduling: Error when closing Select Media form while creating an image schedule

lib/Controller/Display.php, lib/Controller/DisplayGroup.php
- Add `Send Command` in non-destructive feature
Relates to: https://github.com/xibosignage/xibo/issues/3533
=> Display: Non-destructive feature should include send command

ui/src/editor-core/element-group.js, ui/src/editor-core/element.js, ui/src/layout-editor/main.js, ui/src/style/layout-editor.scss
relates to xibosignage/xibo#3516
- Prevent elements and groups to be deleted if parent widget isn't editable
- Failed to create widget when adding widget due to permissions lock adding fix
- Hide element group edit button if it's not editable
=> Elements need to obey sharing permissions

db/migrations/20240909114945_add_folder_filter_to_playlist_table_migration.php, lib/Controller/Playlist.php, lib/Entity/Playlist.php, lib/Factory/PlaylistFactory.php, lib/XTR/DynamicPlaylistSyncTask.php, views/playlist-form-add.twig, views/playlist-form-edit.twig, views/playlist-page.twig
relates to xibosignageltd/xibo-private#841
=> Playlists: dynamic playlists should filter media by folderId

lib/Controller/Widget.php, lib/Entity/Layout.php
- Fix Canvas only layouts should set their duration from any images added or a 10 second minimum
Relates to: https://github.com/xibosignage/xibo/issues/3499
=> Layouts: Fix Canvas only layouts should set their duration from any images added or a 10 second minimum

modules/templates/global-elements.xml
relates to xibosignage/xibo#3520
=> Elements: Text cutoff with gradient

lib/Entity/Layout.php
relates to xibosignage/xibo#3535
=> Layout import : Fix Playlist closure table.

modules/templates/product-elements.xml
- Menu Board Elements: Fix for options doesn't have Font Family property
Relates to: https://github.com/xibosignage/xibo/issues/3528
=> Menu Board Elements: Fix for options doesn't have Font Family property

views/schedule-form-edit.twig
- Schedule Edit: Fix missing relative time checkbox on custom schedule
Relates to: https://github.com/xibosignage/xibo/issues/3537
=> Schedule Edit: Fix missing relative time checkbox on custom schedule

lib/Xmds/Soap.php, lib/Xmds/Soap4.php, lib/Xmds/Soap5.php
This PR applies a small offset (+/- 10 seconds) to the collection interval so that displays which are started at the same time, i.e. at the start of day, or rebooted via command) do not keep connecting concurrently. Instead they spread out after the first connection.
fixes to xibosignage/xibo#3530
=> XMDS: spread collection interval with a small offset

lib/Controller/Library.php
- Folders: Fix Folders appear empty but cannot be deleted due to old file revisions remaining
- Add function to update folder location of media files with revisions
Relates to: https://github.com/xibosignage/xibo/issues/3525
=> Folders: Fix Folders appear empty but cannot be deleted due to old file revisions remaining

modules/calendar.xml, modules/templates/event-static.xml
This PR addresses two issues:
- https://github.com/xibosignage/xibo/issues/3509
- https://github.com/xibosignage/xibo/issues/3515
I don't think it was strictly necessary to remove the `typeof` check,  but the new version does make it easier to understand what is happening, so I kept it in. Triggering using xiboIC with a target of 0 disables the source checking for the trigger.
onDataLoad handles numItems and that has been removed from the one static template that referenced it. The provider always returns all items, so we handle it client side.
=> Calendar widget issues with triggers and number of items

lib/XTR/WidgetSyncTask.php
fixes to xibosignage/xibo#3510
=> Widget: fallback data not added when generated by WidgetSync

ui/src/core/xibo-cms.js, web/theme/compact/css/dashboard.css, web/theme/default/css/dashboard.css
relates to xibosignage/xibo#3526
=> CMS navigation menu: Add active class

ui/src/campaign-builder/main.js, ui/src/core/forms.js, ui/src/core/xibo-cms.js, views/layout-form-edit.twig, views/notification-form-add.twig, views/notification-form-edit.twig, views/notification-page.twig, views/user-page.twig, views/usergroup-page.twig, web/theme/default/css/xibo.css
relates to xibosignageltd/xibo-private#867
=> Improve front-end validation

lib/Factory/MediaFactory.php, lib/Middleware/Handlers.php
=> Errors: sanitize output

lib/Controller/User.php
=> User: force password change shouldn't be accessible unless set.

lib/Report/ApiRequests.php, lib/Report/DisplayAlerts.php, lib/Report/SessionHistory.php, lib/Report/TimeConnected.php, lib/Report/TimeDisconnectedSummary.php, reports/apirequests-report-form.twig, reports/displayalerts-report-form.twig, reports/sessionhistory-report-form.twig, reports/timeconnected-report-form.twig, reports/timedisconnectedsummary-report-form.twig, ui/src/core/xibo-cms.js, views/forms.twig, views/inline.twig
- Range filters should be improved to work mostly client side
- Reports changes
Relates to: https://github.com/xibosignage/xibo/issues/2732
=> Range filters should be improved to work mostly client side

lib/Entity/Schedule.php, ui/src/core/xibo-cms.js, views/forms.twig, views/inline.twig, views/schedule-form-add.twig, views/schedule-form-edit.twig
relates to xibosignage/xibo#3559
=> Schedule form: Limit numeric inputs to min/max

lib/Controller/Login.php
=> Login: add some validation to prior route processing

lib/Factory/MediaFactory.php, lib/Factory/ModuleTemplateFactory.php
fixes xibosignageltd/xibo-private#879
See issue for PR context
=> Library: fix filtering issue with media used as background images on layouts

ui/bundle_xibo.js
relates to xibosignageltd/xibo-private#891
=> Fix for tag filters disappearing after refresh

lib/Service/LogService.php
- Fixed not possible to get audit logging from the player with auditing enabled
Relates to: https://github.com/xibosignage/xibo/issues/3571
=> Fixed Player: still not possible to get audit logging from the player

lib/Connector/CapConnector.php, lib/Connector/EmergencyAlertInterface.php
relates to xibosignageltd/xibo-private#904
=> Simplify Schedule Criteria

lib/Report/ApiRequests.php, lib/Report/DisplayAlerts.php, lib/Report/SessionHistory.php, lib/Report/TimeDisconnectedSummary.php
- Fixed data calculation for today as date range option in specific reports listed below. Previous behavior uses current datetime as the $toDt when 'today' is selected, hence, will retain this behavior instead of calculating the whole day
Reports affected:
- API Requests
- Display Alerts
- Session History
- Time Disconnected
Relates to: https://github.com/xibosignageltd/xibo-private/issues/893
=> Fixed Reporting: time connected summary report does not work with Today as the range

db/migrations/20250121120000_upsert_core_emergency_alert_in_module.php
relates to xibosignageltd/xibo-private#907
=> Enable Emergency Alerts by default

views/library-direct-media-details.twig
relates to xibosignage/xibo#3561
=> Library: improve the "view" direct link

lib/Controller/Library.php
relates to xibosignage/xibo#3572
=> Connector import : restrict media names to up to 95 characters.

lib/Connector/CapConnector.php, lib/Controller/Schedule.php, lib/Event/ScheduleCriteriaRequestEvent.php, lib/Event/ScheduleCriteriaRequestInterface.php, ui/src/core/xibo-calendar.js, views/schedule-form-add.twig, views/schedule-form-edit.twig
relates to xibosignageltd/xibo-private#906
=> Schedule Criteria: Custom conditional

lib/Connector/NationalWeatherServiceConnector.php, lib/Event/ScheduleCriteriaRequestEvent.php, lib/Event/ScheduleCriteriaRequestInterface.php
relates to xibosignageltd/xibo-private#908
=> Schedule Criteria: Merge criteria of the same type

ui/src/core/xibo-calendar.js, ui/src/templates/calendar/sync-event-content-selector.hbs
relates to xibosignageltd/xibo-private#914
- also esLint fixes
=> Synchronised Event layout select fix

ui/bundle_xibo.js, ui/src/pages/schedule/schedule-page.js
relates to xibosignageltd/xibo-private#918
=> Schedule Page: Custom dates don’t show after refresh

ui/src/layout-editor/main.js, ui/src/style/bottombar.scss, ui/src/templates/bottombar-viewer.hbs
relates to xibosignageltd/xibo-private#916
=> Editor Viewer Bar: Limit media name characters

modules/src/xibo-player.js
relates to xibosignageltd/chromeos#62
=> Fix rendering of circle element added to a group

ui/src/layout-editor/viewer.js
relates to xibosignage/xibo#3585
- also prevent double click add
=> Layout Editor Viewer: Enable adding over selected object

lib/Controller/Template.php
=> Template: exclude canva regions when no widgets are included in the template save

lib/Factory/UserGroupFactory.php
=> User: performance improvement assessing enabled features

ui/src/core/forms.js, ui/src/editor-core/properties-panel.js
relates to xibosignage/xibo#3591
- Also fixes the save form fails select other object issue
=> Stock Symbols: input not working for single element

lib/Controller/DisplayProfileConfigFields.php, lib/Factory/DisplayProfileFactory.php, views/displayprofile-form-edit-soc.twig
relates to xibosignage/xibo#3607
=> Display Settings: webOS/Tizen should have multiple video decoder setting

lib/Entity/Layout.php
- Error was caused by missing message value on 'Audit' log, hence, adding a default value solves the issue
Relates to: https://github.com/xibosignage/xibo/issues/3608
=> Delete User: Unexpected error when deleting a user with assigned layouts fix

lib/Controller/Layout.php, lib/Entity/Layout.php
- Fixed Schedule Video/Image: Media with long names cannot be scheduled
Relates to: https://github.com/xibosignage/xibo/issues/3618
=> Fixed Schedule Video/Image: Media with long names cannot be scheduled

lib/Controller/MenuBoardCategory.php, lib/Entity/MenuBoard.php, lib/Widget/MenuBoardCategoryProvider.php
- Fixed Menuboard | Renaming a Category does not update in CMS Layout Editor
Relates to: https://github.com/xibosignage/xibo/issues/3596
=> Menuboard | Renaming a Category does not update in CMS Layout Editor fix

ui/src/core/file-upload.js, ui/src/layout-editor/main.js, views/globalTranslations.twig, views/include-file-upload.twig
relates to xibosignage/xibo#3606
- Limit upload to a single media for the Layout Editor
- Allow removing a media that failed to upload to allow new one
- Reload toolbar after upload to show the new media
=> Layout: Uploading multiple media directly into the editor issue

lib/Listener/DataSetDataProviderListener.php
This PR removes the empty check when parsing out dataset data. It is not clear why the empty check was introduced (in 2023) and there isn't any notes in the commit history or code. My best guess is that it was missing index handling and so I have replaced it with `??`.
fixes xibosignage/xibo#3564
=> DataSet: widgets not showing 0 values due to empty check.

views/welcome-page.twig
- Added blank target to documentation links in Welcome Page
Relates to: https://github.com/xibosignageltd/xibo-private/issues/942
=> Fixed Welcome page opens docs links in the same tab, navigating you away from the CMS

lib/Controller/Layout.php
- Added validation for setting video loop on media schedule
Relates to: https://github.com/xibosignage/xibo/issues/3617
=> Fixed Schedule Video/Image: Video freezes instead of looping on player

views/log-page.twig
Contains improvements on the current Advanced Filter for Logs: 
- Updated label from `fromDate` to `Date`
- Used `dateTime` for filter instead of `date` only
- Provided help text for user experience 
*Previously, the backend uses `00:00:00` as the default time, thus, the only update needed is for the frontend to use datetime and include the time when sending data to the backend.
Relates to: https://github.com/xibosignage/xibo/issues/3573
=> Fixed Advanced > Logs: Date filter is not working

views/library-page.twig
- Resetting the datatables defaults the selection to the first option, hence changing the option index would solve the issue
Relates to: https://github.com/xibosignageltd/xibo-private/issues/954
=> Fixed Media Filters: Clear filters in media grid should set Retired to No

lib/Controller/Layout.php, lib/Entity/Layout.php
- Skip layout validation when creating from a media file or playlist since media files and playlists have their own validation process
Relates to: https://github.com/xibosignage/xibo/issues/3651
=> Fixed Unable to Schedule a Playlist

lib/Controller/Display.php
relates to xibosignageltd/xibo-private#956
=> Generic error message for entering either expired/wrong display activation code

lib/Controller/Widget.php
Implemented property isolation per element
Fixes multiple issues:
- Fixed Menu board: "Option Value" Prefix and Suffix properties wrongly shared between multiple elements
- Fixed [Weather: Temperature element font size issue after adding Stencils](https://github.com/xibosignage/xibo/issues/3635)
- Fixed [Layout Editor [Text]: Vertical Align and Text to Wrap formatting are not working as expected](https://github.com/xibosignage/xibo/issues/3663)
Relates to: https://github.com/xibosignage/xibo/issues/3667
=> Fixed Menu board: "Option Value" Prefix and Suffix properties wrongly shared between multiple elements
