ui/src/editor-core/layer-manager.js

relates to xibosignageltd/xibo-private#518

Layer Control: Scroll position to selected element

---

modules/templates/global-elements.xml
ui/src/editor-core/element.js
ui/src/editor-core/widget.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#294

Elements: Media library image on editor

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#516

Remove position tab for drawer widget

---

ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#516

Add image to drawer fix

---

lib/Event/LibraryUploadCompleteEvent.php
lib/Helper/XiboUploadHandler.php

relates to xibosignageltd/xibo-private#493

MCASS: add library upload complete event. 

---

modules/src/player-bundle.js
modules/src/player.js
ui/src/helpers/date-format-helper.js
ui/src/helpers/player-helper.js
ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#505

Refactor player.js

---

lib/Widget/RssProvider.php

RSS: fix issue with take items from/to

---

ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3188

Elements: Dataset not showing all added slots in preview/player

---

ui/src/editor-core/element-group.js
ui/src/editor-core/element.js
ui/src/editor-core/widget.js
ui/src/layout-editor/main.js
ui/src/templates/context-menu-group.hbs
views/common.twig

relates to xibosignageltd/xibo-private#520
- One viewer render per multi-delete/group
- Canvas region/widget tidying on saveElements
- Stencil global elements type fix
- Ungroup global elements move to canvas

Add element to group

---

modules/src/xibo-elements-render.js
ui/src/core/forms.js

relates to xibosignageltd/xibo-private#522

Effects control: Set default speed based on selected option

---

ui/src/editor-core/element-group.js
ui/src/editor-core/layer-manager.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/layer-manager.hbs
views/common.twig

relates to xibosignageltd/xibo-private#524

Layer Control: Make groups expandable

---

.github/workflows/test-suite.yaml
cypress/e2e/Display/datasets.cy.js
cypress/e2e/Layout/menuboards.cy.js
cypress/e2e/displaygroups.cy.js
cypress/e2e/displays.cy.js

- Related to https://github.com/xibosignageltd/xibo-private/issues/531

Cypress: Giithub workflow change

---

views/display-page.twig

relates to xibosignage/xibo#3181

Displays: cannot override download/update window start/end times

---

cypress/e2e/Layout/users.cy.js
ui/src/editor-core/widget.js
ui/src/layout-editor/viewer.js
ui/src/templates/viewer-element-content.hbs

relates to xibosignage/xibo#3180

Weather: Required elements and sample data

---

modules/src/xibo-calendar-render.js

relates to xibosignage/xibo#3182

Calender Widget: Exclude weekend days button does nothing

---

modules/src/player.js
modules/templates/forecast-elements.xml
modules/templates/global-elements.xml
ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3130

Weather widget: changing the language doesn't affect the whole template

---

cypress/e2e/campaigns.cy.js
modules/forecastio.xml
modules/src/xibo-legacy-template-render.js
modules/templates/forecast-static.xml

relates to xibosignage/xibo#3167

Weather widget: Convert placeholders format from PHP to Moment

---

ui/src/editor-core/layer-manager.js
ui/src/templates/layer-manager.hbs
views/common.twig

relates to xibosignageltd/xibo-private#526

Layer Control: Show empty "regions"

---

modules/src/player.js

relates to xibosignage/xibo#3196

Weather widget not appearing in correct location in layout preview

---

lib/Controller/Layout.php
lib/Controller/Playlist.php

relates to xibosignageltd/xibo-private#536

Layout Editor: Module and media names are lost after editing

---

modules/src/player.js

relates to xibosignageltd/xibo-private#505

PlayerJS: Refactor to render module templates

---

modules/src/xibo-elements-render.js
modules/src/xibo-text-render.js
modules/templates/article-static.xml
modules/templates/event-static.xml
ui/src/core/forms.js

relates to xibosignageltd/xibo-private#167
- Article content changed to summary like in v3
- Number of items cap fixed
- Groups in effect selector

Widget effects: Make consistent with v3

---

ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#264

Player: Use xiboICTargetId when calling xiboIC.reportFault function

---

lib/Storage/MongoDbTimeSeriesStore.php

- Related to https://github.com/xibosignage/xibo/issues/3210

Bugfix 4.0.5: Proof of play

---

.github/workflows/test-suite.yaml

- Related https://github.com/xibosignageltd/xibo-private/issues/534

Cypress workflow change

---

composer.json
composer.lock
lib/Controller/Display.php
lib/Factory/DisplayFactory.php
lib/Helper/Environment.php
lib/Middleware/CASAuthentication.php
lib/Middleware/SAMLAuthentication.php
lib/Middleware/Theme.php
lib/Widget/RssProvider.php
modules/hls.xml
views/display-page.twig

- RSS date sorting (should be newest first)
- HLS widget retest: should also send the mute parameter
- Display page shouldn't have unnecessary requests for the map pins
- Displays page should show when a player is unsupported (based on the CMS)
- SAML dynamic property fix

4.0.5 issues pt2

---

modules/templates/dataset-static.xml

relates to xibosignage/xibo#3209

Dataset: No data message

---

views/authed-topbar.twig

relates to xibosignage/xibo#3174

UX: Top bar menu entry "Users" has no dropdown and is always open

---

modules/templates/dataset-elements.xml

relates to xibosignage/xibo#3211

Dataset Element: HTML element add escapeHtml attribute

---

ui/src/core/forms.js
ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3223

Layout Editor: Playlist Mixer control no saving

---

modules/widget-html-render.twig
package-lock.json
package.json

relates to xibosignage/xibo#3225

PDF duration per page: set target to interactive controller

---

modules/src/player.js
ui/src/helpers/player-helper.js
ui/src/preview/html-preview.js

relates to xibosignage/xibo#3195

Elements: Fix preview flashes, widget scaling and durationIsPerItem

---

modules/src/xibo-substitutes-parser.js

relates to xibosignageltd/xibo-private#548

Substitute parser null value

---

ui/src/editor-core/layer-manager.js
ui/src/editor-core/widget.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/viewer.hbs

relates to xibosignageltd/xibo-private#547

Layout Editor: Avoid too many viewer refreshes

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3233

Changing data slot shouldn't reload element data

---

ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3233

Auto save fix for code input

---

ui/src/editor-core/layer-manager.js
ui/src/layout-editor/region.js
ui/src/templates/layer-manager.hbs

relates to xibosignageltd/xibo-private#553

Layer Control: Sort layers by drag and drop

---

ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3239

Elements: Fix error when evaluating elements for preview canvas

---

ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3238

Elements: Add capability for multiple pinned slots

---

modules/dataset.xml

relates to xibosignage/xibo#3239

Widgets: Add scaling to dataset module

---

modules/dataset.xml

relates to xibosignage/xibo#3239

Widgets: Revert unnecessary changes

---

modules/src/player.js
modules/src/xibo-elements-render.js

relates to xibosignage/xibo#3154

Elements Marquee: speed issue on android

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/main.js

relates to xibosignage/xibo#3244

Fix duplicated widget when moving

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3252

Fix when adding a second widget to a zone

---

modules/templates/article-static.xml
modules/templates/dataset-static.xml
ui/src/core/forms.js

relates to xibosignage/xibo#3220
- Re-hide article static

Dataset Rich text editor snippets don't update

---

ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3224 xibosignageltd/xibo-private#562

Widgets: Add default value for isDataExpected

---

ui/src/editor-core/properties-panel.js

relates to xibosignageltd/xibo-private#563

Elements: Remove marquee effect for elements and element group

---

package-lock.json
package.json

relates to xibosignageltd/xibo-private#558

PlayerJS and XiboIC: Remove use of window.parent

---

ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#559

Elements: Allow preview of multiple data elements of same type

---

modules/src/player.js

relates to xibosignage/xibo#3154

Widgets: Fix marquee speed for android

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3224

Elements: When to show data fix for weather attribution error

---

modules/templates/article-static.xml
ui/bundle_templates.js
ui/src/core/forms.js
ui/src/editor-core/properties-panel.js
ui/src/style/forms.scss
ui/src/templates/forms/inputs/color.hbs
ui/src/templates/forms/inputs/fontSelector.hbs
ui/src/templates/forms/inputs/tickerTagSelector.hbs
ui/src/templates/forms/inputs/tickerTagStyle.hbs
views/common.twig

relates to xibosignage/xibo#3234

RSS Ticker: add a static template to easily design a marquee

---

lib/Widget/Compatibility/RssWidgetCompatibility.php
modules/templates/article-static.xml

relates to xibosignage/xibo#3256

RSS Ticker: Title and Description marquee needs to be able to render like in v3

---

lib/Entity/DataSetColumn.php
lib/OAuth/AccessTokenRepository.php
lib/OAuth/RefreshTokenRepository.php
lib/Widget/Image.php

- Fixed Access/Refresh token
- Fixed image resize
- Fixed editing heading of a column with listContent

3.3.9 misc issues

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3224

Elements: Show element no data for widget

---

composer.json
composer.lock

- Related to https://github.com/xibosignageltd/xibo-private/issues/566

Composer Update: MongoDB Extension

---

lib/Controller/Campaign.php
lib/Controller/Layout.php
lib/Entity/Campaign.php
lib/Factory/UserGroupFactory.php
lib/Helper/Environment.php
lib/XTR/CampaignSchedulerTask.php
lib/Xmds/Soap6.php
modules/templates/product-elements.xml
tests/XMDS.http
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
views/campaign-builder.twig
views/campaign-form-add.twig
views/campaign-page.twig
views/menuboard-product-page.twig

- Hide canvas region from the thumbnail unless it is the only region. Ensure the thumbnail is generated on publish.
- Format menu board price with 2 decimals on the data entry and widget
- Fix an error on the user grid when a user has a null homepage
- XMDS report fault should protect against super long reasons
- Fix Ad Campaigns add/edit so that impression type can be used

Misc issues 4.0.6

---

lib/Xmds/Soap.php

relates to xibosignageltd/xibo-private#559

XMDS: fix data output for multiple canvas widgets for older players

---

modules/src/player.js
ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#565

Elements: Pin slot with mix of single elements and element groups

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3271

Layout Editor: Remove no data error for image element

---

.github/workflows/build-container.yaml
README.md
db/migrations/20231128144300_real_time_data_migration.php
lib/Controller/DataSet.php
lib/Controller/Schedule.php
lib/Entity/DataSet.php
lib/Entity/Schedule.php
lib/Factory/DataSetFactory.php
lib/Factory/ScheduleFactory.php
lib/Factory/UserGroupFactory.php
lib/Helper/Environment.php
lib/Middleware/ListenersMiddleware.php
lib/Service/MediaService.php
lib/Xmds/Entity/Dependency.php
lib/Xmds/Listeners/XmdsDataConnectorListener.php
lib/Xmds/Soap.php
ui/src/core/xibo-calendar.js
views/dataset-form-add.twig
views/dataset-form-edit.twig
views/dataset-page.twig
views/schedule-form-add.twig
views/schedule-form-edit.twig

Foundational work for data connectors and real time data.
- DataSet extended with "Is Real Time" option and JavaScript
- Scheduled extended with "Data Connector" event type and dataSetId/dataSetParams
- XMDS extended to make both of the above available

Real time data pt1

---

modules/src/player.js
ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#565

Elements: Fix pin slot with mix of elements and and element groups

---

db/migrations/20231220155800_user_module_templates_migration.php
lib/Controller/DataSet.php
lib/Controller/Developer.php
lib/Dependencies/Controllers.php
lib/Entity/ModuleTemplate.php
lib/Factory/ModuleTemplateFactory.php
lib/Factory/UserGroupFactory.php
lib/Widget/Render/WidgetHtmlRenderer.php
lib/routes-web.php
lib/routes.php
modules/realtime-dataset.xml
views/authed-sidebar.twig
views/authed-topbar.twig
views/dataset-data-connector-page.twig
views/dataset-data-connector-test-page.twig
views/dataset-form-add.twig
views/dataset-form-edit.twig
views/dataset-page.twig
views/developer-template-form-add.twig
views/developer-template-form-edit.twig
views/developer-template-page.twig

This PR tidies up the user experience for editing data connector scripts, and allows a data connector to proxy its requests via the CMS (because CORS). Players will also proxy.
It also creates a very simple real time data widget which provides to allow a DataSet to be selected.
It also creates a temporary Module Template editor so that a widget can be designed to take advantage of the real time data widget.

Real time data pt4

---

lib/Controller/DataSet.php
lib/Widget/Render/WidgetHtmlRenderer.php
modules/src/player-bundle.js
package-lock.json
package.json
views/dataset-data-connector-page.twig
views/dataset-data-connector-test-page.twig
views/developer-template-form-edit.twig

This PR tidies up the code and makes it so that you can get data connector results in the editor/preview for static widgets.

Real time data pt5

---

ui/src/editor-core/bottombar.js
ui/src/editor-core/toolbar.js
ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3268

Editor: Fullscreen toggle doesn't scale viewer content

---

ui/src/editor-core/topbar.js

relates to xibosignage/xibo#3269

Editor: Rename layout field selected when opening modal

---

lib/XTR/WidgetSyncTask.php
lib/Xmds/Soap5.php
modules/src/xibo-image-render.js
modules/templates/dataset-static.xml

- SSP adspace enabled flag from v3
- Fix for dataset images not being shown first time around on the player

Misc issues 4.0.7 pt1

---

ui/src/core/xibo-cms.js

relates to xibosignage/xibo#3277
- Schedule duplicated cog also fixed

Duplicated ‘Clear Filters’ fix

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3294

Editor Viewer: Snap to grid is broken

---

ui/src/editor-core/bottombar.js
ui/src/editor-core/change.js
ui/src/editor-core/history-manager.js
ui/src/editor-core/properties-panel.js
ui/src/layout-editor/canvas.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js
ui/src/style/bottombar.scss
ui/src/templates/bottombar-viewer.hbs
views/common.twig

relates to xibosignage/xibo#3292

Layout Editor: Undo button broken

---

ui/src/editor-core/bottombar.js

relates to xibosignage/xibo#3299

Editor preview: Stop button doesn't refresh viewer

---

modules/templates/social-media-static.xml

relates to xibosignageltd/xibo-private#587

US spelling of colour on the appearance tab for elements

---

modules/src/xibo-player.js

relates to xibosignageltd/xibo-private#585

PDF Widget: Fix setting of xiboIC widgetData

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3293

Editor Viewer: Limit values when snapping to border

---

modules/currencies.xml
modules/src/xibo-player.js
modules/stocks.xml
modules/templates/currency-static.xml

relates to xibosignage/xibo#3281

Mastodon widgets / templates no date formatting

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3293

Fix to adjust border area value when scaling with full layout dimensions

---

modules/forecastio.xml
modules/src/xibo-player.js

relates to xibosignage/xibo#3274

Weather Widget: Don't show no data error message on player

---

ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3292

Undo: Fix form old data not being updated

---

ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3312

Element slots: Save broken fix

---

ui/src/layout-editor/main.js

relates to xibosignage/xibo#3311

Elements: Duplicated element error message disappears

---

lib/Entity/ModuleTemplate.php
lib/Factory/ModuleTemplateFactory.php
lib/Widget/Render/WidgetHtmlRenderer.php
modules/calendar.xml
modules/currencies.xml
modules/dataset.xml
modules/mastodon.xml
modules/notificationview.xml
modules/rss-ticker.xml
modules/src/xibo-player.js
modules/stocks.xml
modules/templates/article-static.xml
modules/templates/currency-static.xml
modules/templates/dataset-static.xml
modules/templates/event-static.xml
modules/templates/message-static.xml
modules/templates/social-media-static.xml
modules/templates/stock-static.xml
modules/widget-html-render.twig

relates to xibosignageltd/xibo-private#597

Templates: Requiring module to start animation isn't optimal

---

modules/src/xibo-player.js
ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#586

PlayerJS: Refactor fixes

---

modules/embedded.xml

The player uses these properties to decide how to set up the web view.
fixes xibosignage/xibo#3317

Widget: output transparency/isPreNavigate in XLF.

---

lib/Controller/Schedule.php
lib/Factory/ScheduleFactory.php
ui/src/core/xibo-cms.js
views/schedule-page.twig

- Schedule Grid : display/displayGroup filter adjustments. 
Relates to [#3286](https://github.com/xibosignage/xibo/issues/3286)
- Schedule : Fix add form 404 error with a displayGroupId in session that's no longer in the system.
Relates to [#3266](https://github.com/xibosignage/xibo/issues/3266)

4.0.7 Schedule issues

---

lib/Widget/Compatibility/ClockWidgetCompatibility.php

Relates to xibosignage/xibo#3314

Widget : Fix themeId widget option for analogue clock on upgrade

---

modules/templates/article-static.xml
modules/templates/event-static.xml

relates to xibosignage/xibo#3318

Custom templates: Javascript is escaping some characters

---

ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js

relates to xibosignage/xibo#3296

Editor: Publish modal button needs loading status

---

modules/calendar.xml

relates to xibosignage/xibo#3307

Widget: v4 calendar missing an option from v3 to "show only current"

---

ui/src/editor-core/layer-manager.js
ui/src/layout-editor/main.js

relates to xibosignage/xibo#3320

Layout Editor Layers: Send to back doesn't move Canvas in front of target

---

lib/Controller/Schedule.php
lib/Widget/Image.php

- Schedule : addForm, prevent from 404 error when displayGroupId saved in session filter no longer exists.
- Image : Add a condition to use upsize constraint - compare requested dimensions with CMS resize limit.

3.3.10 - Schedule addForm and Image upsize fixes

---

lib/Controller/Layout.php
lib/Controller/Library.php
lib/Controller/Widget.php
lib/Widget/Render/WidgetDownloader.php

- Widget : Add a condition to use upsize constraint - compare requested dimensions with CMS resize limit.

Widget : Add a condition to usage of upsize constraint.

---

ui/src/editor-core/layer-manager.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js

- Update other object layers even if target's layer doesn't change
- Don't update other's layers if not needed
- Save all regions with one call

Editor Layers: Send to back and update other element's layers

---

ui/src/layout-editor/main.js
views/common.twig

relates to xibosignage/xibo#3329

Editor: Warning for deleting a non-empty playlist

---

ui/src/style/bottombar.scss
ui/src/style/playlist-editor.scss
ui/src/templates/bottombar-viewer.hbs
ui/src/templates/playlist-editor-external-container.hbs
ui/src/templates/playlist-editor.hbs
ui/src/templates/playlist-timeline-info.hbs

relates to xibosignage/xibo#3328

Playlist Editor: Bottom bar content breaks when names are too long

---

ui/src/editor-core/layer-manager.js

relates to xibosignage/xibo#3320

Fix to save target regions on send to back

---

lib/Widget/IcsProvider.php
modules/calendar.xml

relates to xibosignage/xibo#3308

Widget: calendar widget should have an option to hide past events

---

ui/src/style/layout-editor.scss

relates to xibosignageltd/xibo-private#604

Layout Editor: Scrollbar colour changed for Chrome 121

---

lib/Widget/Render/WidgetHtmlRenderer.php
modules/clock-analogue.xml
modules/clock-flip.xml
modules/countdown-clock.xml
modules/countdown-custom.xml
modules/countdown-days.xml
modules/countdown-table.xml
modules/countdown-text.xml
modules/embedded.xml
modules/forecastio.xml
modules/googletraffic.xml
modules/hls.xml
modules/pdf.xml
modules/templates/article-static.xml
modules/templates/currency-static.xml
modules/templates/dataset-static.xml
modules/templates/event-static.xml
modules/templates/forecast-static.xml
modules/templates/global-elements.xml
modules/templates/message-static.xml
modules/templates/social-media-static.xml
modules/templates/stock-static.xml
modules/text.xml
modules/webpage.xml
modules/worldclock-analogue.xml
modules/worldclock-digital-custom.xml
modules/worldclock-digital-date.xml
modules/worldclock-digital-text.xml

relates to xibosignageltd/xibo-private#523

Templates which use properties in HBS should use styles instead

---

lib/Controller/Layout.php
ui/src/editor-core/toolbar.js
ui/src/templates/toolbar-search-form.hbs
views/common.twig

relates to xibosignage/xibo#3302

Editor owner filter as select2

---

ui/src/editor-core/properties-panel.js
ui/src/templates/forms/position.hbs
views/common.twig

relates to xibosignage/xibo#3330

Editor: Create bring back to layout view button

---

modules/embedded.xml

Widget: embedded should output embedHtml in XLF for windows to detect browser tag

---

db/migrations/20180130073838_install_migration.php
db/migrations/20180131122645_one_region_per_playlist_migration.php

xibosignageltd/xibo-private#575

Install: missing indexes on region/playlist 

---

lib/Controller/Layout.php

relates to xibosignage/xibo#3330

Layout: resize canvas region on layout edit

---

ui/src/style/bottombar.scss
ui/src/style/forms.scss
ui/src/style/layout-editor.scss
ui/src/style/playlist-editor.scss
ui/src/templates/bottombar-viewer.hbs

relates to xibosignage/xibo#3328
- Viewer bottom bar
- Widget in Playlist view
- External Playlist editor header

Fix text overflow on multiple places

---

modules/src/xibo-player.js

PlayerJS: Testing for 4.0.7

---

ui/src/templates/forms/region.hbs
views/common.twig
views/region-designer-javascript.twig

relates to xibosignage/xibo#3330

Bring to Layout view for zones and playlists

---

package-lock.json
package.json

relates to xibosignageltd/xibo-private#608

Remove console.log from xiboIC

---

modules/forecastio.xml
modules/templates/article-elements.xml
modules/templates/article-static.xml
modules/templates/currency-elements.xml
modules/templates/currency-static.xml
modules/templates/dataset-elements.xml
modules/templates/dataset-static.xml
modules/templates/event-static.xml
modules/templates/global-elements.xml
modules/templates/message-static.xml
modules/templates/product-category-elements.xml
modules/templates/product-elements.xml
modules/templates/social-media-elements.xml
modules/templates/social-media-static.xml
modules/templates/stock-static.xml
modules/text.xml
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js

relates to xibosignageltd/xibo-private#614

xiboImageRender not working for templates and elements

---

lib/Widget/Compatibility/CurrenciesWidgetCompatibility.php
lib/Widget/Compatibility/StocksWidgetCompatibility.php
modules/currencies.xml
modules/src/xibo-finance-render.js
modules/stocks.xml
tests/integration/Widget/CurrenciesWidgetTest.php
ui/src/preview/html-preview.js

relates to xibosignageltd/xibo-private#615

Remove durationIsPerPage from currencies ans stocks

---

modules/src/xibo-elements-render.js
modules/src/xibo-player.js
ui/src/helpers/date-format-helper.js
ui/src/helpers/player-helper.js

* If you group elements for RSS, the next slot is not previewed
* Dates in Dataset date column do not maintain date format in preview Layout with ID 1248 on develop demonstrates this)
*  Add onDataReady to returned params from getWidgetData params: data, meta, onDataReady

PlayerJS: Fix for 4.0.7

---

modules/src/xibo-player.js

PlayerJS: fix for duration for xiboElementsRender (not being set on elements)
PlayerJS: fix for lock interactions not being called.

Misc playerJS fixes

---

ui/src/preview/html-preview.js

relates to xibosignage/xibo#3333

Layout Preview: Media and Youtube Embed play at the same time when in a playlist

---

modules/src/xibo-player.js
ui/src/helpers/player-helper.js

PlayerJS: Fix pin slot

---

modules/src/xibo-player.js

PlayerJS: Fix undefined repeat data slot and add duration props to groups

---

modules/src/xibo-player.js
ui/src/helpers/player-helper.js

relates to xibosignageltd/xibo-private#626

PlayerJS: Fix pin slot for remaining data slots

---

modules/src/xibo-elements-render.js
modules/src/xibo-layout-animate.js
modules/src/xibo-player.js

relates to xibosignage/xibo#3339

Elements are animated before the window is visible

---

package-lock.json
package.json
ui/src/editor-core/common.js
ui/src/editor-core/history-manager.js
ui/src/editor-core/properties-panel.js
ui/src/editor-core/toolbar.js
ui/src/editor-core/topbar.js
ui/src/helpers/form-helpers.js
ui/src/layout-editor/canvas.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/playlist-editor/main.js
ui/src/playlist-editor/playlist.js

relates to xibosignageltd/xibo-private#627
- Updated select2
- Add common method to clear container
- Clear flatpickr, colorpicker, select2, masonry and CKEditor
- ESLint new line tidying

Layout Editor Performance fix: part 1

---

lib/Entity/Layout.php

relates to xibosignageltd/xibo-private#634

Embedded widget JS error when adding to editor

---

lib/Factory/BaseFactory.php

Grids : Fix potential sql error in nameFilter.

---

db/migrations/20240227102400_missing_indexes_migration.php

fixes xibosignageltd/xibo-private#575

DB: fix missing indexes

---

lib/Controller/Layout.php
lib/Factory/LayoutFactory.php
views/layout-page.twig

fixes xibosignageltd/xibo-private#637

Layouts: add modified since filter to the advanced tab

---

lib/Entity/DataSet.php
lib/Widget/Definition/Property.php
lib/Widget/Definition/Sql.php
modules/dataset.xml

DataSet: handling for SQL syntax in filter/order clauses

---

.github/workflows/test-suite.yaml
Dockerfile.cypress

This commit addresses xibosignageltd/xibo-private#641.

GitHub Actions workflow for Cypress and Testmo integration

---

modules/src/xibo-player.js

relates to xibosignage/xibo#3343

xfA V3 Player: shows items more frequently than desired

---

ui/src/layout-editor/main.js
ui/src/style/common.scss
ui/src/style/layout-editor.scss

relates to xibosignage/xibo#3354

Layout lock overlay disappears on refresh

---

ui/src/editor-core/properties-panel.js
ui/src/helpers/form-helpers.js

relates to xibosignage/xibo#3355

Playlist Editor: Delete button not working and Back button needs to be removed

---

lib/Controller/Layout.php
lib/Controller/Playlist.php
ui/src/editor-core/element-group.js
ui/src/editor-core/element.js
ui/src/editor-core/widget.js
ui/src/layout-editor/canvas.js
ui/src/layout-editor/region.js
ui/src/layout-editor/viewer.js
ui/src/templates/viewer.hbs

relates to xibosignage/xibo#3353

Elements, Widgets, and Regions need to obey sharing

---

views/schedule-form-templates.twig
views/schedule-page.twig

relates to xibosignageltd/xibo-private#459

Schedule: tidy up criteria for alpha

---

ui/src/editor-core/toolbar.js

relates to xibosignageltd/xibo-private#629

Editor toolbar: Fix for removed filter preference on load

---

ui/src/templates/forms/layout.hbs

relates to xibosignage/xibo#3341

Layout BG Colour format fix

---

ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js

relates to xibosignage/xibo#3371

Editor toolbar: Load preferences for a new user is broken

---

ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#639

Fix JS error and moveable when adding from playlist tab

---

lib/Connector/PixabayConnector.php
lib/Connector/ProviderDetails.php

Relates to https://github.com/xibosignageltd/xibo-private/issues/659

Provider Details : return available mediaTypes.

---

bin/locale.php
db/migrations/20231220155800_user_module_templates_migration.php
lib/Controller/Developer.php
lib/Controller/Module.php
lib/Dependencies/Factories.php
lib/Entity/ModuleTemplate.php
lib/Factory/ModuleFactory.php
lib/Factory/ModuleTemplateFactory.php
lib/Factory/UserGroupFactory.php
lib/Listener/ModuleTemplateListener.php
lib/Middleware/ListenersMiddleware.php
lib/routes-web.php
ui/src/core/file-upload.js
ui/src/core/xibo-cms.js
views/developer-template-edit-page.twig
views/developer-template-form-add.twig
views/developer-template-form-copy.twig
views/developer-template-form-delete.twig
views/developer-template-page.twig

Relates to https://github.com/xibosignageltd/xibo-private/issues/643

Template Editor : add missing features

---

ui/src/editor-core/toolbar.js
ui/src/layout-editor/viewer.js
ui/src/playlist-editor/playlist.js
ui/src/style/common.scss
ui/src/style/playlist-editor.scss
ui/src/style/toolbar.scss
ui/src/style/variables.scss
ui/src/templates/toolbar-content-media-table.hbs
ui/src/templates/toolbar.hbs
views/common.twig

relates to xibosignageltd/xibo-private#653

Layout Editor: Zoom levels and media explorer

---

ui/src/layout-editor/main.js
ui/src/templates/context-menu.hbs

relates to xibosignage/xibo#3372

Editor: Can't edit sharing for a widget in a zone

---

ui/src/editor-core/bottombar.js
ui/src/editor-core/history-manager.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/playlist-editor/main.js

relates to xibosignage/xibo#3382

Layout Preview: Elements Displayed Incorrectly After Toggling Full Screen

---

modules/templates/stock-static.xml

relates to xibosignage/xibo#3389

Stock Template 2: Remove Items Per Page option

---

lib/Controller/Developer.php
lib/Entity/ModuleTemplate.php
lib/Factory/ModuleTemplateFactory.php
views/developer-template-edit-page.twig
views/developer-template-form-add.twig
views/developer-template-page.twig

Relates to https://github.com/xibosignageltd/xibo-private/issues/643

Module Template : fixes after initial tests.

---

views/developer-template-edit-page.twig

relates to xibosignageltd/xibo-private#644
- Fix for deleting advanced options and not being saved
- Fix for saving advanced controls without twice JSON stringify

Template Editor controls fixes

---

lib/Controller/Display.php
lib/Controller/DisplayGroup.php
lib/Controller/Schedule.php
lib/Factory/DisplayGroupFactory.php
ui/src/core/xibo-calendar.js
ui/src/core/xibo-cms.js
views/schedule-form-add.twig
views/schedule-page.twig

Relates to https://github.com/xibosignageltd/xibo-private/issues/602

Schedule : Switch display filters from using session to local storage.

---

views/user-form-preferences.twig

User: update help text to be clearer

---

ui/src/style/toolbar.scss
ui/src/templates/toolbar-card-layout-template.hbs
ui/src/templates/toolbar-card-media.hbs

relates to xibosignage/xibo#3393

Editor: Layout exchange cards open new tab when selected

---

lib/Entity/Layout.php
ui/src/editor-core/properties-panel.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/forms/widget.hbs

relates to xibosignage/xibo#3379
- Warning message for required elements
- Sample data shown as info

Widget: Required elements only work per widget

---

package-lock.json
package.json

relates to xibosignage/xibo#3396

Remove webpack-bundle-analyzer package

---

lib/Controller/DataSetRss.php
lib/routes.php

DataSet: error viewing DataSet RSS feed.

---

lib/Entity/DataSet.php

DataSet: create using utf8mb4

---

cypress/e2e/Layout/Editor/layout_editor_dataset.cy.js

- The column selection for the dataset was done incorrectly; the wrong column name was used.

Cypress Fix

---

ui/src/editor-core/change.js
ui/src/editor-core/common.js
ui/src/editor-core/history-manager.js
ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js
ui/src/playlist-editor/playlist.js
views/common.twig

relates to xibosignageltd/xibo-private#667

Elements editing: Undo

---

modules/templates/global-elements.xml

relates to xibosignageltd/xibo-private#662

Global Elements: Add Date

---

lib/Widget/Definition/Property.php
ui/src/core/forms.js
ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js
ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3378

Weather: Date element and Widget have both Language properties

---

lib/Controller/Layout.php
ui/src/editor-core/bottombar.js
ui/src/editor-core/widget.js
ui/src/style/bottombar.scss
ui/src/templates/bottombar-viewer.hbs
views/layout-designer-page.twig

relates to xibosignageltd/xibo-private#682

Editor Bottom Bar: Add template info for static widgets

---

ui/src/style/playlist-editor.scss

relates to xibosignageltd/xibo-private#678

Playlist Inline Editor: Multi-select not working

---

modules/src/xibo-player.js
modules/templates/global-elements.xml

relates to xibosignageltd/xibo-private#684

Element shapes: Option to fill area

---

ui/src/editor-core/toolbar.js
ui/src/templates/toolbar-card-media-upload.hbs
ui/src/templates/toolbar-card-playlist-new-template.hbs
views/common.twig

relates to xibosignageltd/xibo-private#686

Editor Toolbar: New Playlist not working with no results

---

ui/src/editor-core/bottombar.js

relates to xibosignageltd/xibo-private#682

Editor Bottom Bar: Fix rendering for non data widgets

---

ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#680

Layout Editor: Playlist thumbnail doesn't resize when viewer changes

---

ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js
ui/src/style/playlist-editor.scss
ui/src/templates/topbar-external-playlist-message.hbs
ui/src/templates/topbar-playlist-switch.hbs
views/common.twig

relates to xibosignageltd/xibo-private#687

Remove Sub-Playlist advanced button

---

modules/countdown-clock.xml
modules/countdown-days.xml
modules/countdown-table.xml
modules/countdown-text.xml
modules/src/xibo-countdown-render.js

relates to xibosignageltd/xibo-private#685

Countdown: Warning message issues and skipped seconds

---

ui/src/style/toolbar.scss

relates to xibosignageltd/xibo-private#688

Toolbar levels: Adjust form controls width accordingly

---

lib/Connector/XiboExchangeConnector.php
lib/Controller/Template.php
lib/Entity/SearchResult.php
lib/Event/TemplateProviderEvent.php
ui/src/editor-core/toolbar.js

Relates to https://github.com/xibosignageltd/xibo-private/issues/665

Layout Exchange : Improve filters, add concept of featured templates.

---

modules/templates/forecast-elements.xml

relates to xibosignageltd/xibo-private#701

Weather: Change Background Image element name

---

modules/src/handlebars-helpers.js
modules/templates/global-elements.xml
ui/bundle_templates.js
ui/src/core/forms.js
ui/src/editor-core/properties-panel.js
ui/src/style/forms.scss
ui/src/templates/forms/inputs/colorGradient.hbs
views/common.twig

relates to xibosignageltd/xibo-private#700

Elements: Add gradient control

---

modules/src/handlebars-helpers.js
modules/templates/forecast-elements.xml

relates to xibosignageltd/xibo-private#702

Weather image: Media selector not working in preview

---

db/migrations/20240430112500_canvas_duration_fix_migration.php

xibosignageltd/xibo-private#672

Widget: fix Canvas module default duration.

---

lib/Middleware/Theme.php

SLO : Fix logout link.

---

lib/Controller/Folder.php
lib/Controller/Settings.php
lib/Entity/Display.php
lib/Factory/FolderFactory.php
lib/Service/ConfigService.php
lib/Service/ConfigServiceInterface.php
lib/Xmds/Soap5.php
views/settings-page.twig

Displays : Nominate an initial Folder.

---

docker/tmp/settings-custom.php
lib/Middleware/SAMLAuthentication.php

SAML: add option to match groups with the IdP.

---

ui/src/editor-core/common.js
ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js
ui/src/style/common.scss
ui/src/templates/toolbar.hbs
views/common.twig

relates to xibosignage/xibo#2720

Layout/Playlist Editor: minimum resolution

---

lib/Connector/PixabayConnector.php

Connector: Pixabay fix broken video thumbnail.

---

ui/src/editor-core/bottombar.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/templates/bottombar-viewer.hbs
views/common.twig

relates to xibosignage/xibo#3411

Editor Multi-select: Use bottombar and keyboard to delete

---

modules/dataset.xml

Widget: DataSet should be a required property

---

modules/templates/global-elements.xml

relates to xibosignageltd/xibo-private#699

Image placeholder doesn't render shadow

---

modules/templates/dataset-static.xml
ui/src/core/forms.js

relates to xibosignage/xibo#3402

Dataset Static Templates - Column Ordering Not Preserved

---

modules/templates/currency-static.xml
modules/templates/dataset-static.xml
modules/templates/social-media-static.xml
modules/templates/stock-static.xml

relates to xibosignage/xibo#3397

Mastodon: Static template can not show formatted date

---

lib/Connector/OpenWeatherMapConnector.php
lib/Widget/DataType/Forecast.php
modules/templates/forecast-elements.xml

Relates to xibosignageltd/xibo-private#698

Weather Elements: Add location

---

ui/src/editor-core/bottombar.js
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js

relates to xibosignageltd/xibo-private#696

Editor Keyboard Shortcuts

---

ui/src/editor-core/common.js
ui/src/editor-core/toolbar.js
ui/src/editor-core/topbar.js
ui/src/layout-editor/main.js
ui/src/templates/topbar.hbs
views/common.twig

relates to xibosignageltd/xibo-private#716

Editor: Delete confirmation modal option and multi delete confirm

---

lib/Helper/DatabaseLogHandler.php

Relates to xibosignage/xibo#3347

Daily Maintenance: Limit number of logs deleted in a single transaction

---

modules/templates/forecast-elements.xml

relates to xibosignage/xibo#3025

Weather widget units: Option to present units with '/' symbol

---

lib/Controller/Playlist.php
lib/routes.php

Relates to https://github.com/xibosignageltd/xibo-private/issues/705

Playlist : Convert from Layout Editor to global

---

lib/Connector/OpenWeatherMapConnector.php
views/openweathermap-form-settings.twig

relates to xibosignage/xibo#3417

Connector: OpenWeather onecall 2.5 EOL

---

lib/Factory/ModuleXmlTrait.php
lib/Widget/Definition/ElementGroup.php
lib/Widget/Definition/Stencil.php
modules/templates/forecast-elements.xml
ui/src/editor-core/widget.js
ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#694

Stencils to create multiple groups

---

modules/clock-analogue.xml

relates to xibosignage/xibo#3423

Clock Widget: Fix alignment

---

ui/src/playlist-editor/playlist-timeline.js

relates to xibosignage/xibo#3425

Layout Editor: Loader stuck when coming from inline Playlist editor

---

ui/src/editor-core/properties-panel.js
ui/src/templates/forms/region.hbs
views/common.twig

relates to xibosignageltd/xibo-private#713

Region exit transition

---

lib/Controller/MenuBoard.php
lib/Dependencies/Controllers.php
lib/Factory/MenuBoardFactory.php

Adjust the feature check to be inline with other controllers add function
fixes xibosignage/xibo#3416

Folders: menuboard add ignores the provided folderId.

---

lib/Controller/Library.php
lib/Widget/Render/WidgetDownloader.php
views/menuboard-category-page.twig
views/menuboard-product-page.twig
views/playlist-dashboard-spots.twig
views/playlist-dashboard.twig

Library: OOM generating thumbnails/previews for large images

---

ui/src/layout-editor/main.js
ui/src/templates/forms/region.hbs
views/common.twig
views/region-designer-javascript.twig

relates to xibosignageltd/xibo-private#721

Convert inline playlist to a global playlist - Front-End

---

lib/Helper/XiboUploadHandler.php

This PR implements element checking on replacement of an image in the Library.
fixes xibosignage/xibo#3418

Library: replaced images are not replaced in layouts when they are used as elements

---

lib/Controller/DataSet.php
lib/Controller/Display.php
lib/Controller/Font.php
lib/Controller/Layout.php
lib/Controller/Library.php
lib/Controller/Notification.php
lib/Controller/PlayerSoftware.php
lib/Controller/Preview.php
lib/Controller/Task.php
lib/Controller/Widget.php

relates to xibosignage/xibo#3427

Library upload API returns plain/text instead of application/json

---

modules/src/player-bundle.js
modules/src/xibo-text-scaler.js
modules/templates/currency-elements.xml
modules/templates/forecast-elements.xml
modules/templates/global-elements.xml
modules/templates/product-elements.xml
modules/templates/stock-elements.xml
ui/src/layout-editor/main.js
ui/src/playlist-editor/main.js

relates to xibosignageltd/xibo-private#664

Text element: Adjust to area

---

ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/style/common.scss
ui/src/style/layout-editor.scss
ui/src/templates/context-menu.hbs
views/common.twig

relates to xibosignage/xibo#3255

Text Element: Inline editing

---

modules/widget-html-render.twig
views/base.twig
views/licence.twig

- Dynamically update copyright year
Relates to: https://github.com/xibosignageltd/xibo-private/issues/719

Updated copyright year

---

package-lock.json
package.json
ui/bundle_vendor.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss

relates to xibosignageltd/xibo-private#691

Editor: Drag to select

---

db/migrations/20240612112949_add_switch_delay_and_video_pause_delay_to_sync_group.php
db/migrations/20240614031633_update_switch_delay_and_video_pause_delay_migration.php
lib/Controller/SyncGroup.php
lib/Entity/SyncGroup.php
lib/Factory/SyncGroupFactory.php
lib/Xmds/Soap5.php
views/syncgroup-form-add.twig
views/syncgroup-form-edit.twig
views/syncgroup-page.twig
web/swagger.json

- Added Switch Delay and Video Pause Delay in Sync Group
Relates to: https://github.com/xibosignage/xibo/issues/3200

Sync Group: Add Switch Delay and Video Pause Delay

---

lib/Entity/DataSet.php
modules/dataset.xml

relates to xibosignage/xibo#3062

Widgets: Add the ability to filter datasets by display tag

---

db/migrations/20240617040320_add_o_s_details_to_display_table_migration.php
lib/Entity/Display.php
lib/Factory/DisplayFactory.php
lib/Xmds/Soap4.php
lib/Xmds/Soap5.php
views/display-page.twig

- Added osVersion, osSdk, manufacturer, brand, model in `Display` 
Relates to: https://github.com/xibosignageltd/xibo-private/issues/725

Display: register should process operating system if sent by the player

---

ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#691

Drag to select: Click on layout refresh fix

---

modules/templates/global-elements.xml

relates to xibosignageltd/xibo-private#755

Image element: Extra characters need to be removed

---

lib/Controller/Display.php
lib/Controller/Tag.php
lib/Entity/Display.php
lib/Entity/Notification.php
lib/Event/TriggerTaskEvent.php
lib/Factory/TagTrait.php
lib/Helper/Environment.php
lib/Listener/DisplayGroupListener.php
lib/Listener/TaskListener.php
lib/Middleware/ListenersMiddleware.php
lib/Middleware/State.php
lib/Widget/Render/WidgetDataProviderCache.php
lib/XTR/MaintenanceRegularTask.php
lib/Xmds/Soap.php
modules/webpage.xml
package-lock.json
web/swagger.json

This PR merges in develop (4.0.12) and updates the version number to 4.1.0-alpha2

Release 4.1.0-alpha2

---

lib/Controller/Layout.php
views/layout-page.twig
views/template-form-add.twig
views/template-page.twig

relates to xibosignageltd/xibo-private#736

Multiple references to Layout Designer

---

ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js
ui/src/templates/toolbar-card-playlist-new-template.hbs
ui/src/templates/toolbar-card-playlist-template.hbs

relates to xibosignage/xibo#3426

Template editing: Adding playlists to zones fix

---

ui/src/layout-editor/main.js
ui/src/templates/toolbar-card-media-upload.hbs

relates to xibosignageltd/xibo-private#724

Media Upload to Inline Playlist

---

ui/src/templates/form-helpers-chart-colors.hbs
ui/src/templates/form-helpers-chart-graph-config.hbs
ui/src/templates/form-helpers-data-set-filter-clause.hbs
ui/src/templates/form-helpers-data-set-order-clause.hbs
ui/src/templates/form-helpers-sub-playlist-form.hbs
ui/src/templates/form-helpers-twitter-metro-colors.hbs

relates to xibosignageltd/xibo-private#727

Layout Editor: Dataset form Filter enter key creates a new Order clause

---

lib/Controller/Library.php
lib/Entity/Media.php
lib/Factory/MediaFactory.php

- Fixes issue on adding item from provider already in library error.
Relates to: https://github.com/xibosignageltd/xibo-private/issues/728

Editor Toolbar: Fixed adding item from provider already in library error

---

.github/workflows/test-suite.yaml

- Related to https://github.com/xibosignageltd/xibo-private/issues/758
Regex Validation and use of GitHub Actions environment variable

Security Fix: Github workflow input validation

---

ui/src/editor-core/bottombar.js
ui/src/editor-core/element.js
ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js
ui/src/layout-editor/main.js
ui/src/style/bottombar.scss
ui/src/templates/bottombar-viewer.hbs
views/layout-designer-page.twig

relates to xibosignageltd/xibo-private#744

Image Element: Show media info

---

ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#748

Element group condition isn't always right

---

views/command-form-add.twig
views/command-page.twig

relates to xibosignageltd/xibo-private#635

Command page: Fix names inconsistency

---

lib/Factory/ConnectorFactory.php

- Fixed file based settings should override database settings
Relates to: https://github.com/xibosignage/xibo/issues/3436

Connector: Fixed file based settings should override database settings

---

lib/Controller/DataSet.php
lib/routes-web.php
lib/routes.php
views/dataset-form-selectfolder.twig

relates to xibosignageltd/xibo-private#610

Dataset Grid: Select folder is not available is dateset item menu

---

ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/style/variables.scss

relates to xibosignageltd/xibo-private#757

Highlight Editor Preview

---

lib/Connector/OpenWeatherMapConnector.php
lib/Controller/Schedule.php
lib/Event/ScheduleCriteriaRequestEvent.php
lib/Event/ScheduleCriteriaRequestInterface.php
ui/src/core/xibo-calendar.js
views/schedule-form-add.twig
views/schedule-form-edit.twig

relates to xibosignageltd/xibo-private#704

Custom schedule criteria (via connectors)

---

lib/Factory/ModuleXmlTrait.php
lib/Widget/CurrenciesAndStocksProvider.php
lib/Widget/Definition/Property.php
modules/src/xibo-finance-render.js
modules/templates/currency-static.xml
modules/templates/stock-static.xml
tests/integration/Widget/CurrenciesWidgetTest.php

relates to xibosignage/xibo#3441

Stocks: Incorrect calculation of Total Duration for elements with Duration Per Item

---

lib/Controller/DataSet.php
lib/Controller/Font.php
lib/Controller/Layout.php
lib/Controller/Library.php
lib/Controller/Notification.php
lib/Controller/PlayerSoftware.php
lib/Helper/AttachmentUploadHandler.php
lib/Helper/BlueImpUploadHandler.php
lib/Helper/DataSetUploadHandler.php
lib/Helper/HttpsDetect.php
lib/Helper/LayoutUploadHandler.php
lib/Helper/UploadHandler.php
lib/Helper/XiboUploadHandler.php
lib/Service/ConfigService.php
lib/Service/UploadService.php
lib/Xmds/Wsdl.php
ui/src/core/xibo-cms.js
ui/src/editor-core/history-manager.js
ui/src/editor-core/toolbar.js
ui/src/editor-core/widget.js
ui/src/layout-editor/canvas.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/layout-editor/region.js
ui/src/playlist-editor/main.js
views/playlist-page.twig

No user facing changes are expected from the PR, the features effected should continue to work as before.
- Strip back the file upload handler to remove functions we do not use
- Modify the way we reload pages from JavaScript
- Misc sanitisation improvements

Misc improvements with sanitization, etc

---

modules/forecastio.xml

relates to xibosignage/xibo#3400

Widget: Weather widget displays "No results returned, please configure Open Weather Map Connector!"

---

lib/Entity/Media.php
lib/Service/ImageProcessingService.php
lib/XTR/ImageProcessingTask.php

- Fixed image not updating values when resizing
Relates to: https://github.com/xibosignage/xibo/issues/3443

Media: Fixed image not updating values when resizing

---

ui/src/editor-core/bottombar.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js

relates to xibosignage/xibo#3448

Editor: Bottom-bar not rendering when leaving multi-select

---

lib/Connector/OpenWeatherMapConnector.php

relates to xibosignage/xibo#3435

Connector: open weather map paid plan does not work

---

ui/src/editor-core/element.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss

relates to xibosignageltd/xibo-private#756

Editor: Widget loading status

---

ui/src/layout-editor/main.js

relates to xibosignage/xibo#3449

Editor: Adding the first data element throws a console error

---

modules/templates/currency-static.xml
modules/templates/stock-static.xml

relates to xibosignage/xibo#3441

Fix for older JS rendering engines

---

lib/Controller/Layout.php
lib/Controller/Library.php
lib/Controller/Playlist.php
ui/src/templates/form-buttons.hbs
ui/src/templates/forms/button.hbs
views/authed.twig
views/xibo-audience-connector-form-javascript.twig

- Fixed onclick btn CSP error
Relates to: https://github.com/xibosignageltd/xibo-private/issues/770

Fixed onclick btn CSP error

---

views/dataset-column-form-add.twig
views/dataset-column-form-edit.twig

relates to xibosignageltd/xibo-private#791

Dataset Add Column: Update help text to warn that column names with spaces cannot be used

---

lib/Controller/User.php
lib/Factory/UserFactory.php
views/user-form-add.twig
views/user-form-edit.twig
views/user-page.twig

relates to xibosignage/xibo#3087

Users: filter by first/last name (rename Name to Username)

---

lib/Connector/OpenWeatherMapConnector.php
lib/Event/XmdsWeatherRequestEvent.php
lib/Xmds/Soap7.php
views/openweathermap-form-settings.twig

relates to xibosignageltd/xibo-private#648

Schedule: Criteria based scheduling - part 2

---

lib/Report/ProofOfPlay.php

relates to xibosignageltd/xibo-private#798

Proof of Play: validate sortBy parameter has an expected value.

---

lib/Entity/DataSet.php
lib/Entity/DataSetColumn.php

relates to https://github.com/xibosignageltd/xibo-private/issues/799

DataSet : Better validate formula column.

---

ui/src/editor-core/properties-panel.js
ui/src/editor-core/toolbar.js
ui/src/playlist-editor/main.js

relates to xibosignage/xibo#3450

Editor Toolbar: Inline playlist throws JS error on slow networks when closing

---

lib/Controller/DataSet.php
lib/Controller/DataSetData.php
lib/Entity/DataSet.php

relates to xibosignageltd/xibo-private#800

DataSet: improve query structure in importJSON/addRow

---

lib/Controller/DataSet.php
lib/Controller/DataSetData.php
lib/Entity/DataSet.php
lib/Report/ProofOfPlay.php

Proof of Play: validate sortBy parameter has an expected value
DataSet: improve query structure in importJSON/addRow

Borelley: misc fixes

---

lib/Controller/DataSet.php
lib/Controller/DataSetData.php
lib/Entity/DataSet.php
lib/Report/ProofOfPlay.php

Proof of Play: validate sortBy parameter has an expected value.
DataSet: improve query structure in importJSON/addRow

Westphal: misc fixes

---

lib/Helper/Environment.php

@ifarzana no release test required here as we have only changed the 1 thing that has already been PR tested.

Release: 4.0.14

---

lib/Helper/Environment.php

@ifarzana no release test required here as we have only changed the 1 thing that has already been PR tested.

Release: prep for 3.3.12.

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/main.js
ui/src/templates/forms/region.hbs
views/region-form-edit.twig

relates to xibosignageltd/xibo-private#775

Editor Property Panel: Keep same tab when moving between objects

---

ui/src/editor-core/toolbar.js
ui/src/style/toolbar.scss

relates to xibosignageltd/xibo-private#788

Editor Toolbar: Media load ready for slow connections

---

lib/Controller/DataSet.php
lib/Controller/DataSetData.php

relates to xibosignage/xibo#3457

DataSet: fix regression in filter clause matching for uniqueKey and data entry filtering

---

modules/src/xibo-player.js
ui/src/core/file-upload.js
ui/src/core/xibo-cms.js
ui/src/editor-core/toolbar.js
ui/src/layout-editor/canvas.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/layout-editor/region.js
ui/src/playlist-editor/playlist.js
ui/src/preview/html-preview.js
views/dataset-data-connector-page.twig
views/display-page.twig
views/notification-page.twig

relates to xibosignageltd/xibo-private#786

Change logs to debug logs to de-clutter dev console

---

lib/Controller/Library.php
ui/src/core/xibo-cms.js
ui/src/editor-core/toolbar.js
ui/src/templates/toolbar-search-form.hbs
views/common.twig

relates to xibosignageltd/xibo-private#778

Editor toolbar: Search by folder

---

db/migrations/20240717113400_add_last_used_time_to_session_history_table_migration.php
lib/Helper/Session.php
lib/Report/SessionHistory.php
reports/sessionhistory-report-form.twig

- Added `session` option and `session history table` in Sessions report 
Relates to: https://github.com/xibosignageltd/xibo-private/issues/747

Report: Add Session History

---

views/user-form-onboarding.twig
views/user-page.twig
web/theme/default/css/xibo.css

relates to xibosignageltd/xibo-private#782

Add user: Select/Deselect all folders

---

lib/Controller/Folder.php
lib/Factory/FolderFactory.php
lib/routes.php
web/swagger.json

- Added folders search API 
Relates to: https://github.com/xibosignage/xibo/issues/3385

Folders: Implement exact matching search

---

lib/Entity/Schedule.php

relates to xibosignage/xibo#3444

Schedule Event: Add Form Modal Doesn't Close on Save When Criteria is Added

---

ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/viewer-playlist-controls.hbs

relates to xibosignageltd/xibo-private#806

Editor Viewer: Tags and controls overlap issue

---

modules/templates/event-static.xml

relates to xibosignage/xibo#3453

Weekly and Monthly Calendar widgets display issue on WebOS

---

db/migrations/20240717043020_add_data_connector_source_to_dataset_table_migration.php
lib/Connector/DataConnectorScriptProviderInterface.php
lib/Connector/DataConnectorSourceProviderInterface.php
lib/Controller/DataSet.php
lib/Entity/DataSet.php
lib/Event/DataConnectorScriptRequestEvent.php
lib/Event/DataConnectorSourceRequestEvent.php
lib/Factory/DataSetFactory.php
lib/Xmds/Soap.php
views/dataset-data-connector-page.twig
views/dataset-form-add.twig
views/dataset-form-edit.twig
views/dataset-page.twig

relates to xibosignageltd/xibo-private#753

Real-time data: provide the data connector JS via Connectors

---

lib/Entity/Media.php

fixes to xibosignage/xibo#3454

Media: when deleting a media record reinstate its parent if it has one

---

ui/src/layout-editor/viewer.js
ui/src/templates/viewer-playlist-controls.hbs

relates to xibosignage/xibo#3466

Playlist: Previous/Next and Edit buttons not clickable

---

ui/src/editor-core/properties-panel.js

relates to xibosignageltd/xibo-private#817

Editor: Elements don’t render properly after changing properties

---

lib/Connector/OpenWeatherMapConnector.php

relates to xibosignage/xibo#3447

The weather widget not functioning with specific coordinates such as those for Adelaide

---

views/dataset-form-edit.twig

relates to xibosignage/xibo#3459

Dataset: typographical error in the dataset Edit Form

---

lib/Widget/Definition/Property.php
lib/Xmds/Soap.php
modules/localvideo.xml

relates to xibosignage/xibo#3461

Local Video: Widget video path does not allow windows file path

---

ui/src/playlist-editor/main.js
ui/src/playlist-editor/playlist-timeline.js

relates to xibosignageltd/xibo-private#820

Playlist Inline Editor: Disable sort for published layout

---

views/welcome-page.twig

relates to xibosignageltd/xibo-private#818

Welcome page: training mention text update

---

package-lock.json
package.json

relates to xibosigangeltd/xibo-private#816

XLR: Fixing slow preview caused by multiple unnecessary network calls

---

modules/src/xibo-player.js
modules/templates/global-elements.xml

relates to xibosignageltd/xibo-private#808

Layout Preview: Circle and Date/Time not being rendered #808

---

modules/src/xibo-player.js
modules/src/xibo-text-render.js

relates to xibosignageltd/xibo-private#796

Mastodon: Fix for item direction horizontal setting and overflow text

---

views/welcome-page.twig

relates to xibosignageltd/xibo-private#818

Welcome page: training mention text update (#2670)

---

ui/src/core/xibo-cms.js
ui/src/editor-core/toolbar.js

relates to xibosignageltd/xibo-private#823

Toolbox folder control: Save preferences and reload is broken

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/viewer.js

relates to xibosignageltd/xibo-private#821

Editor: Element resize and position tab issues

---

lib/Report/TimeDisconnectedSummary.php
reports/timedisconnectedsummary-report-form.twig

Part 1:
- Implement `Group By` filter option 
- Added `Availability Percentage` column
- Implement dynamic table columns display
Relates to: https://github.com/xibosignage/xibo/issues/3357

Reporting: Add Availability and Grouping Option

---

ui/src/core/forms.js

relates to xibosignageltd/xibo-private#828

Module Settings: Translation from editor throwing error

---

lib/Controller/DataSet.php
lib/Helper/DataSetUploadHandler.php
lib/XTR/RemoteDataSetFetchTask.php
views/dataset-form-edit.twig

relates to xibosignage/xibo#3458

DataSet: trying to import without any columns logs an unhelpful error

---

lib/Controller/Schedule.php
ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3460

Schedule Action: Unable to save Action event due to an error

---

lib/Factory/DataSetFactory.php
lib/Helper/DataSetUploadHandler.php

relates to xibosignage/xibo#3456
- `ini_set('auto_detect_line_endings', true);` is deprecated.

Dataset: Importing a CSV file with an empty line fails via remote dataset and uploading the file

---

lib/Helper/Environment.php
locale/default.pot

No release test required for this RC, all PRs have been independently tested. @ifarzana to sign off please.
xibosignageltd/xibo-private#830

Release prep: 4.1.0-rc2

---

views/campaign-page.twig

"Cherry-pick" from the same issue in v4.
Relates to https://github.com/xibosignage/xibo/issues/3474

Campaign : Fix tags on edit form.

---

.github/workflows/build-container.yaml

xibosignageltd/xibo-private#832

Build release40

---

lib/Controller/Developer.php
views/developer-template-edit-page.twig

Developer: fix import and hide temporary text area

---

lib/Controller/Developer.php

Developer: persist data type

---

package-lock.json
package.json

relates to xibosignageltd/xibo-private#824

XLR: Fix layout preview background

---

modules/templates/global-elements.xml

relates to xibosignage/xibo#3475

Layout Preview: Fix text element fit to selection

---

lib/Entity/DataSetColumn.php

relates to xibosignage/xibo#3404

DataSet: Value discrepancy when storing large integers in number values

---

lib/Entity/DataSet.php

relates to xibosignage/xibo#3463

Dataset Advanced Filter: Text based display tag is not replaced at runtime on the player

---

views/login.twig
views/non-authed.twig
views/tfa.twig
views/upgrade-in-progress-page.twig

relates to xibosignageltd/xibo-private#827

Shrunken login page

---

views/displayprofile-form-edit-android.twig
views/displayprofile-form-edit-javascript.twig

xibosignageltd/xibo-private#831

Display Profile: correct the help text on android screen dimensions

---

lib/Controller/Library.php
lib/Controller/Module.php
lib/Entity/Module.php
lib/Factory/ModuleFactory.php
modules/genericfile.xml
views/module-form-settings.twig

- Modules: Disable library media preview for generic file
Relates to: https://github.com/xibosignageltd/xibo-private/issues/802

Modules: Disable library media preview for generic file

---

ui/src/editor-core/layer-manager.js
ui/src/editor-core/properties-panel.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/layer-manager.hbs
views/common.twig

relates to xibosignageltd/xibo-private#826

Layout Editor: Background image layer in viewer and control

---

views/displaygroup-form-media.twig

- Added file assignment search filter
Relates to: https://github.com/xibosignage/xibo/issues/3477

Displays: Add file assignment search filter

---

ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/context-menu.hbs
ui/src/templates/viewer-playlist-controls.hbs
views/layout-designer-page.twig

relates to xibosignageltd/xibo-private#838

Layout Editor: we should not show the playlist editor for dynamic playlists

---

ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#849

Editor: Deleting elements and groups at the same time throws error

---

ui/src/editor-core/history-manager.js
ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js

relates to xibosignageltd/xibo-private#848

Editor Viewer: Slot not being updated for groups

---

ui/src/core/xibo-cms.js
views/notification-page.twig

relates to xibosignageltd/xibo-private#835

Fix validation for hidden inputs

---

ui/src/core/xibo-cms.js

relates to xibosignage/xibo#3407

Folders : Share multiple in one action

---

lib/Connector/XiboExchangeConnector.php
lib/Controller/Template.php
lib/Event/TemplateProviderListEvent.php
lib/routes-web.php
ui/src/editor-core/toolbar.js
ui/src/style/toolbar.scss
ui/src/templates/toolbar-content.hbs
views/common.twig

Connector: add a template provider list route, event and handle in exchange connector.
fixes xibosignage/xibo#3497

Layout Editor: exchange tab should not be visible if the connector is disabled

---

views/campaign-form-edit.twig

relates to xibosignage/xibo#3482

Campaign: Layout assignment filtering improvements

---

lib/Entity/Widget.php

relates to xibosignageltd/xibo-private#856

Auditing: adding/deleting a widget should log the mediaId being modified if there is one

---

lib/Report/ProofOfPlay.php
reports/proofofplay-report-form.twig
tests/XMDS.http

FE:
- Added `Group By` filter options
- Show and hide columns based on group by selection
BE:
- [mySQL and MongoDB] Added data calculation for accumulating the values according to grouping option
Relates to: https://github.com/xibosignage/xibo/issues/3356

Reports: Add Proof of Play MySQL grouping

---

ui/src/style/layout-editor.scss

relates to xibosignage/xibo#3494

Playlist Page: Top bar styled like the Editor topbar

---

modules/templates/forecast-elements.xml

relates to xibosignage/xibo#3495

Widget: weather stencil unable to copy asset

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3498

Add Synchronised Event: Save button not working

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3501

Grouping Elements: Error in console breaks flow

---

ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
views/common.twig

relates to xibosignage/xibo#3486
- Also fix for deleting a single region with drag select

Editor: Elements added in quick succession create multiple widgets

---

bin/locale.php
lib/Service/NullLogService.php

relates to xibosignage/xibo#3500

Locale: fix error with translations generation script.

---

ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3488

Layout Editor: you can't upload an image into an image placeholder

---

lib/Xmds/Soap5.php

Commands: fix XMDS output for createAlertOn

---

lib/Controller/Library.php
lib/Factory/MediaFactory.php

- Add media (URL) Fix for unsupported medial URL
Relates to: https://github.com/xibosignage/xibo/issues/3514

Add media (URL): Fix for unsupported medial URL

---

lib/Controller/DataSet.php
lib/Entity/DataSet.php

- Add data validation and error message for long URI string
Relates to: https://github.com/xibosignage/xibo/issues/3511

Remote Dataset: Fix for unexpected error for long URI string

---

web/xmds.php

relates to xibosignageltd/chromeos#18

Fix: JavaScript asset Content-Type

---

lib/Report/DisplayAlerts.php
reports/displayalerts-report-form.twig

- Add `Event Type` filter option
- Add `Duration` column
Relates to: https://github.com/xibosignage/xibo/issues/3490

Reporting: Display Alert Report Improvements

---

modules/calendar.xml

relates to xibosignage/xibo#3507

Calendar: All-Day Events displayed in monthly calendar despite Exclude All-Day option enabled

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3519

Schedule Filter: Cannot clear dates when selecting a range

---

modules/src/xibo-text-scaler.js
modules/templates/global-elements.xml

relates to xibosignage/xibo#3522
- Gradient hides some text options
- Text scaler using italic and bold
- Fix for SVG rendering

Gradients on text or elements do not render in the player

---

modules/src/xibo-player.js
ui/src/helpers/player-helper.js

relates to xibosignage/xibo#3485

Preview: Fix element group rendering with respect to layer

---

ui/src/core/xibo-calendar.js
views/schedule-form-templates.twig

- Schedule Criteria: Fix wrong delete button and delete flow
Relates to: https://github.com/xibosignage/xibo/issues/3532

Schedule Criteria: Fix wrong delete button and delete flow

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3534

Layout Editor: Elements don't rescale after saving

---

lib/Factory/ScheduleFactory.php
views/schedule-page.twig

- Schedule Grid: Fix for sort by criteria shows errors
Relates to: https://github.com/xibosignage/xibo/issues/3523

Schedule Grid: Fix for sort by criteria shows errors

---

ui/src/core/forms.js
ui/src/style/forms.scss
ui/src/style/variables.scss
ui/src/templates/forms/inputs/code.hbs

relates to xibosignageltd/xibo-private#829

Code Inputs: Expanded view

---

modules/layout-renderer.twig
package-lock.json
package.json
ui/bundle_preview.js

relates to xibosignage/xibo#3502

Layout Preview: Interactive Actions

---

lib/Entity/ModuleTemplate.php
lib/Factory/ModuleTemplateFactory.php
ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js
ui/src/style/common.scss
ui/src/templates/toolbar-card-item.hbs
ui/src/templates/toolbar-card-layout-template.hbs
ui/src/templates/toolbar-card-media-placeholder.hbs
ui/src/templates/toolbar-card-media-upload.hbs
ui/src/templates/toolbar-card-media.hbs
ui/src/templates/toolbar-card-playlist-new-template.hbs
ui/src/templates/toolbar-card-playlist-template.hbs
ui/src/templates/toolbar-card-stencil.hbs
ui/src/templates/toolbar-card-template.hbs
ui/src/templates/toolbar-card.hbs
ui/src/templates/toolbar-content-group.hbs
ui/src/templates/toolbar-content-submenu.hbs
ui/src/templates/toolbar-media-preview-info.hbs

relates to xibosignage/xibo#3542

Editor: module templates description and fix tooltips

---

modules/templates/global-elements.xml

relates to xibosignage/xibo#3522

Fix text wrap for text element

---

ui/src/editor-core/widget.js

relates to xibosignage/xibo#3515

Elements: Fix cast to int for number properties

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3518

Schedule: Validation time input trigger fix

---

modules/pdf.xml

relates to xibosignage/xibo#3470
- Use isEvalSupported to prevent vulnerability

Upgrade pdfjs-dist dependency

---

lib/Entity/ModuleTemplate.php
lib/Factory/ModuleTemplateFactory.php
ui/src/editor-core/toolbar.js
ui/src/layout-editor/main.js
ui/src/style/common.scss
ui/src/templates/toolbar-card-item.hbs
ui/src/templates/toolbar-card-layout-template.hbs
ui/src/templates/toolbar-card-media-placeholder.hbs
ui/src/templates/toolbar-card-media-upload.hbs
ui/src/templates/toolbar-card-media.hbs
ui/src/templates/toolbar-card-playlist-new-template.hbs
ui/src/templates/toolbar-card-playlist-template.hbs
ui/src/templates/toolbar-card-stencil.hbs
ui/src/templates/toolbar-card-template.hbs
ui/src/templates/toolbar-card.hbs
ui/src/templates/toolbar-content-group.hbs
ui/src/templates/toolbar-content-submenu.hbs
ui/src/templates/toolbar-media-preview-info.hbs

relates to xibosignageltd/xibo-private#851

Toolbox: Add description to module templates

---

views/authed.twig

relates to xibosignage/xibo#3541

Help control: Prevent content to be rendered when page loads

---

lib/Controller/Library.php
lib/Helper/XiboUploadHandler.php
ui/src/layout-editor/main.js
ui/src/templates/toolbar-card-media.hbs

relates to xibosignageltd/xibo-private#760

Image widget: Add with default ratio

---

lib/Controller/Library.php
lib/Controller/Playlist.php

- Image Playlist: Fixed image duration not updating
Relates to: https://github.com/xibosignage/xibo/issues/3544

Image Playlist: Fixed image duration not updating

---

lib/Controller/Folder.php

relates to xibosignage/xibo#3550

Editor Toolbar: Folder input filter fix

---

ui/src/editor-core/properties-panel.js
ui/src/editor-core/widget.js
ui/src/layout-editor/layout.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
views/layout-designer-page.twig

relates to xibosignageltd/xibo-private#873

Layout Editor: Decrease the number of back-end requests

---

Dockerfile
Dockerfile.ci
Dockerfile.dev
composer.json
db/migrations/20180131114002_old_upgrade_step121_migration.php
docker-compose.yml
docker/entrypoint.sh
docker/etc/apache2/sites-available/000-default.conf
lib/Helper/Environment.php
lib/Service/ConfigService.php
lib/Service/PlayerActionService.php
lib/Service/PlayerActionServiceInterface.php
lib/XMR/PlayerAction.php
lib/XTR/MaintenanceDailyTask.php
lib/Xmds/Soap5.php
tests/Helper/MockPlayerActionService.php
tests/Helper/NullPlayerActionService.php
views/display-page.twig
views/settings-page.twig

XMR: initial work for CMS->XMR communication over private API, remove ZMQ dependency.
xibosignageltd/xibo-private#880

Web Sockets XMR

---

.github/workflows/build-container.yaml

This PR should build a container for release41.

Build release41

---

ui/src/core/xibo-cms.js
views/dataset-form-add.twig
views/dataset-form-edit.twig
views/dataset-page.twig

relates to xibosignageltd/xibo-private#882

Dataset form: Validation broken for uri field

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3558

Schedule Add/Edit : Dates condition broken fix

---

lib/Entity/Schedule.php
ui/src/core/xibo-cms.js
views/forms.twig
views/inline.twig
views/schedule-form-add.twig
views/schedule-form-edit.twig

relates to xibosignage/xibo#3559

Schedule form: Limit numeric inputs to min/max

---

ui/src/core/xibo-calendar.js

relates to xibosignageltd/xibo-private#883

Schedule Page: Inline filter is broken

---

ui/src/pages/campaign/campaing-page.js

relates to xibosignageltd/xibo-private#888

Campaign Page: Strings with twig translation in JS

---

ui/src/core/xibo-cms.js

relates to xibosignageltd/xibo-private#885

Display page: Thumb modal fix

---

ui/src/core/xibo-datatables.js

relates to xibosignageltd/xibo-private#886

Grid pages: Broken folder filter toggle

---

ui/src/core/xibo-cms.js
ui/src/core/xibo-datatables.js

relates to xibosignageltd/xibo-private#890

Fix filter tag init and user search enter key refresh

---

modules/src/xibo-player.js

relates to xibosignageltd/xibo-private#892

Element group render position fix

---

modules/emergency-alert.xml

relates to xibosignageltd/xibo-private#897

Emergency Alert: Fix data cache key

---

db/migrations/20250115151900_add_xmr_ws_setting_migration.php

fixes xibosignageltd/xibo-private#903

XMR: add the new setting for WS address

---

views/display-page.twig

relates to xibosignageltd/xibo-private#898

Display: Player Type filter shows Chrome OS with a space

---

db/migrations/20250121120000_update_metric_column_limit_in_schedule_criteria.php

relates to xibosignageltd/xibo-private#900

Increase character limit for Schedule Criteria's type and metric

---

ui/src/style/layout-editor.scss

relates to xibosignage/xibo#3575

Editor: Change viewer default colour

---

lib/Widget/Render/WidgetHtmlRenderer.php
modules/src/xibo-player.js
package-lock.json
package.json

- fix data widget fetching and parsing
- bump XLR version

Fix: data widget fetching and parsing

---

views/display-page.twig

relates to xibosignageltd/xibo-private#895

Add translation to clientCode for Display page

---

ui/src/core/xibo-cms.js

relates to xibosignage/xibo#3543

Local select: allow searching for multi-word

---

ui/src/core/xibo-calendar.js
ui/src/core/xibo-cms.js

relates to xibosignage/xibo#3576

Schedule Agenda: Fixes for select and delete Events

---

ui/src/core/forms.js

relates to xibosignageltd/xibo-private#920

Assign Layouts: shows error in console

---

ui/src/editor-core/layer-manager.js
ui/src/editor-core/properties-panel.js
ui/src/layout-editor/viewer.js
ui/src/templates/layer-manager.hbs
views/editorTranslations.twig

relates to xibosignageltd/xibo-private#910

Bring group to view and layer manager warning

---

lib/Controller/DayPart.php
lib/Controller/Schedule.php
lib/Factory/DayPartFactory.php
views/daypart-form-add.twig
views/daypart-form-edit.twig
views/daypart-page.twig

relates to xibosignage/xibo#3568

Daypart: Unable to retire Dayparts

---

web/theme/default/css/xibo.css

relates to xibosignageltd/xibo-private#917

Fix datepicker for display override input

---

lib/Connector/CapConnector.php
lib/Connector/NationalWeatherServiceConnector.php

relates to xibosignage/xibo#3579

Metric matching error prevents Emergency Alert layouts from playing

---

ui/src/pages/display/display-page.js
views/display-page.twig

relates to xibosignage/xibo#3581

Display page: TeamViewer and Webkey links fix

---

ui/src/templates/schedule/reminder-event.hbs
ui/src/templates/schedule/schedule-criteria-fields.hbs
views/schedule-form-add.twig
views/schedule-form-edit.twig
web/theme/default/css/xibo.css

relates to xibosignageltd/xibo-private#928

Schedule Form: Reminder and Criteria input UI fix

---

views/template-page.twig

relates to xibosignageltd/xibo-private#924

Template page: Publish modal throws JS error

---

lib/Widget/Render/WidgetDataProviderCache.php
lib/Widget/Render/WidgetHtmlRenderer.php
lib/Xmds/Soap.php
lib/Xmds/Soap7.php
web/xmds.php

XMDS: ensure that the CDN URL is obeyed if present.

---

ui/src/core/xibo-calendar.js

relates to xibosignageltd/xibo-private#923

Schedule Layout: Error when saving form

---

ui/src/core/xibo-datatables.js

relates to xibosignage/xibo#3584

Grid multi edit tags fix

---

package-lock.json
package.json

relates to xibosignageltd/xibo-private#929

Video preview has no sound

---

views/command-form-add.twig
views/command-form-edit.twig

Commands: add ChromeOS to the list

---

lib/Connector/XiboSspConnector.php
lib/Controller/Connector.php

Connector: fix enable/disable/delete actions without breaking the interface

---

views/sessions-page.twig

relates to xibosignage/xibo#3592

Remove Event button from Sessions page

---

web/theme/default/css/xibo.css

relates to xibosignageltd/xibo-private#928

Fix for CSS removed from XiboCSS

---

views/playlist-page.twig

relates to xibosignage/xibo#3600

CKeditor missing in playlist view

---

views/xibo-ssp-connector-form-javascript.twig

- Refactored code to add fallback value
Relates to: https://github.com/xibosignage/xibo/issues/3612

Fixed Connectors: SSP Connector returns NaN on Summary Report

---

lib/Xmds/Soap4.php

XMDS: notify status should parse the same commercial licence values

---

lib/Controller/Tag.php
lib/Entity/Campaign.php

relates to xibosignage/xibo#3589

Multi-edit Ad campaigns: tags not saving after edit tags

---

ui/src/layout-editor/main.js

relates to xibosignageltd/xibo-private#940

Interactive Actions: Unable to set duration

---

ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3621

Actions: Next/Previous Layout shows regions as target

---

ui/src/editor-core/element.js

relates to xibosignageltd/xibo-private#933

Layout: It doesn't display the elements when visited

---

ui/src/core/xibo-cms.js
ui/src/core/xibo-datatables.js

relates to xibosignageltd/xibo-private#915

Schedule grid:  filter defined date on load fix

---

ui/src/editor-core/properties-panel.js
ui/src/layout-editor/main.js
ui/src/layout-editor/viewer.js
ui/src/style/layout-editor.scss
ui/src/templates/forms/region.hbs

relates to xibosignage/xibo#3613

Layout Editor: Form not saving for Widget options

---

modules/templates/event-static.xml

relates to xibosignage/xibo#3610

Calendar: Events overlapping in weekly static template

---

ui/src/editor-core/properties-panel.js

relates to xibosignage/xibo#3620

Layout Editor: Change Layout refreshes Topbar

---

lib/Controller/Widget.php
lib/Entity/ModulePropertyTrait.php

fixes xibosignageltd/xibo-private#938

Layout Editor: element properties should be validated

---

eslint.config.mjs
ui/src/helpers/form-helpers.js

relates to xibosignage/xibo#3623
- esLint updated to warn about assign to const

Playlist editor, choose media search bug

---

ui/src/templates/forms/position.hbs

relates to xibosignage/xibo#3625

Layout Editor: Change Playlist name not working

---

modules/templates/article-static.xml
modules/templates/dataset-static.xml
modules/templates/event-static.xml
modules/templates/forecast-static.xml
modules/templates/social-media-static.xml
modules/templates/stock-static.xml
modules/text.xml

relates to xibosignage/xibo#3597

Optional Javascript input field: Add help text to not use array style syntax

---

views/schedule-form-sync-add.twig
views/schedule-form-sync-edit.twig

relates to xibosignage/xibo#3602

Synchronized Event: Negative Values in the numeric fields should not be valid 

---

lib/Controller/Campaign.php
lib/Factory/CampaignFactory.php
ui/src/pages/schedule/schedule-page.js

relates to xibosignageltd/xibo-private#941

Schedule Filter: Video event layouts appearing in layout filter

---

lib/Controller/Folder.php
lib/Factory/FolderFactory.php

relates to xibosignage/xibo#3630

Delete Folder: delete fails after adding a sync group

---

ui/src/templates/forms/region.hbs

relates to xibosignage/xibo#3613

Layout Editor: Playlist position not saving

---

views/licence.twig

- Spelling fix on About window
Relates to: https://github.com/xibosignageltd/xibo-private/issues/948

Fixed wrong spelling in a specific text in About window

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3636

Add Event Pre-Populates All Displays

---

lib/Controller/Campaign.php
lib/Entity/Campaign.php

relates to xibosignage/xibo#3647

Campaign Grid: Modified By column is empty

---

lib/Controller/Tag.php
lib/Event/TagEditEvent.php
lib/Listener/DisplayGroupListener.php
lib/Middleware/ListenersMiddleware.php

relates to xibosignage/xibo#3631

Tag: Editing tag name does not reflect in criteria tag in display group

---

ui/src/core/xibo-cms.js

relates to xibosignage/xibo#3660

Scheduling Playlist UI: Resolution drop-down is below form

---

ui/src/templates/schedule/fullscreen-schedule.hbs

relates to xibosignage/xibo#3666

Schedule Form: Playlist and Resolution have the same help text

---

ui/src/core/xibo-calendar.js

relates to xibosignage/xibo#3658

Schedule Criteria: Edit form fails to populate the custom metric field

---

modules/templates/product-elements.xml

relates to xibosignage/xibo#3634

Menu Board: Option Value is duplicated when in use

---

ui/src/editor-core/properties-panel.js

relates to xibosignageltd/xibo-private#947

Editor: Add 2nd playlist with slower network error

---

ui/src/core/file-upload.js
ui/src/core/xibo-datatables.js
views/template-page.twig

relates to xibosignage/xibo#3638

Folder tree missing text

---

ui/src/layout-editor/layout.js

relates to xibosignage/xibo#3657

Template: Cannot add zone after checking out

---

ui/src/templates/forms/region.hbs

relates to xibosignage/xibo#3656

Template: Zones not saving when moved

---

views/displayprofile-form-edit-soc.twig

relates to xibosignage/xibo#3653

Key lock options are duplicated

---

ui/src/core/forms.js
views/displayprofile-form-edit-javascript.twig

relates to xibosignage/xibo#3652

Reposition Error message for Android dimensions

---

ui/src/playlist-editor/main.js

relates to xibosignage/xibo#3673

Playlist Editor: Multi select context menu not working properly

---

ui/src/layout-editor/viewer.js

relates to xibosignage/xibo#3670

Text Element: Line breaks in text elements fix

---

lib/XTR/AuditLogArchiveTask.php
tasks/auditlog-archiver.task

XTR: fix the audit log archive task so that it does not do an unbounded delete

---

views/layout-page.twig

relates to xibosignage/xibo#3677

Layout Page: Clear filters set "Retired" to No

---

lib/Controller/Applications.php
lib/routes-web.php
lib/routes.php

relates to xibosignageltd/xibo-private#962

Applications: unable to revoke access via the API

---

lib/Controller/Playlist.php
views/playlist-form-timeline.twig

relates to xibosignage/xibo#3674

Playlist Editor: Timezone dropdown not working

---

lib/Controller/User.php
lib/Entity/User.php
lib/Entity/UserNotification.php
lib/Factory/UserGroupFactory.php
lib/XTR/EmailNotificationsTask.php
views/user-form-edit.twig
views/usergroup-form-edit.twig

Notifications: present notification settings in a clearer way on user and user group. Fix the issue sending email only to the users group settings

---

modules/templates/product-elements.xml

relates to xibosignage/xibo#3634

Menu Board: Option name is duplicated
