xibosignage/xibo-cms

theme/default/css/dashboard.css
See: https://github.com/xibosignage/xibo/issues/184
=> Reduce menu items height

theme/default/css/dashboard.css
Reverts xibosignage/xibo-cms#23
=> Revert "Reduce menu items height"

theme/default/css/xibo.css
Made the CSS change for issue #181
=> Changed xibo.css for issue #181

theme/default/html/layout_designer.php
https://github.com/xibosignage/xibo/issues/174
=> Update layout_designer.php, changed col-md1 to col-md-2 to fix issue #174

install/database/86.sql, install/master/data.sql, lib/modules/module.class.php, locale/dbtranslate.php
Will resolve https://github.com/xibosignage/xibo/issues/201
=> Set Default statue of Delete Old Version Media option.

modules/theme/ticker/media-rss-with-left-hand-text.template.json, modules/theme/ticker/media-rss-with-title.template.json, modules/theme/ticker/prominent-title-with-desc-and-name-separator.template.json, theme/default/js/xibo-forms.js
Issue https://github.com/xibosignage/xibo/issues/262
I found a better way to fix this problem (and keep most of your code as it is).
Now everything should work. I've tested it with text and ticker fields.
I added also some `#Color#` tags in three ticker templates. Now the color should automatically change to the complementary color.
=> Issue262 source view leads to color change v2

theme/default/html/header.php
this would be the correct way? ..
=> Getting Sidebar

theme/default/css/xibo.css
also it seems that the css class page-header is not used any longer, but not sure about that
=> Added pointer cursor to preview navigation buttons

modules/ticker.module.php
Please test/review.
If there is no image attached to the feed as media enclosure, this patch takes the first image from content (if not found from description) of an rss item.
=> Ticker image from content

modules/text-form-add.twig, modules/ticker-form-edit.twig, modules/webpage-form-add.twig, modules/webpage-form-edit.twig, views/dataset-form-add.twig, views/dataset-form-delete.twig, views/dataset-form-edit.twig
really small fixes to few modules and views.
=> Last(?) small bunch of fixes

views/dataset-column-form-add.twig, views/dataset-column-form-edit.twig
dataSetColumnAddForm - done
dataSetColumnEditForm - done
=> Fixes dataSetColumnForms

web/theme/default/js/xibo-layout-designer.js
xibosignage/xibo#709
Should be applicable to 1.7 series too.
=> Refresh designer preview after reordering timeline item.

composer.lock, lib/Controller/DataSetColumn.php, lib/Controller/Display.php, lib/Entity/Display.php, lib/Entity/Layout.php, lib/routes.php, tests/integration/DataSetTest.php, tests/integration/DisplayTest.php, tests/integration/ScheduleTest.php, views/display-form-wakeonlan.twig
=> Test Suite Fixes

lib/Twig/DateFormatTwigExtension.php, views/campaign-preview.twig, web/index.php
See - https://community.xibo.org.uk/t/campaign-preview/6110 for feature description.
=> format date with a twig extension

README.md, lib/Service/ConfigService.php
=> Extract user theme data into its own custom folder.

lib/Controller/Template.php, lib/Entity/Layout.php, lib/Entity/Schedule.php, lib/Factory/LayoutFactory.php, lib/Middleware/State.php, lib/Service/ConfigService.php, lib/Xmds/Soap.php, modules/datasetview-designer-javascript.twig, views/region-form-timeline.twig, web/theme/default/js/xibo-calendar.js, web/theme/default/js/xibo-forms.js, web/theme/default/js/xibo-layout-designer.js
=> Feature/release 1.8.1

lib/Widget/ModuleWidget.php, lib/Widget/Ticker.php, modules/ticker-form-edit.twig, web/modules/xibo-text-render.js
=> Randomise ticker

modules/forecastio-form-add.twig, modules/forecastio-form-edit.twig, modules/googletraffic-form-add.twig, modules/googletraffic-form-edit.twig
=> Fixed wording in google traffic and weather widgets

install/steps/135.json, lib/Controller/Layout.php, lib/Entity/DataSet.php, lib/Entity/Layout.php, lib/Factory/DataSetFactory.php, lib/Middleware/State.php, lib/Service/ConfigService.php, lib/Service/ConfigServiceInterface.php, lib/XTR/RemoteDataSetFetchTask.php, lib/Xmds/Soap.php
Final changes to prepare this branch for testing.
https://github.com/xibosignage/xibo/issues/1320
=> Ready for testing

Dockerfile, Dockerfile.dev, docker/entrypoint.sh, docker/etc/cron.d/anacron, docker/etc/periodic/15min/cms-db-backup
Fixes https://github.com/xibosignage/xibo/issues/1387
=> Replace anacron with custom script to manage backups.

lib/Controller/Settings.php
=> Remove pool drop from settings save

docker/etc/apache2/conf.d/cms.conf
https://github.com/xibosignage/xibo/issues/1403
=> Turn keepalive off in Apache as this can cause issues with Players

composer.json, composer.lock
=> Switch to PHP7 compatible branch of onelogin/php-saml

.dockerignore, .gitignore, Dockerfile, Dockerfile.cypress, cypress.json, cypress/integration/dashboard_spec.js, cypress/integration/layout_designer_spec.js, cypress/integration/login_spec.js, cypress/integration/modules_spec.js, cypress/integration/unauthed_spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, docker/etc/apache2/conf.d/cms.conf, lib/Helper/Environment.php, lib/Middleware/Actions.php, lib/Middleware/CsrfGuard.php, lib/Service/LogServiceInterface.php, package-lock.json, package.json
=> Cypress for Front End Testing

lib/Widget/ModuleWidget.php
=> Better regex for replacing width/height/scale_override in the preview

lib/Controller/Schedule.php, lib/Middleware/SAMLAuthentication.php, views/schedule-form-add.twig, views/schedule-form-edit.twig
Hotfix for critical issues found post release.
=> 1.8.10-hotfix

ui/src/css/designer.less, ui/src/css/playlist-editor.less, ui/src/css/toolbar.less, ui/src/designer/viewer.js, ui/src/designer/widget.js, ui/src/templates/designer.hbs, ui/src/templates/playlist-timeline-widget.hbs, ui/src/templates/properties-panel.hbs, ui/src/templates/timeline-ghost-widget.hbs, ui/src/templates/timeline-widget.hbs, ui/src/templates/timeline.hbs, views/authed.twig, views/layout-form-background.twig
- Style updated
- Widgets name added to timeline
- Layout Background image upload form style fix
=> Layout Designer Improvements: CSS style revamp

composer.json, composer.lock, lib/Factory/BandwidthFactory.php, lib/Factory/MediaFactory.php, lib/Service/DisplayNotifyService.php, lib/Widget/Chart.php, lib/Widget/DataSetView.php, lib/Widget/ForecastIo.php, lib/Widget/GoogleTraffic.php, lib/Widget/ModuleInterface.php, lib/Widget/ModuleWidget.php, lib/Widget/NotificationView.php, lib/Widget/Ticker.php, lib/Widget/Twitter.php, lib/Widget/TwitterMetro.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, web/xmds.php
Performance turning for Widget Sync and Notify.
=> 1.8.12 pack4

cypress.json
=> Cypress viewport dimensions configuration

lib/Controller/DataSetData.php, lib/Controller/Settings.php, lib/Entity/Widget.php, lib/Helper/XiboUploadHandler.php, lib/Service/ConfigService.php, lib/Widget/AlphaVantageBase.php, lib/Widget/Pdf.php, lib/Widget/Ticker.php, modules/ticker-form-edit.twig, modules/xibo-text-render.js, views/dataset-data-form-add.twig, views/dataset-data-form-edit.twig, views/display-form-request-screenshot.twig, views/display-page.twig, views/schedule-form-add.twig, views/schedule-form-edit.twig, views/schedule-form-now.twig, views/settings-page.twig
Pack of changes ported from release18
Fixes for Auto_Auth setting
=> Swift 2.0.0 beta

db/migrations/20190213162212_add_horizontal_menu_setting_migration.php, lib/Controller/Settings.php, lib/Controller/User.php, lib/Entity/User.php, lib/Entity/UserOption.php, lib/routes-web.php, lib/routes.php, phpunit.xml, ui/src/css/toolbar.less, views/authed-notification-drawer.twig, views/authed-topbar.twig, views/authed-user-menu.twig, views/authed.twig, views/settings-page.twig, views/user-form-preferences.twig, web/theme/compact/css/dashboard.css, web/theme/default/css/dashboard.css, web/theme/default/css/xibo.css
xibosignage/xibo#1737
xibosignage/xibo#1738
=> Horizontal navigation menu, including user preferences

composer.json, lib/Controller/Login.php, lib/Middleware/CASAuthentication.php, lib/Service/ConfigService.php, views/login.twig
Code is based on the SAMLAuthentication Middleware
=> New Feature: Use CAS only, to authenticate users.

db/migrations/20180130073838_install_migration.php, lib/Xmds/Soap4.php
Log status dialog to ALERT level
Fix install on cluster
=> Tweaks ahead of beta.3/rc1

lib/Helper/Environment.php, lib/Widget/SubPlaylist.php, lib/Xmds/Soap5.php, modules/subplaylist-designer-javascript.twig, modules/subplaylist-form-edit.twig, ui/src/templates/form-helpers-sub-playlist-form.hbs, views/settings-page.twig
Sub Playlist work and some tweaks
=> 2.0.2-pack3

lib/Entity/EntityTrait.php, lib/Entity/Media.php, lib/Entity/Playlist.php, lib/Entity/Widget.php, lib/Widget/SubPlaylist.php
=> Handle empty lists being used for Spot fill.

lib/XTR/StatsArchiveTask.php, lib/Xmds/Soap4.php, lib/Xmds/Soap5.php
=> Fix for duplicate displayIds

lib/XTR/StatsArchiveTask.php
=> Export stats without buffering to save memory.

views/schedule-page.twig
Relates to xibosignage/xibo#1916
=> OSX-832 Campaigns dropdown close button upgrade

lib/Widget/SubPlaylist.php
=> Do not save inside sub playlists recursive function.

cypress/integration/layout_designer_spec.js, ui/src/preview/html-preview.js
xibosignage/xibo#1940
- Video scale type also implemented
=> OSX-818 Video Widget: Full Screen preview

lib/Xmds/Soap.php
Download layout resources before downloading layout to fix bug where expired layout was using old resources.
=> Change required file download order

lib/Entity/Layout.php
=> Rework the way we set Minimum duration on Widgets.

lib/Helper/Environment.php, lib/Widget/SubPlaylist.php
Bump min PHP version
Fix initial values in Subplaylist for spots and spotLength
=> Olbers 2.2.1

README.md, lib/Helper/Environment.php, views/licence.twig
Update version
Update copyright year (yes to 2019!)
Update readme with new branches
=> Prepare 2.2.1 release

composer.json, composer.lock, lib/Helper/Environment.php
Add temporary symfony/http-foundation requirement to fix CVE
=> Update PHP min version to 7.0.8

lib/Entity/Media.php, lib/Xmds/Soap.php
xibosignage/xibo#2049
xibosignage/xibo#2051
=> Bugfix xibosignage/xibo#2049

lib/Controller/PlaylistDashboard.php, lib/routes-web.php, ui/src/core/xibo-cms.js, views/playlist-dashboard-spots.twig, views/playlist-dashboard.twig, views/schedule-form-edit.twig
=> Update Playlist Dashboard to show one Playlist at a time

lib/Entity/Layout.php, lib/Factory/LayoutFactory.php, lib/Helper/Environment.php, lib/XTR/LayoutConvertTask.php
=> Layout conversion task to only select schemaVersions < 2.

lib/Controller/Library.php
S3 URLs support in add media via URL
=> Wolf 2.3.0 alpha

lib/Controller/Library.php
=> Add support for S3 URLs to add media by URL

Dockerfile
=> alpine3.11, fix mongo ssl error

.github/workflows/test-suite.yaml, Dockerfile, Dockerfile.ci, Dockerfile.dev, README.md
=> Use actions for test suite, fix npm install build error

lib/Controller/Stats.php, lib/Storage/MongoDbTimeSeriesStore.php, lib/Storage/MySqlTimeSeriesStore.php, lib/Storage/TimeSeriesMongoDbResults.php, lib/Storage/TimeSeriesMySQLResults.php, lib/Storage/TimeSeriesResultsInterface.php, lib/XTR/ReportScheduleTask.php, lib/Xmds/Soap.php
Pagination support in stat search
Search by >= statDate
Search by > statId
=> Updated api/stats

.github/workflows/build-container.yaml
I forgot to add the build containers workflow to the release
=> release: add build container workflow

lib/Controller/Stats.php, lib/Xmds/Soap.php
=> Engagement in Proof of Play Export 

db/migrations/20200130165443_countdown_module_add_migration.php
Add in the Countdown Module as a core module which we install automatically on upgrade/install.
=> Release 2.3.0-beta - Add migration for Countdown Module.

README.md, lib/Middleware/ApiAuthorizationOAuth.php, lib/Middleware/State.php, package-lock.json, web/api/authorize/index.php, web/api/index.php, web/index.php, web/maint/index.php
Added some readme for how to generate API keys for dev
=> Fixes for setRootUri and setBasePath.

ui/src/core/xibo-calendar.js, views/schedule-page.twig
resolves xibosignage/xibo#1961
=> Schedule Page: Implement paging on the Agenda view table

lib/Entity/Schedule.php, tests/integration/ScheduleDayPartTest.php
=> Fix event 0 duration when DayPart start/end time are the same

lib/Widget/ForecastIo.php, modules/forecastio-tab-exporttemplate.twig, ui/src/core/toolbar.js, ui/src/core/xibo-calendar.js, ui/src/designer/main.js, views/schedule-page.twig, views/user-welcome.twig
xibosignage/xibo#2090
xibosignage/xibo#1961
xibosignage/xibo#2113
xibosignage/xibo#2112
=> Cherry pick from 2.2/2.3 issues

modules/clock-get-resource-flip.twig
=> Flip Clock type in Clock Widget issues with an Offset + or - specified

modules/countdown-form-edit.twig
=> Countdown module/widget advanced editor and helptext fix

bin/run.php, lib/Controller/Error.php, lib/Controller/Layout.php, lib/Entity/Display.php, lib/Factory/ContainerFactory.php, lib/Helper/DatabaseLogHandler.php, lib/Middleware/ApiAuthenticationOAuth.php, lib/Middleware/ApiAuthorizationOAuth.php, lib/Middleware/State.php, lib/Xmds/LogProcessor.php, lib/routes-web.php, web/api/authorize/index.php, web/api/index.php, web/index.php, web/maint/index.php, web/xmds.php
- Fixed session issues, we set the entry point name on the container now.
- Fixed(?) ErrorHandler - need more tests in normal usage.
- Fixed log levels.
=> Session, ErrorHandler and log Fixes

cypress/integration/playlist_editor_populated_spec.js
fixes xibosignage/xibo#2124
- Fix broken test
=> Refactor and reenable Cypress tests for the layout designer

views/dashboard-status-page.twig, views/display-page.twig, views/layout-page.twig, views/library-page.twig, views/playlist-page.twig, views/report-schedule-page.twig, views/task-page.twig, views/user-page.twig
This avoid issue with French translations in html title attribute. (Specially in display-page.twig)
I also try to change it for all class attribute.
Exception for class inside data- attribute.
=> Fix single quote/double quotes issue

lib/Controller/Stats.php
=> Stats timezone output

lib/Weather/OpenWeatherMapProvider.php
Small enhancement for trying to guess the units of "auto" option.
Fix for wind bearing not being in response if no wind.
=> Small weather fixes

db/migrations/20200427085958_add_report_schedule_start_end_migration.php, lib/Controller/Report.php, lib/Entity/ReportSchedule.php, lib/Factory/ReportScheduleFactory.php, lib/XTR/ReportScheduleTask.php, reports/distribution-schedule-form-add.twig, reports/proofofplay-schedule-form-add.twig, reports/summary-report-schedule-form-add.twig, views/report-schedule-page.twig, views/reportschedule-form-edit.twig
Add start/end date for report schedule xibosignage/xibo#2183
=> Feature: Report Schedule

modules/datasetticker-designer-javascript.twig
=> Colour Picker not appearing for Dataset Ticker Widget

lib/Controller/Schedule.php, package-lock.json, package.json, ui/bundle_vendor.js, ui/src/core/xibo-calendar.js, views/schedule-page.twig, web/theme/default/css/calendar.css
resolves xibosignage/xibo#2198
=> Schedule Agenda: Geo-Filter

ui/src/core/xibo-calendar.js
fixes xibosignage/xibo#2198
- Geo-Filter only events with geo location
=> Schedule Agenda: Geo-Filter fix

lib/Controller/AuditLog.php, lib/Controller/DayPart.php, lib/Controller/Fault.php, lib/Controller/Layout.php, lib/Controller/Maintenance.php, lib/Controller/Notification.php, lib/Controller/Report.php, lib/Controller/Stats.php, lib/Factory/AuditLogFactory.php, lib/Helper/SendFile.php, lib/Middleware/Handlers.php, lib/Widget/ModuleWidget.php, tests/integration/StatisticsTest.php
Fix sendfile on all requests (provide helper to output necessary headers for each download mode).
Fix error handler for XHR (do not redirect XHR requests as it makes it really hard to debug)
=> Sendfile and Error Handler

ui/src/designer/main.js, ui/src/playlist-editor/main.js, ui/src/style/common.scss, ui/src/style/designer.scss, ui/src/style/mixins.scss, ui/src/style/playlist-editor.scss, ui/src/style/toolbar.scss, ui/src/style/topbar.scss, ui/src/style/variables.scss, views/layout-designer-page.twig
=> Refactor SASS structure

ui/src/playlist-editor/main.js
=> Playlist Editor: Delete multiple failing with > 4 requests

docker/etc/apache2/conf.d/cms.conf
=> Disable Apache TRACK/TRACE. 

lib/Widget/ShellCommand.php, modules/shellcommand-designer-javascript.twig, modules/shellcommand-form-edit.twig, ui/src/core/xibo-cms.js, views/authed.twig, views/command-form-add.twig, views/command-form-edit.twig, views/displayprofile-form-edit-command-fields.twig, web/theme/default/css/xibo.css
resolves xibosignage/xibo#2247
=> Commands: Improve the UI for creating commands

ui/src/designer/viewer.js, views/region-designer-javascript.twig
=> Layout Designer: Handle some JS errors regarding undefined objects

lib/XTR/StatsMigrationTask.php
Stat Migration Task: Watermark Issue
=> Bugfix2.3.6

lib/Entity/Tag.php, lib/Factory/TagFactory.php, ui/src/core/xibo-forms.js, views/campaign-form-add.twig, views/campaign-form-edit.twig, views/display-form-edit.twig, views/displaygroup-form-add.twig, views/displaygroup-form-edit.twig, views/layout-form-add.twig, views/layout-form-edit.twig, views/library-form-edit.twig, views/playlist-form-add.twig, views/playlist-form-edit.twig, views/template-form-add-from-layout.twig
With this the tag with value can be assigned either by:
1) `tag|value` format
Depending if values were pre defined on the tag creation then either:
2) pick one of the pre defined values from a dropdown
or
3) input tag value in input field (confirm with enter or focus out)
If we are assigning a new Tag we can create it with value with 1) or 3) option.
=> Tag input changes

lib/Entity/Tag.php, lib/Factory/TagFactory.php, ui/src/core/xibo-forms.js, views/campaign-form-add.twig, views/campaign-form-edit.twig, views/display-form-edit.twig, views/displaygroup-form-add.twig, views/displaygroup-form-edit.twig, views/layout-form-add.twig, views/layout-form-edit.twig, views/library-form-edit.twig, views/playlist-form-add.twig, views/playlist-form-edit.twig, views/template-form-add-from-layout.twig
=> Cherry pick from 2.3.6 into 3.0.0-beta

lib/Controller/Preview.php, modules/layout-preview.twig, ui/src/preview/html-preview.css, ui/src/preview/html-preview.js, views/campaign-preview.twig
resolves xibosignage/xibo#2283
=> v3: Layout Preview, basic interactivity?

views/user-welcome.twig
=> Tour: Multiple fixes

web/theme/default/css/calendar.css
=> Some repeat Event schedules do not fit the day view calendar

lib/Controller/Tag.php, lib/routes.php, ui/src/core/xibo-cms.js, views/authed.twig, views/base.twig, views/campaign-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/inline.twig, views/layout-page.twig, views/library-page.twig, views/playlist-page.twig, views/template-page.twig, web/theme/default/css/calendar.css, web/theme/default/css/xibo.css
resolves xibosignage/xibo#2212
=> Tags: Bulk tagging using multi-select

lib/Controller/Campaign.php, lib/Controller/Command.php, lib/Controller/DataSet.php, lib/Controller/DayPart.php, lib/Controller/Display.php, lib/Controller/DisplayGroup.php, lib/Controller/Layout.php, lib/Controller/Library.php, lib/Controller/Notification.php, lib/Controller/PlayerSoftware.php, lib/Controller/Playlist.php, lib/Controller/Report.php, lib/Controller/Tag.php, lib/Controller/Template.php, lib/Controller/User.php, lib/routes-web.php, lib/routes.php, ui/src/core/xibo-cms.js, ui/src/core/xibo-forms.js, ui/src/style/designer.scss, views/authed.twig, views/base.twig, views/user-form-multiple-permissions.twig
resolves xibosignage/xibo#2217
=> Permissions: Bulk set for selected items

ui/src/core/xibo-cms.js
=> Auto submit on some dialogs fix

views/user-form-multiple-permissions.twig
=> Permissions Bulk Edit: help text fix

lib/Widget/Calendar.php, lib/Widget/Chart.php, lib/Widget/Clock.php, lib/Widget/Countdown.php, lib/Widget/Currencies.php, lib/Widget/DataSetTicker.php, lib/Widget/DataSetView.php, lib/Widget/Embedded.php, lib/Widget/ForecastIo.php, lib/Widget/GoogleTraffic.php, lib/Widget/Hls.php, lib/Widget/ModuleWidget.php, lib/Widget/NotificationView.php, lib/Widget/Pdf.php, lib/Widget/Stocks.php, lib/Widget/Text.php, lib/Widget/Ticker.php, lib/Widget/Twitter.php, lib/Widget/TwitterMetro.php, lib/Widget/Weather.php, lib/Widget/WebPage.php, lib/Widget/WorldClock.php, modules/xibo-interactive-control.js, ui/src/designer/main.js, ui/src/preview/html-preview.js
resolves xibosignage/xibo#2340
- Include new Xibo IC library
- Add the library to the modules
- Create a call to the layout designer viewer to enable trigger actions
=> Widget Interactive JavaScript

lib/Controller/Module.php, lib/Widget/Calendar.php, lib/Widget/Chart.php, lib/Widget/Clock.php, lib/Widget/Countdown.php, lib/Widget/Currencies.php, lib/Widget/DataSetTicker.php, lib/Widget/DataSetView.php, lib/Widget/Embedded.php, lib/Widget/ForecastIo.php, lib/Widget/GoogleTraffic.php, lib/Widget/Hls.php, lib/Widget/NotificationView.php, lib/Widget/Pdf.php, lib/Widget/Stocks.php, lib/Widget/Text.php, lib/Widget/Ticker.php, lib/Widget/Twitter.php, lib/Widget/TwitterMetro.php, lib/Widget/Weather.php, lib/Widget/WebPage.php, lib/Widget/WorldClock.php, modules/get-resource-pdf.twig, modules/pdf-form-edit.twig, modules/xibo-interactive-control.js, ui/src/designer/main.js, ui/src/preview/html-preview.js
resolves xibosignage/xibo#944
relates to xibosignage/xibo#2340
- durationPerItem added to pdf module
- getResource for module type changed to renderAs
- Layout preview setDuration action added
- xibo-interactive-control updated
- widget id added to the xiboIC on all modules
=> Improve PDF module with duration per page

lib/Widget/Calendar.php, lib/Widget/Countdown.php, lib/Widget/Currencies.php, lib/Widget/DataSetTicker.php, lib/Widget/DataSetView.php, lib/Widget/Hls.php, lib/Widget/NotificationView.php, lib/Widget/Stocks.php, lib/Widget/Text.php, lib/Widget/Ticker.php, lib/Widget/Twitter.php, lib/Widget/TwitterMetro.php, lib/Widget/WorldClock.php
=> Widget Interactive JavaScript - Module Fix

lib/Controller/Module.php
fixes xibosignage/xibo#2340
- getResource in Module reverted and a new condition for renderAs added
=> Widget Interactive JavaScript - Module final fix

lib/Widget/Calendar.php, modules/calendar-form-edit.twig, modules/xibo-interactive-control.js, ui/src/preview/html-preview.js
resolves xibosignage/xibo#2208
=> Widget: Calendar to trigger Actions via web hook

lib/Factory/UserGroupFactory.php, views/usergroup-form-acl.twig
=> Reword various features based on feedback 

ui/src/core/xibo-cms.js, views/campaign-form-selectfolder.twig, views/displaygroup-form-selectfolder.twig, views/library-form-selectfolder.twig, views/playlist-form-selectfolder.twig
- Alpha sort folder tree
- All grids share the same saved folder tree state
- Select folder forms have folder tree appear in the form body instead of additional modal
=> Small enhancements to Folders

package-lock.json, views/user-welcome.twig
=> Tutorial will not proceed if steps not followed exactly.

views/user-welcome.twig
=> Tutorial fix: Remove log messages

ui/src/core/file-upload.js, views/common.twig, views/include-file-upload.twig
resolves xibosignage/xibo#2353
=> Start and End times enhancements - v3

lib/Controller/DisplayProfileConfigFields.php, lib/Entity/DisplayProfile.php, lib/Entity/Layout.php, lib/Helper/Environment.php, lib/Widget/DataSetTicker.php, lib/XTR/DynamicPlaylistSyncTask.php, modules/datasetticker-form-edit.twig, tests/integration/Widget/VideoWidgetTest.php, views/displayprofile-form-edit-windows.twig
Add Randomise option to DataSet Ticker. xibosignage/xibo#2209
=> Final tweaks to 2.3.8

.github/workflows/build-container.yaml, cypress/integration/dashboard_spec.js, cypress/integration/layout_designer_empty_spec.js, lib/Factory/DataSetFactory.php, lib/Xmds/Soap.php
Including CI: new way to deploy test builds
=> 2.3.9 work in progress

package-lock.json, ui/src/style/designer.scss, ui/src/style/topbar.scss, views/authed.twig, views/display-page-manage.twig, web/theme/default/css/xibo.css
resolves xibosignage/xibo#2361
- Display manage chart growing fix
- Layout designer topbar fix for hor navbar
=> Upgrade Bootstrap more fixes

package-lock.json, package.json, ui/bundle_style.js, ui/bundle_vendor.js, ui/bundle_xibo.js, ui/src/core/tour.js, ui/src/style/tour.scss, views/base.twig, views/user-welcome.twig, views/welcome-page.twig, webpack.config.js
resolves xibosignage/xibo#2398
=> Xibo Javascript tour library

lib/Middleware/Handlers.php, ui/src/core/xibo-cms.js, views/user-page.twig
Folders: Fix Sharing form.
User Page: Fix toast error.
Core: 404 over XHR should return JSON
=> Misc fixes

ui/src/core/file-upload.js, ui/src/core/xibo-cms.js, ui/src/designer/drawer.js, ui/src/helpers/form-helpers.js, ui/src/style/designer.scss, ui/src/style/playlist-editor.scss, ui/src/style/toolbar.scss, ui/src/templates/drawer-widget.hbs, ui/src/templates/drawer.hbs, ui/src/templates/timeline-widget.hbs, views/action-designer-javascript.twig, views/action-form-delete.twig, views/authed.twig, views/dataset-dataentry-page.twig, views/dataset-page.twig, views/include-file-upload.twig, views/layout-designer-page.twig, views/layout-page.twig, views/template-form-add-from-layout.twig, views/template-page.twig, web/theme/compact/css/dashboard.css, web/theme/default/css/dashboard.css
fixes xibosignage/xibo#2361
- Add form folder breadcrumb default fix
- Dataset data entry page: change edit/multi mode logic
- Actions add/delete data reload
- Drawer widgets with action icon
- flatpickr: fix locale for en-gb
- Firefox toolbar colour fix
- Drawer widget tooltip fix
- Prevent add to drawer if closed
- Layout designer main container height fix
- Side bar text fix
- Property Panel buttons order and margin fix
- Upload form table fix
- Android intent name/intent field added
=> Upgrade Bootstrap fixes

lib/Factory/LayoutFactory.php, lib/Storage/ApiClientStorage.php
=> XMDS: Correctly match layout table through layouthistory via campaignId

.eslintrc.js, .prettierrc, package-lock.json, package.json, ui/src/core/xibo-cms.js, views/authed.twig, web/theme/default/css/xibo.css
resolves xibosignage/xibo#2248
=> Commands: HTTP helper

lib/Controller/Campaign.php, lib/Controller/Display.php, lib/Controller/DisplayGroup.php, lib/Controller/Layout.php, lib/Controller/Library.php, lib/Controller/Playlist.php, lib/Factory/CampaignFactory.php, lib/Factory/MediaFactory.php, lib/Factory/PlaylistFactory.php, ui/src/core/xibo-cms.js, views/campaign-page.twig, views/display-page.twig, views/library-page.twig, views/playlist-page.twig
Fixes filtering on Campaign page from localStorage (and now url too)
Couple of other smaller fixes
=> Implements 4 new jump links with handling

modules/clock-designer-javascript.twig
=> Clock Widget: Analogue/Digital switch broken

.github/workflows/test-suite.yaml, cypress/integration/playlist_editor_populated_spec.js, docker-compose.yml, lib/Controller/Display.php, lib/Controller/Schedule.php, lib/Controller/Settings.php, lib/Entity/SavedReport.php, lib/Helper/Random.php, tests/integration/LayoutTest.php, views/auditlog-page.twig, views/reportschedule-form-edit.twig
MySQL update to 5.7 and related fixes - xibosignage/xibo#2469
=> Wolf 2.3.10

.eslintrc.js, modules/xibo-layout-scaler.js, package-lock.json, package.json
=> Xibo Layout Scaler wrong dimensions on Android

lib/Widget/WorldClock.php
=> World Clock elements misplaced on Linux Player

lib/Controller/Folder.php, views/campaign-page.twig, views/dataset-page.twig, views/display-page.twig, views/displaygroup-page.twig, views/layout-page.twig, views/library-page.twig, views/playlist-page.twig, views/template-page.twig
Global Search -> All Folders
/ -> Root Folder
=> Folders : Rename Global Search and Root Folder

ui/src/preview/html-preview.js
=> Layout Preview renders widgets in wrong regions

lib/Widget/ModuleWidget.php, views/forms.twig, views/inline.twig, views/user-welcome.twig
=> Editor Tour multiple fixes

lib/Storage/MongoDbTimeSeriesStore.php, lib/XTR/StatsMigrationTask.php
=> BugFix-2.3.11

ui/src/preview/html-preview.js
=> Player preview transition broken

views/display-page.twig
=> Fix Android Display Profile Settings for Dimensions

lib/Widget/DataSetView.php
allow colorPicker values  to be applied with overrideTemplate and basic template
=> DataSetView : post upgrade fix

views/authed.twig
=> Top-bar and user menu disappearing

lib/Entity/Layout.php
xibosignage/xibo#2567 (cherry picked from commit dba68afb0c5919610236698914ea6525fb678d1c)
=> Fix regression with layout publishing

views/campaign-preview.twig
resolves xibosignage/xibo#2597
=> Campaign preview: Embed new tab preview link broken

views/region-form-edit.twig
=> Layout Editor: Region set full screen dimensions button needs highlighting

ui/src/preview/html-preview.js
=> Layout Editor Preview: Broken video playback

lib/Controller/Display.php, lib/Controller/Login.php, lib/Controller/User.php, lib/Entity/Layout.php, lib/Entity/Playlist.php, lib/Entity/Region.php, lib/Factory/LayoutFactory.php, lib/Factory/UserGroupFactory.php, lib/Factory/UserNotificationFactory.php, lib/Widget/Twitter.php, lib/Widget/TwitterMetro.php, lib/XTR/MaintenanceDailyTask.php, lib/XTR/MaintenanceRegularTask.php
=> Wolf 2.3.13

views/display-page.twig
relates to xibosignage/xibo#2671
=> Display - Profile Settings: Long profile values break the structure

web/theme/default/css/calendar.css
fixes xibosignage/xibo#2700
- CSS Selector fix
=> Schedule: add priority to the day drop down panel

lib/XTR/AuditLogArchiveTask.php, lib/XTR/StatsArchiveTask.php, tasks/auditlog-archiver.task, tasks/stats-archiver.task, views/dashboard-status-page.twig
Resolves xibosignage/xibo#2698
Resolves xibosignage/xibo#2699
=> Prevent JavaScript SyntaxError if vars are undefined

ui/src/core/xibo-cms.js
=> Date time picker: Needs to address AM/PM functionality

lib/Connector/ConnectorTrait.php, lib/Connector/PixabayConnector.php, lib/Connector/XiboExchangeConnector.php, web/swagger.json
Connectors should use default http client.
=> Prepare for 3.1.0-beta release. Update swagger.

lib/Controller/Base.php, lib/Report/ReportTrait.php, views/common.twig
2.2 is end of life and should not be used. These patches can be manually applied.
=> EOL: Patches for 2.2.x

lib/Controller/Base.php
2.0 is end of life and should not be used. These patches can be manually applied.
=> EOL: Patches for 2.0.x

lib/Controller/Base.php, lib/Entity/DataSet.php, lib/Helper/BlueImpUploadHandler.php, lib/Widget/Chart.php, lib/Widget/DataSetView.php, lib/Widget/Ticker.php, lib/XMR/PlayerAction.php, lib/XTR/StatsArchiveTask.php, lib/Xmds/Soap.php
1.8 is end of life and should not be used. These patches can be manually applied.
=> EOL: Patches for 1.8.x

lib/Controller/Base.php, lib/Report/ReportTrait.php
2.1 is end of life and should not be used. These patches can be manually applied.
=> EOL: Patches for 2.1.x

lib/Controller/DataTablesDotNetTrait.php
3.0 is end of life and should not be used. These patches can be manually applied.
=> EOL: Patches for 3.0.x

cypress/e2e/layout_designer_populated.cy.js
relates to xibosignage/xibo#2841
=> Tidy Cypress tests: fix region test

ui/src/editor-core/toolbar.js, ui/src/templates/designer.hbs
=> Layout Editor Viewer: Fix for overlay bug

cypress/e2e/layout_designer_empty.cy.js, ui/src/editor-core/toolbar.js
=> Layout Editor Viewer: 2nd Fix for overlay bug

views/help-form-add.twig
Just correcting the spelling line 45 :-)
=> Add missing T

views/layout-form-checkout.twig
Add the ability to translate the message of the form.
=> Add translation for the message.

modules/countdown.xml, modules/currencies.xml, modules/forecastio.xml, modules/src/player.js, modules/src/xibo-countdown-render.js, modules/stocks.xml, modules/templates/countdown-static.xml, ui/src/editor-core/properties-panel.js, ui/src/helpers/form-helpers.js
- Fix for non visible init rich text input
- Alignment options fixed
- Appearance tab fix for no properties
=> Countdown widget and other fixes

views/display-page.twig
=> Display Profile Settings: Player version override issue

lib/Connector/XiboAudienceReportingConnector.php, lib/XTR/CampaignSchedulerTask.php
fixes https://github.com/xibosignage/xibo/issues/2971
=> Ad Campaigns: adjust scheduler for no logged in displays

lib/Xmds/Soap.php, views/xibo-audience-connector-form-settings.twig
NB: Parent campaign on the media stat was an unreleased bug.
=> Audience Connector: Explain DMA on the form and fix parent campaign on media stat

lib/Controller/Layout.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Property.php, modules/clock-flip.xml, modules/src/player-bundle.js, modules/src/player.js, modules/src/xibo-worldclock-render.js, modules/worldclock-analogue.xml, modules/worldclock-digital-custom.xml, modules/worldclock-digital-date.xml, modules/worldclock-digital-text.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/templates/form-helpers-world-clock.hbs, ui/src/templates/forms/inputs/custom.hbs, ui/src/templates/forms/inputs/divider.hbs, views/common.twig
- 4 World clock widgets added
- Timezones added to layout editor page
- Custom and divider inputs added
=> WIP: World Clock

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Stencil.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/src/player.js, modules/src/xibo-image-render.js, modules/src/xibo-layout-animate.js, modules/src/xibo-layout-scaler.js, modules/src/xibo-metro-render.js, modules/src/xibo-text-render.js, modules/widget-html-render.twig
- Metro and Text: Animation and element tagging fixes
- Layout animate fix to allow generic containers
- Image render formatted for code convention
- displayDirection option fixed
- padding option added to stencils
- value options added to properties
=> Modules: Fixes for text and metro renderers

lib/Connector/TwitterConnector.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/DataType/SocialMedia.php, lib/Widget/Definition/Data.php, lib/Widget/Definition/Property.php, modules/templates/social-media-static.xml, modules/twitter.xml, package-lock.json, ui/src/core/forms.js, ui/src/templates/form-helpers-twitter-metro-colors.hbs, ui/src/templates/forms/inputs/checkbox.hbs, ui/src/templates/forms/inputs/code.hbs, ui/src/templates/forms/inputs/color.hbs, ui/src/templates/forms/inputs/custom.hbs, ui/src/templates/forms/inputs/date.hbs, ui/src/templates/forms/inputs/hidden.hbs, ui/src/templates/forms/inputs/number.hbs, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/text.hbs
- Bigger user profile image added to Twitter connector
- Custom data added to inputs
=> Modules: Convert Twitter templates and Metro

lib/Listener/OnMediaDelete/WidgetListener.php, lib/Middleware/ListenersMiddleware.php
Make sure we don't delete a widget during media delete if that widget is region specific
fixes xibosignage/xibo#2988
=> Library delete: fix for widgets being deleted

lib/Connector/XiboAudienceReportingConnector.php
xibosignageltd/xibo-private#97
=> Audience Connector: minor refactor to try and solve stalling task

views/playlist-form-add.twig, views/playlist-form-edit.twig
=> Playlist: Add form has a conflicting message and help text

modules/xibo-metro-render.js, package-lock.json
=> Widgets: Twitter Metro render crash with limited elements

views/user-welcome.twig
fixes https://github.com/xibosignage/xibo/issues/2982
=> Tutorial walk through dead ends

db/migrations/20230130114907_update_campaign_display_column_data_type_migration.php
https://github.com/xibosignage/xibo/issues/2953
=> Correcting data types of columns in Ad Campaigns/Displays migrations

views/user-welcome.twig
fixes https://github.com/xibosignage/xibo/issues/2982
=> Fix Display tour when auth is automatic

lib/Report/DisplayAdPlay.php, reports/campaign-proofofplay-report-form.twig, reports/display-adplays-report-form.twig, reports/display-percentage-report-form.twig, ui/src/core/xibo-cms.js
Fixes following reports on rounding spend/impressions and charts
- Campaign Proof of play
- Display Percentage
- Display ad plays
https://github.com/xibosignage/xibo/issues/2998
=> Connector Reports: minor adjustments and snagging

views/display-page.twig
- We used html and css to create pie charts for each clustered displays, Chart.js or D3 are not required.
=> Display Map: add display status as pie chart 

views/xibo-audience-connector-form-javascript.twig, views/xibo-audience-connector-form-settings.twig
- Adjusting  boolean `Is Geo?` status to tick/cross icon in DMA grid https://github.com/xibosignage/xibo/issues/2992
- Hide DMA grid when API key is missing https://github.com/xibosignage/xibo/issues/2983
=> Bug Fix for 3.3.3: Audience Reporting Connector

lib/Widget/Render/WidgetHtmlRenderer.php, modules/currencies.xml, modules/src/xibo-finance-render.js, modules/stocks.xml, modules/templates/currency-static.xml, modules/templates/stock-static.xml
relates to
xibosignageltd/xibo-private#117
xibosignageltd/xibo-private#118
- Module Twig translated
- **Still need to add flags for Currencies**
=> WIP: Convert Currencies and Stocks modules

views/display-page.twig
Cherry picked from https://github.com/xibosignage/xibo-cms/pull/1577
Issue: https://github.com/xibosignage/xibo/issues/3014
=> Display Map: add display status as pie chart

lib/Controller/DataSet.php, lib/Entity/DataSet.php, lib/routes-web.php, views/dataset-dataentry-page.twig, views/dataset-form-clear-cache.twig
- Remote DataSet : add Clear Cache function
Fixes xibosignage/xibo#3012
- DataSet data : Fix delete rows button
Fixes xibosignage/xibo#3013
=> DataSet : add clear cache function and fix delete rows button

ui/src/core/forms.js, ui/src/editor-core/properties-panel.js, ui/src/templates/actions-form-element-edit-template.hbs, ui/src/templates/forms/inputs/checkbox.hbs, ui/src/templates/forms/inputs/code.hbs, ui/src/templates/forms/inputs/color.hbs, ui/src/templates/forms/inputs/custom.hbs, ui/src/templates/forms/inputs/date.hbs, ui/src/templates/forms/inputs/divider.hbs, ui/src/templates/forms/inputs/dropdown.hbs, ui/src/templates/forms/inputs/header.hbs, ui/src/templates/forms/inputs/message.hbs, ui/src/templates/forms/inputs/number.hbs, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/text.hbs, ui/src/templates/forms/region.hbs, ui/src/templates/forms/widget.hbs
relates to xibosignageltd/xibo-private#100
- Widget common properties to use widgetId
- Fix for Region and Layout properties
=> Modules: Advanced fields

lib/Helper/QuickChartQRProvider.php, views/user-form-edit-profile.twig
- Add a case for `webp` image to `getMimeType()` in QuickChartQRProvider
- Small formatting adjustments
Fixes xibosignage/xibo#3018
=> Two Factor : fix for QR render with webp image

ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/templates/forms/layout.hbs, views/layout-designer-page.twig
fixes xibosignageltd/xibo-private#125
=> Layout Editor: Background image not working on form

modules/worldclock-analogue.xml, modules/worldclock-digital-custom.xml, modules/worldclock-digital-date.xml, modules/worldclock-digital-text.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/templates/forms/inputs/worldClock.hbs
resolves xibosignageltd/xibo-private#127
=> Advanced Input: World Clock Timezone

db/migrations/20230209132720_add_open_weather_map_connector_migration.php, lib/Connector/OpenWeatherMapConnector.php, views/openweathermap-form-settings.twig
- New Connector, get data from OWM and add to the provider on dataRequest
- Migration that adds the new connector
- Settings twig file for the new connector
=> Widgets : Open Weather Map Connector

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Option.php, lib/Widget/Definition/Property.php, modules/clock-analogue.xml, ui/src/core/forms.js, ui/src/templates/forms/inputs/add-ons/dropdownOptionImage.hbs, ui/src/templates/forms/inputs/dropdown.hbs, views/common.twig
resolves xibosignageltd/xibo-private#129
=> Module Inputs: Add image asset to dropdown control

ui/src/editor-core/toolbar.js, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#125
=> Layout Editor Background image fix

modules/src/xibo-webpage-render.js, modules/webpage.xml
resolves xibosignageltd/xibo-private#131
=> Convert Module: Web Page

modules/googletraffic.xml, modules/videoin.xml, ui/src/templates/forms/inputs/message.hbs
Fixes: 
- Google Traffic https://github.com/xibosignageltd/xibo-private/issues/133 
- Video In https://github.com/xibosignageltd/xibo-private/issues/132
=> Convert Modules: Google Traffic and Video In

modules/forecastio.xml
relates to xibosignageltd/xibo-private#130
=> Weather Module: No results message fix

modules/forecastio.xml
relates to xibosignageltd/xibo-private#130
=> Weather Module error message background fix

lib/Widget/Render/WidgetHtmlRenderer.php, modules/shellcommand.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/style/forms.scss, ui/src/templates/forms/inputs/commandBuilder.hbs, ui/src/templates/forms/inputs/commandSelector.hbs, views/authed.twig, views/common.twig
resolves xibosignageltd/xibo-private#134
=> Convert Module: Shell Command

lib/Entity/Module.php, lib/Factory/ModuleFactory.php
Fixes https://github.com/xibosignageltd/xibo-private/issues/135
=> Group for non datatype modules

db/migrations/20230220213618_update_play_list_timeline_help_link_migration.php, lib/Controller/Playlist.php
Fixes https://github.com/xibosignage/xibo/issues/3008
=> Playlist Editor: Help link needs to be changed 

lib/Factory/RegionFactory.php, ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss
resolves xibosignageltd/xibo-private#138
- Action flow fixed
=> Layout Editor: Interactive Drawer not being initialised properly

ui/src/layout-editor/main.js
fixes xibosignageltd/xibo-private#137
=> Layout Editor: Viewer doesn't refresh after upload

ui/src/editor-core/common.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/playlist-editor/main.js, ui/src/playlist-editor/playlist.js, ui/src/style/layout-editor.scss, ui/src/style/playlist-editor.scss, ui/src/templates/playlist-editor-external-container.hbs, views/region-form-timeline.twig
resolves xibosignageltd/xibo-private#142
=> Playlist Editor is broken from the Playlist grid page

modules/clock-analogue.xml, modules/clock-digital.xml, modules/clock-flip.xml, modules/countdown-clock.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/worldclock-analogue.xml, modules/worldclock-digital-custom.xml, modules/worldclock-digital-date.xml, modules/worldclock-digital-text.xml, ui/src/editor-core/toolbar.js, ui/src/style/toolbar.scss, ui/src/templates/toolbar-card.hbs, ui/src/templates/toolbar-content-group.hbs
resolves xibosignageltd/xibo-private#144
=> Layout Editor module groups

views/authed.twig
Fixes: https://github.com/xibosignage/xibo/issues/3023
=> Android Intent Command Control: Added extra shows plus instead of minus

lib/Entity/DisplayGroup.php
=> Display Group : Fix Display Group delete when linked to ad Campaign

lib/Widget/DataSetTicker.php, lib/Widget/DataSetView.php
=> DataSet Widgets : Fix direct library references.

ui/src/editor-core/toolbar.js, ui/src/templates/toolbar-card-media.hbs
=> Layout Designer: video thumbnails do not show in the toolbox for local video

ui/src/editor-core/properties-panel.js, ui/src/helpers/form-helpers.js, ui/src/layout-editor/main.js, views/common.twig
resolves xibosignageltd/xibo-private#141
=> Layout Editor Interactive: Delete action widgets from Drawer

ui/src/core/forms.js, ui/src/templates/forms/inputs/checkbox.hbs, ui/src/templates/forms/inputs/code.hbs, ui/src/templates/forms/inputs/color.hbs, ui/src/templates/forms/inputs/custom.hbs, ui/src/templates/forms/inputs/date.hbs, ui/src/templates/forms/inputs/divider.hbs, ui/src/templates/forms/inputs/dropdown.hbs, ui/src/templates/forms/inputs/header.hbs, ui/src/templates/forms/inputs/hidden.hbs, ui/src/templates/forms/inputs/message.hbs, ui/src/templates/forms/inputs/number.hbs, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/text.hbs, ui/src/templates/forms/inputs/worldClock.hbs, ui/src/templates/forms/region.hbs
Visibility and dependsOn for XML elements are added via JS. But for elements in other hbs templates, we need to add those properties in the HBS HTML directly. So this fix allows both options.
=> Fix for forms inputs not being added through XML

ui/src/editor-core/toolbar.js, ui/src/templates/toolbar-content.hbs
relates to xibosignageltd/xibo-private#146
=> Fix toolbar sub-menu save

lib/Widget/Ticker.php, modules/ticker-form-edit.twig
- In Layout Editor, Ticker widget will now have the option to set userAgent
Relates to: https://github.com/xibosignage/xibo/issues/2999
=> Ticker widget: add option to set the user agent

db/migrations/20230214135035_remove_dooh_user_type_migration.php, lib/Controller/Login.php, lib/Controller/User.php, lib/Entity/User.php, lib/Factory/BaseFactory.php, lib/Factory/DayPartFactory.php, lib/Factory/ScheduleFactory.php, lib/Factory/UserFactory.php, views/user-form-preferences.twig, web/swagger.json
- Removes DOOH user type from Users page
- Removes  option to select DOOH content (i.e., show content from) from user Preferences
https://github.com/xibosignage/xibo/issues/2912
=> Remove DOOH user type and option to select DOOH content

modules/subplaylist-designer-javascript.twig, modules/subplaylist.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/helpers/form-helpers.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/region.js, ui/src/playlist-editor/playlist.js, ui/src/style/common.scss, ui/src/style/forms.scss, ui/src/templates/form-helpers-sub-playlist-form.hbs, ui/src/templates/form-helpers-sub-playlist-header.hbs, ui/src/templates/forms/inputs/hidden.hbs, ui/src/templates/forms/inputs/playlistMixer.hbs, views/common.twig
resolves xibosignageltd/xibo-private#149
=> Convert Module: Sub-Playlist

lib/Widget/SubPlaylist.php
=> Widget: do not exception when a playlist ref on SubPlaylist cannot be found

lib/Entity/Widget.php, lib/Listener/WidgetListener.php, lib/Widget/Definition/Property.php, modules/subplaylist.xml, ui/src/core/forms.js, ui/src/templates/form-helpers-sub-playlist-form.hbs
~Foxes~ :fox_face: Fixes for missing WidgetEdit event. 
Further fixes for parameter names and upgrade step (upgrade step is pending the `WidgetCompatibilityInterface` to upgrade the options saved.
=> Modules: sub-playlist fixes after testing

ui/src/editor-core/toolbar.js, ui/src/playlist-editor/main.js
=> Toolbar results broken after adding a widget to the Playlist Editor

ui/src/editor-core/properties-panel.js
resolves xibosignageltd/xibo-private#156
=> Editor Properties Panel: Error saving stays even if its corrected

ui/src/core/forms.js, ui/src/helpers/form-helpers.js, ui/src/style/forms.scss, ui/src/templates/form-helpers-sub-playlist-container.hbs, ui/src/templates/form-helpers-sub-playlist-form.hbs, ui/src/templates/forms/inputs/playlistMixer.hbs
resolves xibosignage/xibo#2836
=> Sub-Playlist: re-order the playlists

modules/templates/currency-static.xml
relates to xibosignageltd/xibo-private#150
- Prevent render if content not returned from query
=> Flags added to second template and render fix

lib/Connector/AlphaVantageConnector.php, lib/Connector/OpenWeatherMapConnector.php, lib/Connector/TwitterConnector.php, lib/Controller/Widget.php, lib/Event/DataSetSnippetsRequestEvent.php, lib/Event/WidgetSnippetsRequestEvent.php, lib/Listener/DataSetDataProviderListener.php, lib/Widget/DashboardProvider.php, lib/Widget/DataSetProvider.php, lib/Widget/DataType/Article.php, lib/Widget/DataType/Event.php, lib/Widget/DataType/Forecast.php, lib/Widget/DataType/SocialMedia.php, lib/Widget/IcsProvider.php, lib/Widget/NotificationProvider.php, lib/Widget/Provider/WidgetProviderInterface.php, lib/Widget/RssProvider.php, lib/routes.php
* New route
* New event/widget provider
* Update existing providers to handle the new event
xibosignageltd/xibo-private#154
=> Modules: snippets implementation for the BE

lib/Controller/Playlist.php, lib/Entity/Widget.php, lib/Event/SubPlaylistWidgetsEvent.php, lib/Listener/WidgetListener.php
fixes xibosignageltd/rosetta#1034
=> Sub-Playlist: fix duration reported on widgets/layout when cycle playback is used

ui/src/editor-core/properties-panel.js
relates to xibosignageltd/xibo-private#149
=> Visibility flag for isTopLevel fix

lib/Controller/Layout.php, lib/Controller/Region.php, lib/Entity/Region.php, lib/Factory/LayoutFactory.php, lib/Factory/RegionFactory.php
These act as a place new widgets can be dropped to create either a frame/playlist.
fixes xibosignageltd/xibo-private#159
=> Regions: add a new region type called placehold

lib/Controller/Layout.php, lib/Controller/Region.php, lib/Entity/Region.php, lib/Factory/LayoutFactory.php, lib/Factory/RegionFactory.php
xibosignageltd/xibo-private#159
=> Regions: swap placehold to zone.

modules/forecastio-css-generator.twig
relates to xibosignageltd/xibo-private#153
=> Forecastio CSS generator restored

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Asset.php, lib/Xmds/Listeners/XmdsAssetsListener.php, lib/Xmds/Soap.php, modules/templates/currency-static.xml, modules/templates/dataset-static.xml, modules/templates/event-static.xml, modules/templates/forecast-static.xml, modules/templates/social-media-static.xml, modules/templates/stock-static.xml
xibosignageltd/xibo-private#152
=> Assets: prevent certain assets from being sent to the player.

modules/templates/article-static.xml
relates to xibosignageltd/xibo-private#161
=> RSS Ticker templates title fix

lib/Widget/RssProvider.php
- Fixes https://github.com/xibosignageltd/xibo-private/issues/160
=> RSS Ticker module: numItems not working

lib/Entity/Module.php, lib/Factory/ModuleFactory.php
- Fixes https://github.com/xibosignageltd/xibo-private/issues/173
=> Modules: Show a thumbnail inside the module card on the toolbar

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Property.php, modules/clock-digital.xml, modules/notificationview.xml, modules/templates/article-static.xml, modules/templates/event-static.xml, modules/text.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/helpers/form-helpers.js, ui/src/style/forms.scss, ui/src/templates/forms/inputs/dropdown.hbs, ui/src/templates/forms/inputs/snippet.hbs, views/common.twig
relates to xibosignageltd/xibo-private#164
relates to xibosignageltd/xibo-private#154
=> Modules: snippets property

lib/Factory/ModuleFactory.php, lib/Listener/DataSetDataProviderListener.php, lib/Widget/Definition/DataType.php, modules/templates/dataset-static.xml, ui/src/core/forms.js
relates to xibosignageltd/xibo-private#164
=> Snippet fix for dataset ticker

db/migrations/20230310143321_saved_report_move_out_migration.php, lib/Controller/Library.php, lib/Controller/SavedReport.php, lib/Controller/ScheduleReport.php, lib/Entity/SavedReport.php, lib/Factory/MediaFactory.php, lib/Factory/SavedReportFactory.php, lib/Listener/OnGettingDependencyFileSize/SavedReportListener.php, lib/Middleware/ListenersMiddleware.php, lib/Service/MediaService.php, lib/Service/ReportService.php, lib/XTR/ReportScheduleTask.php
Fixes: https://github.com/xibosignage/xibo/issues/2893
=> Reports: saved reports should not be stored in the media

lib/Report/ProofOfPlay.php
- Fixes https://github.com/xibosignage/xibo/issues/3032
=> Report: (3.3.4) Proof of play schedule report cannot filter by media/layout

modules/clock-digital.xml, modules/clock-flip.xml, modules/countdown-clock.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/embedded.xml, modules/googletraffic.xml, modules/templates/article-static.xml, modules/templates/currency-static.xml, modules/templates/dataset-static.xml, modules/templates/event-static.xml, modules/templates/forecast-static.xml, modules/templates/social-media-static.xml, modules/templates/stock-static.xml, modules/text.xml, modules/worldclock-digital-custom.xml, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/templates/toolbar-card-template.hbs, ui/src/templates/toolbar-card.hbs
relates to xibosignageltd/xibo-private#174
=> Modules/templates default size front-end

lib/Entity/Module.php, lib/Entity/ModuleTemplate.php, lib/Factory/ModuleFactory.php, lib/Factory/ModuleTemplateFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/GroupProperty.php, lib/Widget/Definition/Property.php, lib/Widget/Definition/PropertyGroup.php
- Fixes https://github.com/xibosignageltd/xibo-private/issues/175
=> Modules: Group properties

lib/Widget/ForecastIo.php
resolves xibosignage/xibo#3028
=> Weather widget: Background colour not being applied

views/report-schedule-page.twig, views/saved-report-page.twig
- Fixes https://github.com/xibosignage/xibo/issues/3035
=> Report Schedule: Owners/Type showing first item when they should be empty

reports/bandwidth-report-form.twig, reports/campaign-proofofplay-report-form.twig, reports/display-adplays-report-form.twig, reports/display-percentage-report-form.twig, reports/distribution-report-form.twig, reports/mobile-proofofplay-report-form.twig, reports/proofofplay-report-form.twig, reports/summary-report-form.twig, reports/timeconnected-report-form.twig, reports/timedisconnectedsummary-report-form.twig
- FIxes https://github.com/xibosignage/xibo/issues/2986
=> Reports: Apply button should show a progress cog

views/report-schedule-page.twig, views/saved-report-page.twig
- 3.3.4 Fixes https://github.com/xibosignage/xibo/issues/3035
=> Report Schedule: 3.3.4 Owners/Type showing first item when they should be empty

.github/workflows/build-container.yaml, .github/workflows/build-cypress.yaml, .github/workflows/build-tag.yaml, .github/workflows/test-suite.yaml, docker-compose.yml
relates to xibosignageltd/xibo-private#180
=> Env: swap to github container registry 

.github/workflows/build-container.yaml, .github/workflows/build-cypress.yaml, .github/workflows/build-tag.yaml, .github/workflows/test-suite.yaml, docker-compose.yml
relates to xibosignageltd/xibo-private#180
=> Env: swap to github container registry

lib/Entity/ModuleTemplate.php, lib/Factory/ModuleTemplateFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Factory/WidgetFactory.php, lib/Widget/Definition/Extend.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/templates/global-elements.xml
relates to xibosignage/xibo-private#190
=> Elements: new properties to support elements

ui/src/layout-editor/viewer.js
related to xibosignageltd/xibo-private#163
=> Editor theme calculate fix for null layout background

ui/src/playlist-editor/main.js, ui/src/style/playlist-editor.scss, ui/src/style/toolbar.scss, ui/src/templates/playlist-editor-external-container.hbs
[Playlist Editor: Add back button#168](https://github.com/xibosignageltd/xibo-private/issues/168)
=> Playlist Editor: Add back button

.gitignore, lib/Event/XmdsDependencyRequestEvent.php, lib/Widget/Render/WidgetHtmlRenderer.php, lib/Xmds/Soap.php, lib/Xmds/Soap3.php, lib/Xmds/Soap4.php, lib/Xmds/Soap7.php, tests/XMDS.http, tests/http-client.env.json
XMDS
- fix for outputting data correctly in v3 html, and for not doing that in v4.
- add some HTTP request for easy testing
- fix GetDependency in v7
=> Fixes during player testing

modules/templates/social-media-static.xml, ui/src/core/forms.js, ui/src/templates/forms/inputs/dropdown.hbs
relates to xibosignageltd/xibo-private#188
=> Layout Editor controls: Improve setDefault

lib/Connector/XiboSspConnector.php
- Fixes xibosignageltd/xibo-private#147
=> Incorrect Xibo API key could not be corrected in SSP Connector

tests/integration/ReportScheduleDataTest.php
- Fixes https://github.com/xibosignageltd/xibo-private/issues/204
=> Report Schedule test for summary report fails for DST 

lib/Factory/ModuleFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/ArticleWidgetCompatibility.php, lib/Widget/ClockWidgetCompatibility.php, lib/Widget/CountDownWidgetCompatibility.php, lib/Widget/DatasetWidgetCompatibility.php, lib/Widget/Definition/LegacyType.php, lib/Widget/SocialMediaWidgetCompatibility.php, lib/Widget/WeatherWidgetCompatibility.php, lib/Widget/WorldClockWidgetCompatibility.php, modules/countdown-clock.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/templates/article-static.xml, modules/templates/dataset-static.xml, modules/templates/forecast-static.xml, modules/templates/social-media-static.xml
- Relates to https://github.com/xibosignageltd/xibo-private/issues/182
=> Module migration: Legacy type

lib/Controller/Applications.php, lib/Controller/DisplayGroup.php, lib/Middleware/ApiAuthorization.php, lib/OAuth/AccessTokenRepository.php
- Set user on logService for API calls
- Audit Access token granted
- Audit Application approved/revoked (for authorization_code)
=> API Auth : improve auditing

db/migrations/20220330111440_modules_table_ver_four_migration.php
relates to xibosignage/xibo-private#190
=> Elements: insert the Canvas widget on migrate 

modules/text.xml
xibosignageltd/xibo-private#197
=> Testing: text property name incorrect somehow. 

lib/Entity/Module.php, lib/Factory/LayoutFactory.php
* Fix for the default layout importing without a playlist in the centre spot
* Fix for an error while uploading a video
related to https://github.com/xibosignageltd/xibo-private/issues/197
=> Misc fixes during initial private beta testing

.eslintrc.js, lib/Widget/Render/WidgetHtmlRenderer.php, modules/src/player.js, modules/widget-html-render.twig, ui/src/editor-core/toolbar.js, ui/src/layout-editor/main.js, ui/src/playlist-editor/main.js, ui/src/playlist-editor/playlist-timeline.js, ui/src/templates/playlist-timeline-widget.hbs
relates to xibosignageltd/xibo-private#212
- Fix toolbar templates for Playlist Editor
- DurationPerItem fixed for rendering
- Playlist Editor: Duration for widgets fix
- ESLint updated for switch statements
=> Multiple fixes for the layout and playlist editors

modules/templates/global-elements.xml, ui/src/core/forms.js, ui/src/editor-core/element.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/templates/forms/inputs/textArea.hbs, ui/src/templates/viewer-element-content.hbs, ui/src/templates/viewer-element.hbs, views/common.twig
relates to xibosignageltd/xibo-private#217
=> Text Element: Improve rendering

db/migrations/20220330111440_modules_table_ver_four_migration.php, modules/mastodon.xml
- Relates to  https://github.com/xibosignage/xibo/issues/3042
=> Module: Mastodon

.github/workflows/build-container.yaml, .github/workflows/build-tag.yaml, .github/workflows/test-suite.yaml
GHA: speed up builds with buildx and cache xibosignageltd/xibo-private#111
=> GHA: Speed up builds

.github/workflows/build-container.yaml, .github/workflows/build-tag.yaml, .github/workflows/test-suite.yaml
fixes xibosignageltd/xibo-private#111
=> GHA: use the github context instead of environment variables.

lib/Factory/ModuleTemplateFactory.php, lib/Factory/WidgetFactory.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/widget-html-render.twig
related to xibosignageltd/xibo-private#214
=> Elements: fix BE to output elements and their templates to the widget HTML

lib/Controller/Widget.php, lib/Entity/ModulePropertyTrait.php, lib/Widget/RssProvider.php
* Widgets: fix issue with saving templateId on edit.
* RSS: fix issue with date comparison deprecation.
=> Misc fixes during testing

lib/Widget/MastodonProvider.php, modules/mastodon.xml
- Relates to https://github.com/xibosignage/xibo/issues/3042
=> Module: Mastodon Cache Fix

ui/src/editor-core/toolbar.js
relates to xibosignageltd/xibo-private#221
=> Toolbar submenu save fix

lib/Controller/Applications.php, lib/Controller/Layout.php, lib/Controller/Library.php, lib/Controller/Playlist.php, lib/Controller/Schedule.php, lib/Dependencies/Controllers.php, lib/Entity/Campaign.php, lib/Entity/Layout.php, lib/Entity/Playlist.php, lib/Entity/Schedule.php, lib/Event/PlaylistDeleteEvent.php, lib/Factory/LayoutFactory.php, lib/Factory/MediaFactory.php, lib/Factory/PlaylistFactory.php, lib/Factory/ResolutionFactory.php, lib/Factory/ScheduleFactory.php, lib/Listener/LayoutListener.php, lib/OAuth/AccessTokenEntity.php, lib/Xmds/Soap.php, lib/routes-web.php, lib/routes.php, ui/src/core/xibo-calendar.js, ui/src/core/xibo-cms.js, views/authed-sidebar.twig, views/authed-topbar.twig, views/schedule-form-add.twig, views/schedule-form-edit.twig, views/schedule-form-now.twig, views/schedule-grid-page.twig
- Full Screen Schedule for Media and Playlist (Schedule Now on their respective grids and new events from Schedule/Calendar pages)
- Schedule Grid
- Fixed OAUTH token
=> Scheduling : Full screen schedule and Schedule Grid

lib/Xmds/Soap7.php, lib/Xmds/service_v7.wsdl
- Added GetWeather function in Soap 7, no actual weather returned yet
- Added GetWeather to wsdl v7 schema
=> XMDS : add GetWeather to Soap7 and wsdl v7

lib/Widget/AudioProvider.php, modules/audio.xml
- Relates to https://github.com/xibosignageltd/xibo-private/issues/213
=> Widget: Audio needs to have a duration provider 

db/migrations/20220915100902_add_fonts_table_migration.php, db/migrations/20220928091249_player_software_refactor_migration.php, db/migrations/20230310143321_saved_report_move_out_migration.php, lib/Middleware/Actions.php, lib/XTR/MaintenanceDailyTask.php
- Don't fail if the library location is not set by the time we migrate.
- Daily maint should ensure the library exists before copying the fonts over.
relates to xibosignageltd/xibo-private#109
=> Fonts: fixes for installation/migration

ui/src/templates/layout-editor.hbs, ui/src/templates/playlist-editor-external-container.hbs
resolves xibosignageltd/xibo-private#226
=> Playlist and Layout Editor: Consistent back button names and icons

modules/templates/dataset-static.xml, ui/src/core/forms.js
relates to xibosignageltd/xibo-private#234
=> Widgets: DataSet widgets are not currently working

ui/src/layout-editor/viewer.js
resolves xibosignageltd/xibo-private#230
=> Layout Editor: scale background with CSS

ui/src/editor-core/bottombar.js, ui/src/editor-core/widget.js, ui/src/style/layout-editor.scss, ui/src/templates/bottombar-viewer.hbs, views/common.twig
related to xibosignageltd/xibo-private#229
=> Delete stencil and bottom-bar fixed

modules/currencies.xml, modules/src/player.js, modules/stocks.xml
resolves xibosignageltd/xibo-private#228
=> Modules: sample data and initial properties

modules/currencies.xml, modules/stocks.xml
resolves xibosignageltd/xibo-private#228
=> Modules: use sample data text instead of actual data text

lib/Report/TimeDisconnectedSummary.php
- Fixes https://github.com/xibosignage/xibo/issues/3043
=> Reporting: Time Connected Summary

lib/Connector/AlphaVantageConnector.php, lib/Connector/OpenWeatherMapConnector.php, lib/Connector/TwitterConnector.php, lib/Connector/XiboDashboardConnector.php, lib/Controller/Widget.php, lib/Listener/DataSetDataProviderListener.php, lib/Listener/NotificationDataProviderListener.php, lib/Widget/IcsProvider.php, lib/Widget/MastodonProvider.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Provider/DataProviderInterface.php, lib/Widget/Render/WidgetDataProviderCache.php, lib/Widget/RssProvider.php, lib/XTR/WidgetSyncTask.php
So we can present an error message if there are configuration issues. 
related to xibosignageltd/xibo-private#236
=> Widgets: Data Providers should be explicitly handled

modules/dashboard.xml
resolves xibosignageltd/xibo-private#236
=> Dashboard Module: show not configured message on preview

cypress/e2e/report_bandwidth.cy.js, cypress/e2e/report_distribution.cy.js, cypress/e2e/report_library_usage.cy.js, cypress/e2e/report_proofofplay.cy.js, cypress/e2e/report_summary.cy.js, cypress/e2e/report_timeconnected.cy.js, cypress/e2e/report_timeconnectedsummary.cy.js
- Relates to https://github.com/xibosignageltd/xibo-private/issues/220
=> Testing: migrate reporting tests from PHPUnit to Cypress 

modules/templates/global-elements.xml
relates to xibosignageltd/xibo-private#244
=> Text Element: Horizontal align not working for long text

lib/Entity/Region.php, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/style/variables.scss, ui/src/templates/toolbar-card.hbs, ui/src/templates/viewer-widget.hbs
relates to xibosignageltd/xibo-private#232
- Playlist card turns frames and zones into playlists
- Zone regions highlighted
=> Layouts: new full screen layout leaves an empty invisible zone

lib/Report/TimeDisconnectedSummary.php
- Time Connected Summary does not show connected displays
- Fixes https://github.com/xibosignage/xibo/issues/3043
=> Reporting: (4.0.0 alpha) Time Connected Summary

lib/Factory/ModuleXmlTrait.php, lib/Factory/RequiredFileFactory.php, lib/Widget/Definition/Asset.php, lib/Widget/Render/WidgetHtmlRenderer.php, lib/Xmds/Soap.php
* Assets added twice to required files
* Data widgets for newer players should output null instead of empty structure
=> Player tests: fixes for widgets

lib/Controller/Display.php, lib/Xmds/Soap.php, views/display-page-manage.twig
=> XMDS: do not add resource nodes for canvas regions

ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#253
=> Layout select fix

lib/Connector/AlphaVantageConnector.php, lib/Controller/Widget.php, modules/stocks.xml, ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/style/layout-editor.scss, ui/src/templates/forms/inputs/connectorProperties.hbs
resolves xibosignageltd/xibo-private#196
=> Stocks Module: Stock symbol search

modules/src/handlebars-helpers.js, modules/src/player-bundle.js
resolves xibosignageltd/xibo-private#255
=> Player: Global elements error

lib/Connector/AlphaVantageConnector.php, lib/Connector/OpenWeatherMapConnector.php, lib/Connector/TwitterConnector.php, views/alphavantage-form-settings.twig, views/openweathermap-form-settings.twig, views/pixabay-form-settings.twig, views/twitter-form-settings.twig
fixes xibosignageltd/xibo-private#260
=> Connectors: fix connectors exposing platform provided settings

lib/Entity/DataSet.php, lib/Factory/LayoutFactory.php, lib/Widget/Compatibility/DatasetWidgetCompatibility.php, modules/hls.xml, modules/localvideo.xml, modules/templates/dataset-static.xml
- add missing local video widget
- fix dataset layout import in light of new v4 widget options
- don't notify dataset on layout import, it can't be active as its not imported yet
=> Minor fixes

cypress/e2e/folder.cy.js
- Related to https://github.com/xibosignage/xibo/issues/2916
=> Folders: add UI integration tests 

ui/src/core/forms.js
resolves xibosignageltd/xibo-private#256
=> Properties panel: Add check if condition target exists

modules/templates/global-elements.xml
resolves xibosignageltd/xibo-private#247
=> Element Line: Fix positioning for all tips

ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#266
=> Stencils: Allow editing element in the group

modules/templates/stock-static.xml
resolves xibosignageltd/xibo-private#259
=> Widget Stocks: Apply static stock widget background color

.gitignore, bin/locale.php, lib/Factory/ModuleFactory.php, lib/Factory/ModuleTemplateFactory.php, lib/Helper/NullSanitizer.php, lib/Service/BaseDependenciesService.php, lib/Service/LogServiceInterface.php, lib/Service/NullLogService.php, lib/Widget/Definition/Property.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/183
=> Translations from the config XML files 

bin/locale.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/183
=> Translation: Properties rule message fix

modules/htmlpackage.xml
fixes xibosignageltd/xibo-private#272
=> Widget: fix HTML package 

modules/stocks.xml
resolves xibosignageltd/xibo-private#259
=> Widget Stocks: Remove backgroundColor from stocks module

modules/currencies.xml, modules/stocks.xml, ui/src/core/forms.js
relates to xibosignageltd/xibo-private#256
- `reverseConversion` and `durationIsPerPage` also fixed for stocks and currencies
=> Fix for field visibility with multiple conditions

modules/src/xibo-elements-render.js
resolves xibosignageltd/xibo-private#258
=> Widgets: Fix player overlapping animations

modules/templates/dataset-static.xml
relates to xibosignageltd/xibo-private#262
=> Dataset template fix for empty datasetId

ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/playlist-editor/main.js, ui/src/style/playlist-editor.scss, ui/src/templates/form-helpers-data-set-order-clause.hbs
relates to xibosignageltd/xibo-private#270
- Simple form fields
- Advanced form fields
- Moveable
- Context menu
- Delete buttons
=> Layout Editor: Preview mode needs all inputs locked/disabled

package-lock.json, package.json, webpack.config.js
resolves xibosignageltd/xibo-private#278
=> Player bundle: Add babel plugin to support object rest spread

ui/src/editor-core/toolbar.js, ui/src/templates/toolbar-search-form.hbs
relates to xibosignageltd/xibo-private#280
=> Layout: upload new media item, view library button does not work

modules/templates/global-elements.xml
relates to xibosignageltd/xibo-private#283
=> Text Element: Add line height

ui/src/templates/viewer-element-content.hbs
relates to xibosignageltd/xibo-private#285
=> Editor: Elements style gets corrupted by editor style

ui/src/style/toolbar.scss, ui/src/templates/toolbar-card-layout-template.hbs
relates to xibosignageltd/xibo-private#279
=> Layout Editor: Templates in toolbar overflow

lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Property.php, lib/Widget/Definition/Rule.php, lib/Widget/Definition/Test.php, modules/countdown-clock.xml, modules/countdown-custom.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/dataset.xml
fixes xibosignageltd/xibo-private#277
=> Widget: validation to support type=OR and move message to test node

ui/bundle_templates.js, ui/src/core/forms.js, ui/src/style/common.scss, ui/src/templates/forms/inputs/add-ons/dateFormatHelperPopup.hbs
resolves xibosignageltd/xibo-private#274
=> Properties panel: Add date format helper popup

lib/Factory/LayoutFactory.php, lib/Widget/Agenda.php, lib/Widget/Calendar.php
=> Widget: agenda/calendar validation of custom interval

ui/src/editor-core/properties-panel.js, ui/src/layout-editor/region.js, ui/src/style/layout-editor.scss, ui/src/templates/forms/position.hbs
relates to xibosignageltd/xibo-private#289
=> Full screen button missing from positioning tab of static widgets

lib/Controller/Module.php, lib/Factory/ModuleFactory.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/297
=> Modules: Hide canvas module from grid

lib/Controller/Widget.php, lib/Entity/Widget.php, lib/Factory/LayoutFactory.php, lib/XTR/WidgetCompatibilityTask.php, modules/clock-analogue.xml, modules/clock-digital.xml, modules/clock-flip.xml, modules/countdown-clock.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/currencies.xml, modules/dataset.xml, modules/forecastio.xml, modules/stocks.xml, modules/subplaylist.xml, modules/worldclock-analogue.xml, modules/worldclock-digital-custom.xml, modules/worldclock-digital-date.xml, modules/worldclock-digital-text.xml
- Related to https://github.com/xibosignageltd/xibo-private/issues/286
=> Widget Upgrade: Compatibility Schema Versions

modules/templates/event-elements.xml
resolves xibosignageltd/xibo-private#295
=> Elements Calendar: Add calendar data as widget elements

lib/Controller/Schedule.php, lib/Factory/ScheduleFactory.php, views/schedule-page.twig
- Schedule Factory, do not use displayId in sql if we don't have it ;)
- Schedule - Fix PHP 8.1 dynamic properties warning (depends on displayGroup issue to be fixed, so it's actually set correctly in the first place)
=> Schedule page : misc fixes

ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#309
=> Layout Editor: Popups don't always work

lib/Controller/Action.php, lib/Controller/Font.php, lib/Controller/MediaManager.php, lib/Controller/PlaylistDashboard.php, lib/Entity/Layout.php, lib/Event/SubPlaylistItemsEvent.php, lib/Factory/FontFactory.php, lib/Factory/LayoutFactory.php, lib/Listener/WidgetListener.php, lib/Widget/Validator/DisplayOrGeoValidator.php, lib/routes-web.php, lib/routes.php, views/media-manager-page.twig, views/playlist-dashboard-spots.twig, views/playlist-dashboard.twig
Font: fix importing a layout with a font. Refactor to extract common parts: xibosignageltd/xibo-private#267
Actions: deprecated properties
Dashboards: start unpicking the errors with dashboards. Media manager needs form rendering (bump to FE), Playlist Dashboard might be OK as it, needs testing with upload forms, etc.
=> Misc fixes (fonts/actions)

lib/Controller/Layout.php, modules/templates/social-media-elements.xml, ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/editor-core/bottombar.js, ui/src/editor-core/common.js, ui/src/editor-core/history-manager.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/helpers/form-helpers.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/region.js, ui/src/layout-editor/viewer.js, ui/src/playlist-editor/main.js, ui/src/playlist-editor/playlist.js, ui/src/style/common.scss, ui/src/style/forms.scss, ui/src/style/layout-editor.scss, ui/src/style/toolbar.scss, ui/src/templates/forms/layout.hbs, ui/src/templates/forms/region.hbs, ui/src/templates/toolbar.hbs, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#166
- Layout background image triggers save
- Toast messages removed
- Loading overlay changed to a corner icon
- Fix style for date inputs in read only mode
- Layout Editor help added to toolbar
- Toolbar not refreshing when reloading viewer
=> Layout Editor: Automatic save

lib/Xmds/Soap5.php, tests/Xmds/SyncTest.php
relates to xibosignageltd/xibo-private#312
=> XMDS: move syncGroup to a settings node from attribute.

modules/src/player.js
resolves xibosignageltd/xibo-private#317
=> Elements: Preview rotation

ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/playlist-editor/main.js, ui/src/style/bottombar.scss, ui/src/style/layout-editor.scss, ui/src/templates/toolbar-search-form.hbs, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#318
- Save previous target when selecting a new one in the viewer
- Properties panel selective rendering to avoid field unfocus
- Viewer and topbar style updated
- Layout background form fixed for auto-save
=> Save improvements and fixes

modules/src/player.js
resolves xibosignageltd/xibo-private#320
=> Elements Preview: SVG Unique ID

db/migrations/20230530124400_widget_option_size_migration.php
relates to  - xibosignageltd/xibo-private#322
=> Widgets: increase the size of the value column.

ui/src/editor-core/common.js, ui/src/editor-core/element-group.js, ui/src/editor-core/element.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/templates/layout-editor.hbs, ui/src/templates/viewer-element-group.hbs, views/common.twig, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#328 xibosignageltd/xibo-private#325
- Single click to select Zones and Playlists
- Button added to playlist widget to edit it
- Select text in viewer disabled
- Overlay added to viewer when editing group
- Remove alert for reload page while saving
- Viewer object outlines tweaked
- Moveable rendering improved
- Add template with selected object error fix
=> Resize groups, add elements fixes and misc fixes

modules/templates/currency-elements.xml, modules/templates/global-elements.xml
relates to xibosignageltd/xibo-private#302
=> Currency logo fix

ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, views/common.twig
relates to xibosignageltd/xibo-private#331
=> Editor add template warning

ui/src/editor-core/properties-panel.js
relates to xibosignageltd/xibo-private#348
=> Playlist region: Positioning form is broken

ui/src/editor-core/properties-panel.js, ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#348
=> Select zone fix

modules/embedded.xml
relates to  xibosignageltd/xibo-private#350
=> Embedded: embedHtml field needs to be HTML code editor

ui/src/style/layout-editor.scss
relates to xibosignageltd/xibo-private#349
=> Viewer Full-screen button appears over notification menu

lib/Entity/TagLink.php
Relates to https://github.com/xibosignage/xibo/issues/3073
=> Tags : with options, without isRequired, allow empty value

lib/Controller/Library.php, lib/Controller/Schedule.php, lib/Entity/Module.php, lib/Entity/ModuleTemplate.php, lib/Entity/SyncGroup.php, lib/Entity/TagLink.php, lib/Factory/ModuleFactory.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/widget-html-render.twig, web/swagger.json
Modules: onDataError, relates to xibosignageltd/xibo-private#264
Swagger: fix openAPI annotations
=> Modules: add onDataError and API doc generation fixes

lib/Controller/Playlist.php, ui/src/editor-core/properties-panel.js, ui/src/playlist-editor/main.js, ui/src/playlist-editor/playlist-timeline.js, ui/src/playlist-editor/playlist.js, ui/src/style/playlist-editor.scss, ui/src/templates/context-menu.hbs, ui/src/templates/playlist-editor-external-container.hbs, ui/src/templates/playlist-editor.hbs, ui/src/templates/playlist-timeline-info.hbs, ui/src/templates/playlist-timeline-widget.hbs
relates to xibosignageltd/xibo-private#353
- Toggle for scaled mode in timeline
- Thumbnail for video in timeline
- Playlist Editor save doesn't reload property panel and toolbar
- Refactor for widget properties
- More labels added to context menu
- Duration formatted to hh:mm:ss
=> Playlist Editor new scale and tweaks

modules/src/xibo-text-render.js
relates to xibosignageltd/xibo-private#352
=> Ticker marquee not working

.github/workflows/phpcs.yaml, lib/Helper/Environment.php
Try adding the phpcs action as a separate workflow.
=> PHPCS: run action with every PR. xibosignageltd/xibo-private#340

modules/src/xibo-text-render.js, modules/templates/article-static.xml, modules/templates/event-static.xml, ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#352
=> Ticker marquee not working: More fixes

ui/src/editor-core/toolbar.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/bottombar.scss, ui/src/style/common.scss, ui/src/style/forms.scss, ui/src/style/layout-editor.scss, ui/src/style/playlist-editor.scss, ui/src/style/toolbar.scss, ui/src/style/topbar.scss, ui/src/style/variables.scss, ui/src/templates/layout-editor.hbs, ui/src/templates/toolbar-content.hbs, ui/src/templates/viewer-element-group.hbs, ui/src/templates/viewer.hbs, views/common.twig
relates to xibosignageltd/xibo-private#356
=> Element group: Add when click fails and move control layer

ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/layout-editor/region.js, ui/src/layout-editor/viewer.js, ui/src/templates/forms/region.hbs
relates to xibosignageltd/xibo-private#324
- Region select for static widgets
- Auto-save fixed for regions
- Auto-save when changing selected without saving fixed
=> Content Sync: add "syncKey" to "zone"

lib/Controller/Template.php, modules/subplaylist.xml, modules/video.xml, ui/src/editor-core/toolbar.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/common.scss, ui/src/templates/bottombar-viewer.hbs, ui/src/templates/context-menu.hbs, ui/src/templates/playlist-timeline-widget.hbs, ui/src/templates/toolbar-card-media.hbs, ui/src/templates/toolbar-card.hbs, ui/src/templates/toolbar-content-group.hbs, ui/src/templates/toolbar-content-submenu.hbs, views/common.twig, views/module-icon-preview.twig, views/playlist-dashboard-spots.twig, views/playlist-dashboard.twig, views/region-playlist-preview.twig, views/template-form-add.twig
relates to xibosignageltd/xibo-private#359
=> Adding Zones in template editing

lib/Controller/Region.php, ui/src/editor-core/properties-panel.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/region.js, ui/src/layout-editor/viewer.js, ui/src/templates/forms/position.hbs, views/region-designer-javascript.twig
relates to xibosignageltd/xibo-private#358
=> Position tab layer fixes

ui/src/templates/forms/region.hbs
relates to xibosignageltd/xibo-private#324
=> Change syncKey position in form

ui/src/editor-core/toolbar.js
relates to xibosignageltd/xibo-private#359
=> Remove lD references from toolbar

modules/src/player.js, modules/src/xibo-elements-render.js
resolves xibosignageltd/xibo-private#305
=> Widget: Mastodon Stencil profile preview fix

lib/Controller/Widget.php, ui/src/editor-core/properties-panel.js, ui/src/helpers/form-helpers.js, ui/src/style/layout-editor.scss
relates to xibosignageltd/xibo-private#360
=> Layout editor: Replace option missing for library widgets

ui/src/editor-core/widget.js
relates to xibosignageltd/xibo-private#362
=> Element slot: Logic of incrementing isn't always clear

modules/src/player.js, modules/templates/social-media-elements.xml
resolves xibosignageltd/xibo-private#238
=> Widget Preview: Implement slots

modules/templates/event-elements.xml, modules/templates/global-elements.xml, modules/templates/social-media-elements.xml
relates to xibosignageltd/xibo-private#363
=> Change Stencil date format to PHP

CONTRIBUTING.md, README.md
Revive dead links, nicer formatting for the page, licence/download badges, clearer installation/contributing instructions.
=> Readme Improvements

ui/src/editor-core/element-group.js, ui/src/editor-core/element.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/region.js, ui/src/templates/context-menu.hbs, ui/src/templates/forms/region.hbs, views/common.twig
relates to xibosignageltd/xibo-private#368
=> Context Menu: Add layer options

lib/Controller/Campaign.php, lib/Controller/Display.php, lib/Controller/DisplayGroup.php, lib/Controller/Folder.php, lib/Controller/PlayerSoftware.php, lib/Controller/Schedule.php, lib/Controller/User.php, lib/Controller/UserGroup.php, lib/Entity/PlayerVersion.php, lib/Entity/User.php, lib/Factory/DisplayFactory.php, lib/Factory/DisplayGroupFactory.php, lib/Factory/UserFactory.php, lib/Factory/UserGroupFactory.php, ui/src/core/xibo-cms.js, views/base.twig, views/display-form-membership.twig, views/displaygroup-form-members.twig, views/syncgroup-form-members.twig, views/user-form-membership.twig, views/user-page.twig, views/usergroup-form-members.twig
In addition to 3.3.7 issues
- Player Software : validate fileName on save to avoid duplicates
- Schedule Grid : Fix command type event end date
- Members forms : Fix sorting by member column in all of them (in v3 this only affects Display Group members form)
- Folders : Fixed Root Folder title
=> Fixes/issues from 3.3.7

db/migrations/20230727102500_menuboard_additional_fields_migration.php, lib/Listener/MenuBoardProviderListener.php, lib/Widget/DataType/Product.php, modules/menuboard-category.xml, modules/menuboard-product.xml, modules/templates/product-category-elements.xml, modules/templates/product-elements.xml, ui/bundle_templates.js, ui/src/core/forms.js, ui/src/editor-core/widget.js, ui/src/layout-editor/viewer.js, ui/src/style/common.scss, ui/src/style/layout-editor.scss, ui/src/style/toolbar.scss, ui/src/templates/forms/inputs/menuBoardCategorySelector.hbs, ui/src/templates/forms/inputs/menuBoardSelector.hbs, views/common.twig
relates to xibosignage/xibo#2790
=> Menu Boards: Implement with the new design tools: FE

lib/Middleware/SAMLAuthentication.php
(will do into 3.3.7 - tested by a user)
=> SAML support for OKTA

modules/src/xibo-elements-render.js
relates to xibosignageltd/xibo-private#365
=> Widgets Preview: Fix per item duration

lib/Controller/Font.php, lib/Controller/PlayerSoftware.php, lib/Entity/RequiredFile.php, lib/Middleware/ListenersMiddleware.php, lib/Widget/DataSetProvider.php, lib/Widget/Definition/Property.php, lib/Widget/IcsProvider.php, lib/Xmds/Listeners/XmdsFontsListener.php, modules/calendar.xml, modules/dataset.xml, modules/mastodon.xml, modules/menuboard-product.xml, modules/notificationview.xml, modules/rss-ticker.xml, web/xmds.php
Fixed:
- downloads for fonts via XMDS/CDN
- property validation of the default value, and conditions which use the value in the condition for the test
- numItems for dataset/calendar xibosignageltd/xibo-private#394
=> XMDS font fixes & duration/numItems

composer.lock, lib/Controller/DataSetData.php, lib/Factory/ModuleFactory.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Provider/DataProviderInterface.php, lib/Widget/RssProvider.php, modules/rss-ticker.xml
- DataSet correctly handle saving HTML in a HTML column type (sanitised for body)
- RSS Ticker correctly handle strip tags (previously dropped content)
=> Widgets: HTML sanitisation

lib/Entity/Module.php, views/common.twig
PDF duration on upload fix
Wording on tooltip
=> Minor Tweaks

lib/Connector/XiboSspConnector.php, lib/Entity/Module.php, modules/ssp.xml, views/common.twig, views/xibo-ssp-connector-form-settings.twig
[#408](https://github.com/xibosignageltd/xibo-private/issues/408)
=> SSP Widget

ui/src/editor-core/element.js
relates to xibosignageltd/xibo-private#409
=> Element: Place extended element properties on top

lib/Factory/ModuleFactory.php, lib/Listener/NotificationDataProviderListener.php, lib/Widget/Compatibility/NotificationViewCompatibility.php, lib/Widget/Definition/Property.php, lib/Widget/NotificationProvider.php, lib/XTR/WidgetCompatibilityTask.php, modules/calendar.xml, modules/datatypes/message.xml, modules/notificationview.xml, modules/templates/event-static.xml, modules/templates/message-elements.xml, modules/templates/message-static.xml, ui/src/core/forms.js
Widgets:
- add back range filtering and include for elements
- convert the notification widget to be data widget, add elements, reorganise properties and add compatibility class
Misc:
- effects form control wasn't working
- validation rules for testing a preset field value wasn't working
=> Calendar and Notification Widgets

modules/dataset.xml, modules/src/player-bundle.js, modules/templates/dataset-elements.xml, modules/templates/dataset-static.xml, ui/bundle_tools.js, ui/src/core/forms.js, ui/src/editor-core/properties-panel.js, ui/src/helpers/array.js
relates to xibosignage/xibo#2747
=> Dataset Elements: PR improvements

lib/Service/DisplayNotifyService.php
- Relates to xibosignage/xibo#3086
=> Interactive: make sure notifyByLayoutCode checks for scheduled actions.

lib/Entity/Layout.php, lib/Factory/LayoutFactory.php, lib/Service/DisplayNotifyService.php
- Fix Scheduled action  Relates to https://github.com/xibosignage/xibo/issues/3086
- Remove layout.xml from Layout export, Relates to https://github.com/xibosignageltd/xibo-private/issues/413
- Fix exporting fonts on Layout export, Relates to https://github.com/xibosignageltd/xibo-private/issues/412
=> Elements fonts and scheduled action fixes

lib/Event/NotificationModifiedDtRequestEvent.php, lib/Listener/NotificationDataProviderListener.php, lib/Widget/NotificationProvider.php, modules/countdown-clock.xml, modules/countdown-custom.xml, modules/countdown-days.xml, modules/countdown-table.xml, modules/countdown-text.xml, modules/notificationview.xml, modules/stocks.xml
* Stocks reverse conversion property is from currencies
* Countdown uses JS not supported on older browsers
* Notification widget caching too aggressive
=> Misc fixes 4

lib/Entity/ModulePropertyTrait.php, lib/Widget/IcsProvider.php, lib/Widget/RssProvider.php, modules/calendar.xml, modules/clock-digital.xml, modules/src/xibo-calendar-render.js, modules/templates/event-static.xml, modules/templates/global-elements.xml, ui/src/editor-core/topbar.js, ui/src/layout-editor/main.js, ui/src/style/toolbar.scss, ui/src/templates/forms/inputs/languageSelector.hbs, ui/src/templates/topbar.hbs, views/layout-designer-page.twig
A novel way to solve the issues returning data to the calendar between elements vs static. Also adding the language option.
=> Misc fixes 5

lib/Widget/MastodonProvider.php
- Related to https://github.com/xibosignageltd/xibo-private/issues/351
=> Mastodon: Exclude Reposts

lib/Controller/Display.php, lib/Controller/Module.php, lib/Entity/Widget.php, lib/Factory/ModuleFactory.php, lib/Factory/ModuleTemplateFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Factory/RequiredFileFactory.php, lib/Factory/WidgetFactory.php, lib/Widget/Definition/Asset.php, lib/Widget/Provider/DataProvider.php, lib/Widget/Render/WidgetHtmlRenderer.php, lib/XTR/WidgetSyncTask.php, lib/Xmds/Soap.php, lib/Xmds/Soap7.php, modules/mastodon.xml, modules/templates/social-media-static.xml
Assets: assets duplicating in required files
Assets: names must be unique, added the concept of an alias.
Display: media manager not counting asset file sizes.
Get data: should decorate with all cached files, regardless of whether they are linked to the display yet.
Widget Cache: should sync on D not W
[#434](https://github.com/xibosignageltd/xibo-private/issues/434)
=> Misc fixes 8

ui/src/editor-core/layer-manager.js, ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/templates/layer-manager.hbs, ui/src/templates/layout-editor.hbs, views/common.twig, views/layout-designer-page.twig
relates to xibosignageltd/xibo-private#436
=> Layout Editor: layer control

modules/src/player.js, modules/templates/product-elements.xml, ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#398
=> Menu Boards: Implement onTemplateRender and add fixes

ui/src/core/forms.js, ui/src/helpers/form-helpers.js, ui/src/layout-editor/viewer.js, ui/src/style/forms.scss, ui/src/style/variables.scss, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/textArea.hbs, views/common.twig
relates to xibosignageltd/xibo-private#433
- Zoom added
- Position on scroll with keyboard fixed
- Reload when resizing widget on viewer
=> Rich text tweaks

ui/src/editor-core/layer-manager.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/layout-editor/main.js, ui/src/style/layout-editor.scss, ui/src/style/variables.scss, ui/src/templates/layer-manager.hbs, views/common.twig
relates to xibosignageltd/xibo-private#436
- Layer Manager re-designed
- Max-height and scroll
- Z-index fix for manager to be in front of elements and properties panel
- Removed pref POST calls on toolbar load
- Add icons with the new icon system
=> Layer control fixes/tweaks

ui/src/core/forms.js, ui/src/editor-core/properties-panel.js, ui/src/templates/forms/inputs/add-ons/helpText.hbs, ui/src/templates/forms/inputs/checkbox.hbs, ui/src/templates/forms/inputs/code.hbs, ui/src/templates/forms/inputs/color.hbs, ui/src/templates/forms/inputs/date.hbs, ui/src/templates/forms/inputs/dropdown.hbs, ui/src/templates/forms/inputs/number.hbs, ui/src/templates/forms/inputs/richText.hbs, ui/src/templates/forms/inputs/text.hbs, ui/src/templates/forms/inputs/textArea.hbs, views/common.twig
relates to xibosignageltd/xibo-private#443
=> Layout and Region forms, add help text

modules/src/player.js, modules/templates/product-elements.xml
relates to xibosignageltd/xibo-private#398
=> Menu Boards: Fix rendering of product options onTemplateRender and calories

lib/Entity/Layout.php, lib/Entity/Module.php, lib/Factory/ModuleFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Widget/Definition/Asset.php, lib/Widget/Validator/DisplayOrGeoValidator.php, modules/forecastio.xml, ui/src/layout-editor/viewer.js
Implement required elements in the BE so that the "attribution" element must be provided when adding Weather. Also fixes for the weather icons not being included.
=> Required Elements and Weather fixes

ui/src/editor-core/layer-manager.js, ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/templates/layer-manager.hbs
relates to xibosignageltd/xibo-private#436
- Time added to canvas
- Update only when needed
=> Time format and fixes

ui/src/editor-core/properties-panel.js, ui/src/editor-core/toolbar.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss, ui/src/style/toolbar.scss, ui/src/templates/forms/widget.hbs, ui/src/templates/toolbar-card-item.hbs, ui/src/templates/viewer-element-content.hbs, views/common.twig
relates to xibosignageltd/xibo-private#446
=> Required elements for widgets

ui/src/editor-core/layer-manager.js, ui/src/style/layout-editor.scss, ui/src/templates/layer-manager.hbs, views/common.twig
relates to xibosignageltd/xibo-private#436
- Add template icons and names
- Add module icon
- Add group border to module icon
=> Layer Control: Multiple tweaks

composer.lock, lib/Middleware/SAMLAuthentication.php, lib/Service/DisplayNotifyService.php, package-lock.json, package.json
Shortly westphal will become develop, so this PR clears down develop ahead of that event. This will allow us to branch release33 from master, which feels better than branching that from develop.
=> Clear down develop ahead of v4 release.

cypress/e2e/campaigns.cy.js, cypress/e2e/folder.cy.js, cypress/e2e/report_bandwidth.cy.js, cypress/e2e/report_distribution.cy.js, cypress/e2e/report_library_usage.cy.js, cypress/e2e/report_proofofplay.cy.js, cypress/e2e/report_summary.cy.js, cypress/e2e/report_timeconnected.cy.js, cypress/e2e/report_timeconnectedsummary.cy.js, cypress/e2e/schedule.cy.js, cypress/support/commands.js, lib/XTR/SeedDatabaseTask.php
- https://github.com/xibosignageltd/xibo-private/issues/447
=> Alias along with its parameters

modules/src/player.js
relates to xibosignageltd/xibo-private#454
=> Widgets: Global elements and data value overriding render fixes

lib/Entity/DisplayProfile.php, lib/Entity/Region.php, lib/Entity/Widget.php, lib/Helper/LayoutUploadHandler.php
- Display profile config will now work with more odd configs
- Layout import with elements will get the correct widgetId inside of the elements widgetOption value
=> Pre release fixes

lib/Connector/XiboDashboardConnector.php, lib/Event/XmdsConnectorTokenEvent.php, lib/Factory/ContainerFactory.php, lib/Service/JwtService.php
- fix token generation xibosignage/xibo#3104
=> Dashboard widget:

lib/Connector/XiboDashboardConnector.php, lib/Event/XmdsConnectorTokenEvent.php, lib/Factory/ContainerFactory.php, lib/Service/JwtService.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/clock-analogue.xml, modules/clock-digital.xml, modules/forecastio.xml, modules/templates/article-static.xml, modules/templates/currency-elements.xml, modules/templates/dataset-static.xml, modules/templates/event-static.xml, modules/templates/forecast-elements.xml, modules/templates/message-static.xml, modules/templates/product-elements.xml, modules/templates/social-media-static.xml, modules/templates/stock-elements.xml, modules/text.xml, tests/XMDS.http
- Fix the dashboard widget
- Fix downloading widgets with library references
- Fix text widget using `let`
- Fix multiple widgets, templates and elements for `let` and `const`
=> Dashboard and Widget download fixes

db/migrations/20230727102500_menuboard_additional_fields_migration.php, lib/Entity/Display.php, lib/Entity/Playlist.php, lib/Widget/Compatibility/CalendarWidgetCompatibility.php, lib/Widget/Compatibility/ClockWidgetCompatibility.php, lib/Widget/Compatibility/CountDownWidgetCompatibility.php, lib/Widget/Compatibility/CurrenciesWidgetCompatibility.php, lib/Widget/Compatibility/DatasetWidgetCompatibility.php, lib/Widget/Compatibility/NotificationViewCompatibility.php, lib/Widget/Compatibility/RssWidgetCompatibility.php, lib/Widget/Compatibility/SocialMediaWidgetCompatibility.php, lib/Widget/Compatibility/StocksWidgetCompatibility.php, lib/Widget/Compatibility/SubPlaylistWidgetCompatibility.php, lib/Widget/Compatibility/WeatherWidgetCompatibility.php, lib/Widget/Compatibility/WorldClockWidgetCompatibility.php, lib/XTR/DynamicPlaylistSyncTask.php
Hold this PR for any further migration issues:
- Migration: fix menu board migration. xibosignage/xibo#3101
- Upgrade: digital clock turns analog. xibosignage/xibo#3109
- Upgrade: missing options aren't handled in compatibility classes
- Maintenance: PHP8 errors with regular maintenance xibosignage/xibo#3110
- Maintenance: Sync Dynamic Playlists task broken xibosignage/xibo#3111
=> Migration issues: 

lib/Controller/SyncGroup.php, lib/routes.php
Feature flags shouldn't disable getting a list of those things (only ones you have sharing for).
=> Feature fixes: fonts/sync groups

ui/src/playlist-editor/main.js
relates to xibosignage/xibo#3114
=> Inline Playlist Editor: Auto-save not working when selecting another item

lib/Controller/Schedule.php
- Schedule : Grid view, make sure we show relevant recurring events correctly - Relates to xibosignage/xibo#3119
=> Schedule : Better represent recurring events in the Grid.

modules/templates/event-static.xml
relates to xibosignage/xibo#3116
=> Calendar Widget: Upgrade from v3 and effects targets

lib/Controller/Layout.php, lib/Entity/Layout.php
- Widget transitions being left out of the XLF
- Auto apply default not being captured on add
=> Issues with transitions

modules/src/player.js
relates to xibosignageltd/xibo-private#264
=> Player: Add xiboIC.expireNow for elements and call xiboIC.reportFault

lib/Controller/Folder.php, lib/Entity/Folder.php, lib/Helper/XiboUploadHandler.php, lib/Service/DisplayNotifyService.php, ui/src/core/xibo-cms.js
- Interactive : notifyByLayoutCode should check scheduled actions (this was missing after branch changes)
- Library Upload : We should check if the playlist provided with the upload is editable
- Folders : Catch and Throw specific error when attempting to delete a Folder that is set as a homeFolder for any existing user
- Schedule : Fix issues with notifying Displays after updating a Layout (or Playlist) if the Schedule was using a user created day part.
=> 3.3.8 fixes

lib/Controller/User.php, lib/Middleware/Actions.php, reports/timeconnected-report-form.twig, views/dashboard-status-page.twig
3 fixes:
- dashboard jiggling on a 4k screen
- "tall rows" in time connected report
- force password change should disallow existing password
Note: this PR changes authentication.
=> Final bugs for 3.3.8 (cherry picked from v4)

lib/Controller/Module.php, lib/Controller/Widget.php, lib/routes.php, web/swagger.json
Modules: new routes to get a list of properties needed. Update Swagger docs with new routes and docs for widget edit. xibosignage/xibo#3102
=> Modules API docs

lib/Controller/Module.php, lib/Xmds/Soap5.php
- Dashboards cache clear doesn't work
- XMDS missing syncPublisherPort
=> Misc bug fixes 4.0.2 part 2

ui/src/editor-core/widget.js
relates to xibosignage/xibo#3088
=> Widget Expiry dates don't display the correct timezone

views/display-page.twig
- https://github.com/xibosignage/xibo/issues/3108
=> Bugfix: Display Map

views/display-page.twig
- Fixes https://github.com/xibosignage/xibo/issues/3108
=> Bugfix-4.0.2: Display map 

modules/templates/article-static.xml
relates to xibosignage/xibo#3116
=> Upgrade from v3 and effects targets

ui/src/core/xibo-cms.js, views/authed.twig
relates to xibosignage/xibo#475
=> Inline forms: Clear filters

modules/src/player.js, modules/src/xibo-elements-render.js, modules/templates/global-elements.xml, ui/src/core/forms.js, ui/src/editor-core/properties-panel.js
relates to xibosignageltd/xibo-private#438
=> Widgets: Enable marquee for widget elements

lib/Xmds/Soap7.php
=> XMDS: fix images downloading on new data 

ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js
relates to xibosignageltd/xibo-private#481
=> Layout Editor: onParseData doesn't get refreshed when element properties are changed

modules/templates/global-elements.xml
relates to xibosignageltd/xibo-private#477
=> Image Element: Add opacity

modules/src/player.js
relates to xibosignageltd/xibo-private#478
=> Elements: Fix for scroll horizontal and vertical effect

lib/Entity/Layout.php, lib/Entity/ModulePropertyTrait.php, lib/Widget/Definition/Property.php, modules/webpage.xml
XLF: incorrect options output, incorrect renderAs for webpage, incorrect application of filters saving URLs
fixes xibosignage/xibo#3140
=> Various issues with widgets that supply a URL

ui/src/core/forms.js
relates to xibosignageltd/xibo-private#482
=> Modules: visibility tests should work without a field

modules/src/player.js, modules/src/xibo-elements-render.js, ui/src/core/forms.js
relates to xibosignageltd/xibo-private#438
=> Widgets: Marquee fixes for marquee up/down

ui/src/editor-core/properties-panel.js, ui/src/helpers/form-helpers.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/style/layout-editor.scss
relates to xibosignageltd/xibo-private#483
- Fix for target changing when adding a new widget
- Fix text overlay in action preview
=> Delete widgets from drawer

ui/src/editor-core/properties-panel.js
relates to xibosignageltd/xibo-private#481
=> Fix for element groups

ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js
relates to xibosignageltd/xibo-private#483
=> Fix for missing option for delete object

modules/src/player.js, modules/src/xibo-elements-render.js
relates to xibosignageltd/xibo-private#438
=> Widgets: Marquee improvement for single element

lib/Controller/Playlist.php
=> Playlist editor: display the name on widgets correctly

lib/Helper/Environment.php, locale/default.pot
No changes to swagger and its too soon for updated translation MO files.
=> Release prep, bump 4.0.3

ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/editor-core/topbar.js
relates to xibosignageltd/xibo-private#484
=> Select2: Fix search focus

modules/text.xml, ui/src/core/forms.js, ui/src/editor-core/properties-panel.js
relates to xibosignage/xibo#3157
=> Widget: text flickers after upgrade (rich text)

.github/workflows/test-suite.yaml, cypress/e2e/report_summary.cy.js, cypress/e2e/schedule.cy.js
Cypress should save screenshots in artifacts and stop
=> Cypress - saving artifacts and misc fixes

lib/Widget/Render/WidgetHtmlRenderer.php, modules/src/player.js, modules/templates/global-elements.xml, modules/widget-html-render.twig, ui/src/layout-editor/viewer.js
relates to xibosignageltd/xibo-private#494
=> API: extend class missing escape attribute used for elements FE

modules/src/player.js
relates to xibosignageltd/xibo-private#264
=> Player: use reportFault second param object for setting targetId

modules/src/player.js
relates to xibosignage/xibo#3138
=> Widget elements: Mastodon shows username instead of post text and date is not formatted

views/common.twig
relates to xibosignageltd/xibo-private#504
=> Editors: Review all messages, labels and help text content

lib/Entity/DataSetColumn.php, lib/Widget/AlphaVantageBase.php, ui/src/core/file-upload.js, views/dashboard-status-page.twig
- Video Upload : no thumbnail without manually pausing/seeking in the video preview. Relates to https://github.com/xibosignage/xibo/issues/3153
- DataSets : Fix formula validation for `[DisplayGeoLocation]` replacement
- Stocks : Fix AlphaVantage api endpoints, they have changed them around :) . Relates to https://github.com/xibosignage/xibo/issues/3168
- Status Dashboard : Fix sql error when ordering by Faults column in Display grid. Relates to https://github.com/xibosignage/xibo/issues/3170
=> Bugfixes 3.3.9 issues

ui/src/editor-core/properties-panel.js, ui/src/layout-editor/main.js, ui/src/style/layout-editor.scss, views/common.twig
relates to xibosignageltd/xibo-private#483
- Removed delete button from PPanel
=> Add delete button to drawer widget select

lib/Controller/Widget.php, lib/Entity/Widget.php, lib/Factory/MediaFactory.php, lib/Factory/ModuleXmlTrait.php, lib/Service/MediaService.php, lib/Widget/Definition/Stencil.php, lib/Widget/Render/WidgetHtmlRenderer.php, modules/embedded.xml, modules/widget-html-render.twig
- Embedded widget modifications to bring back the "HEAD content" field and add a new JavaScript field. Also enhance the help text on those to make it clearer what's expected. https://github.com/xibosignage/xibo/issues/3141 and https://github.com/xibosignage/xibo/issues/3134
- Maintenance modified to avoid deleting files still linked to displays. https://github.com/xibosignage/xibo/issues/3143
=> Misc issues for 4.0.4

ui/src/editor-core/layer-manager.js, ui/src/editor-core/properties-panel.js, ui/src/editor-core/widget.js, ui/src/layout-editor/layout.js, ui/src/layout-editor/main.js, ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss
relates to xibosignageltd/xibo-private#503
- Select item on layer manager to put on top fix
- Canvas layer is also calculated
- Element group layer defaults to 0 for empty canvas
- Prevent multi refreshes when deleting element group
=> Layer manager fixes

modules/templates/forecast-elements.xml
relates to xibosignageltd/xibo-private#485
=> Widget: Weather background image choose from library

ui/src/playlist-editor/main.js
relates to xibosignage/xibo#3161
=> Playlists scroll inline fix

ui/src/layout-editor/viewer.js, ui/src/style/layout-editor.scss
relates to xibosignageltd/xibo-private#515
=> Multi-select tweaks

ui/src/core/forms.js, ui/src/core/xibo-cms.js, ui/src/style/common.scss, ui/src/templates/forms/inputs/color.hbs
relates to xibosignage/xibo#3092
=> Colour picker rendered off screen when at the bottom of the property panel

ui/src/layout-editor/main.js
relates to xibosignageltd/xibo-private#516
=> Editor interactions target fix
